coala/coala

coalib/parsing/CliParser.py
coalib/parsing/DefaultArgParser.py
coalib/tests/parsing/CliParserTest.py
coalib/tests/settings/SectionManagerTest.py

* Settings can now be specified with the parameter --settings (-S)
* Settings can still be of the form section.key=value
* Settings can not be mixed with traditional params anymore

Parsing: change way to set custom settings

---

coala
execute_all_tests.py
setup.py

According to several sources it is more platform independent to invoke
python via /usr/bin/env.
Please try it out and report if it works on your distribution!

Correct shebang

---

coalib/tests/TestHelper.py
coalib/tests/collecting/BearCollectorTest.py
coalib/tests/settings/SettingTest.py
execute_all_tests.py

One can get verbose output through passing the -v argument. If this
doesn't meet your needs because you need the ordering between
stderr/stdout you are encouraged to execute your test manually for
debugging.

tests: Shorten output

---

coalib/results/Diff.py
coalib/tests/results/DiffTest.py

We do matcher.get_grouped_opcodes(1) and assume that each change group
affects only one line in the origin and target file. However despit it
may affect only one origin line it may affect several target lines thus
we need to remove that assumption.
Fixes: https://github.com/coala-analyzer/coala/issues/316

Diff: Fix multiple line handling.

---

coalib/processes/BearRunner.py
coalib/tests/processes/BearRunnerTest.py

BearRunner now handles bears which may return an unexpected value.
Expected return value is a list of Results or None from a Bear.
fixes: https://github.com/coala-analyzer/coala/issues/256

BearRunner: Handle unexpected values from bears

---

doc/getting_involved/WRITING_TESTS.md

The old `unittest.Test` is the wrong class to inherit from.

writing-tests: Inherit from `unittest.TestCase`

---

coalib/output/printers/HTMLWriter.py
coalib/tests/output/printers/HTMLWriterTest.py

Add HTMLWriter class to enable writing HTML files. Also include
HTMLWriterTest to enable testing of the class methods.
Also derived work from WIP by Lasse Schuirmann (@sils1297)

printers: Add HTMLWriter - v2

---

coalib/tests/TestHelper.py

Changed method definition in run_tests() from show_nonexistent_test()
to show_nonexistent_tests(). In the method show_nonexistent_tests()
change the j variable to nonexistent_tests.
Fixes: https://github.com/coala-analyzer/coala/issues/384

TestHelper: Show error on passing invalid tests

---

.ci_coafile
.coafile
coalib/bearlib/parsing/clang/README.md
coalib/bearlib/parsing/clang/cindex.py
doc/Exit_Codes.md
doc/General_Dev_Info/git_tutorial_1.md

clang used an absolute import which isn't valid within the coala source
tree. With this the clang library can finally be used.

clang: Correct import

---

appveyor/appveyor.yml
appveyor/run_with_env.cmd
coalib/processes/SectionExecutor.py
coalib/tests/processes/SectionExecutorTest.py
coalib/tests/settings/SectionManagerTest.py
coalib/tests/settings/SettingTest.py

Appends the python file extension to coala. This allows Windows users
to run coala from command line if they have python in their PATH.
Also using the ".py" file extension is more consequent for python
files.

Last piece of windows compatability

---

doc/Getting_Involved/Writing_Tests.md

Missing the sys.path.insert() statement before the coala imports.

writing-tests-guide: Improve kickstart

---

.gitignore

This prevents files generated automatically by Kdevelop to be committed by accident. It is inline with the suppression of the PyCharm .idea files.

.gitignore: Ignore Kdevelop4 files

---

coalib/output/dbus/DbusDocument.py
coalib/tests/output/dbus/DbusDocumentTest.py

Fix for the issue brought up in https://github.com/coala-analyzer/coala/commit/240557a30a40ef1052f045b7a9eccbc2f2f81b61

DbusDocument: Add special handling for empty path

---

run_tests.py

The ignore list was not complete before, now it includes more python3
specific package locations that do not belong to this project.

tests: Improve ignore list

---

.misc/fail_if_HEAD_is_merge.sh
.rultor.yml

This will allow us to merge with a simple `@rultor merge` from
collaborators. It will prohibit any non fastforward merge.

rultor: Add rultor configuration

---

README.md

We only build on python 3.4 now.

README: Correct windows build info

---

.rultor.yml
circle.yml

We may rebuild old builds on master, we only want to upload that kind of
stuff when we merge to master so rultor is the option for that.

circle: Move zanata upload to rultor

---

coala

This makes it easy to execute the local coala version for development.
Also it fixes the deployment step which is currently failing on master
because of this file missing.

Add coala main file

---

.misc/deploy.pypi.sh
circle.yml

This will deploy automatically from master to pypi making the most
recent coala version available easily.

circleci: Add pypi deployment

---

.misc/deploy.coverage.sh
.misc/deps.sh
circle.yml
coalib/parsing/ConfParser.py
docs/Getting_Involved/Review.md
docs/Getting_Involved/Testing.md
docs/Getting_Involved/Writing_Tests.md

This is the most up to date uploader at any time and it fiddles with the
coverage data and should allow us to finally remove platform dependent
no covers.

coverage: Use future codecov

---

coalib/misc/StringConverter.py
coalib/parsing/CliParsing.py
coalib/parsing/LineParser.py
coalib/settings/ConfigurationGathering.py

1. If a coafile was not found, say "Using default" instead of "Thus it
will not be executed" (where the question arises "What is executed
instead?").
2. If a user saves sections via command line and the coafile did not
exist, don't say again "Thus it will not be used". The new inputted
information _is_ used. So just trigger no warning.
Fixes #367 - I hope I fixed this issue correctly^^

Refactor warnings when no coafile existent - see #367

---

coalib/tests/parsing/StringProcessingTest.py

Using repr(key) causes the output to wrap even the keywords in quotes.

StringProcessingTest: Use str(key) for assert msg

---

RELEASE_NOTES.md
bears/codeclone_detection/ClangCloneDetectionBear.py
bears/tests/codeclone_detection/ClangCloneDetectionBearTest.py
coalib/coala.py
coalib/coala_ci.py
coalib/coala_json.py
coalib/misc/Exceptions.py
coalib/output/dbus/DbusDocument.py

My evaluations have come up with 0.185 as a very good threshold value
that yields almost no false positives which is more important than a few
clones not found. If someone whishes to do a more elaborate examination
of clones he is hereby invited to raise the threshold manually.

ClangCloneDetectionBear: Reduce threshold

---

README.md

The link we used before was generated by readthedocs and doesn't put the
user into the documentation but into the public project view which is
rather useless.

README: Point to real documentation

---

coalib/results/Result.py

This has a higher chance of being unique since it's made for having a
high chance of uniqueness.
We use uuid4 because it generates a random UUID, other generators may
invade the users privacy by hashing in platform dependent data and
privacy is important :).

Result: Use uuid to generate id

---

coalib/output/ConsoleInteraction.py
coalib/tests/output/ConsoleInteractionTest.py

This simplifies the result printing by far because it splits out the
context printing of the result and gets rid of the state machine.
As a result functionality changes a bit, gets a bit simpler, because
we're getting rid of the complicated state machine with current file and
current line: the full context (file and the three lines before) is
printed for each result, even if it has the same file as the last one.
If no file but a line is given, it will simply be printed project wide
(way simpler: no file -> project wide. Ignore line.)
This is a preparation for getting the new results in. Plus a
simplification and code removal which is good too :).

ConsoleInteraction: Move out result context printing

---

.misc/appveyor.yml

This reverts commit 3d9a782f064109fea5a6a38e605fb3ae97f40fb4.
The appveyor related issue has been fixed and released upstream, see
https://github.com/myint/language-check/issues/19

Revert "Use language-check 0.7.2 explicitly"

---

bears/codeclone_detection/ClangFunctionDifferenceBear.py
bears/tests/codeclone_detection/ClangCloneDetectionBearTest.py
coalib/bears/Bear.py
coalib/settings/FunctionMetadata.py
coalib/tests/bearlib/spacing/SpacingHelperTest.py
coalib/tests/bears/BearTest.py
coalib/tests/settings/FunctionMetadataTest.py

We don't want to execute a bear if its value isn't in a type he desires.
Fixes https://github.com/coala-analyzer/coala/issues/800

Bear: Fail on inconvertible value

---

coalib/misc/Constants.py

In certain environments access to this directory might not be given.
coala should not fail to run because of this.

Constants: Pass on failure of tags dir creation

---

coalib/coala_main.py
coalib/tests/coalaTest.py

This is a fix for #1066. I've added a test case that verifies the original error is gone. What do you think about having fixtures as actual files in the tests folder? I have mixed feelings, as normal test cases shouldn't require the creation of extra files.

Use fail_acquire_settings in coala_main.py. Fixes #1066

---

coalib/misc/Decorators.py

Makes it shorter and more robust.
Fixes https://github.com/coala-analyzer/coala/issues/1024
@AbdealiJK @Makman2 can you review this ASAP? Until we merge this GitMate won't be able to associate results with their lines and not place comments accordingly :/

Decorators: Use dir() for get_public_members

---

coalib/tests/TestUtilities.py

The placeholder of current test executed scale automatically depending
on the count of tests to execute.
Before:
```
99/107 | TaggingTest
100/107 | TextPositionTest
```
After:
```
99/107 | TaggingTest
100/107 | TextPositionTest
```

run_tests: Auto-scale test count field size

---

.misc/appveyor.yml
.misc/deps.sh
bears/natural_language/MarkdownBear.py
bears/tests/natural_language/MarkdownBearTest.py

`mdast` was officially renamed to `remark`.

Migrate mdast to remark

---

coalib/tests/bearlib/abstractions/CorrectionBasedBearTest.py

`check_prerequisites` is now completely covered by the
`CorrectionBasedBearTest` itself.

CorrectionBasedBearTest: Make coverage standalone

---

coalib/processes/Processing.py
coalib/tests/processes/ProcessingTest.py

If an auto-apply action fails due to a raised exception, it's
considered unprocessed.

Processing: Treat failing actions as unprocessed

---

MANIFEST.in
requirements.txt

The requirements.txt is needed for setup execution and thus must be
included in the distribution. The other files are just nice to include
in a distribution... especially the license.
Another commit will be added soon which will upgrade pyprint to 0.1.1 as soon as it's out.

Add MANIFEST.in

---

bears/general/SpaceConsistencyBear.py

SpaceConsistencyBear shows "Trailing Whitespace" when
new line is missing.This is taken care of by comparing
the replacement with the original line with stripped off
new line and by adding a new line at the end.
Fixes https://github.com/coala-analyzer/coala/issues/1185

SpaceConsistencyBear: Remove "Trailing Whitespace"

---

coalib/output/ConsoleInteraction.py
coalib/tests/output/ConsoleInteractionTest.py

related to coala-analyzer #1124
Shows relative path in the results, does not have an option(as of now) to show absolute paths.

Show relative path in results output

---

coalib/results/result_actions/OpenEditorAction.py
coalib/tests/output/ConfWriterTest.py
coalib/tests/parsing/ConfParserTest.py

In many places, filehandler(r) is used when opening a file:
with open(..) as filehandler:
This is replaced with the word file, which is more semantic:
with open(..) as file:

CodeStyle: replace filehandler with the more mnemonic file

---

coalib/tests/settings/FunctionMetadataTest.py

this is about #971
there are 3 more usages of `__dict__` in our code, but those cannot be replaced (like `hasattr(__dict__)`).
We have 4 usages of `__len__` but all of them are function definitions, so that seems to be it

codestyle: Use builtin vars() instead of __dict__

---

coalib/bearlib/languages/documentation/doxygen.coalang

Closed  Issue #1143 
As Objective-C and PHP are C-styled languages , their commenting style is same as of java and c++ 
: referred Doxygen Manual 1.8.11

Added PHP and Objective-C in doxygen.coalang

---

coalib/results/SourcePosition.py
coalib/tests/output/ConsoleInteractionTest.py
coalib/tests/results/ResultFilterTest.py
coalib/tests/results/ResultTest.py
coalib/tests/results/SourcePositionTest.py
coalib/tests/results/SourceRangeTest.py

If absoloute path is not used, then comparison wouldn't work
between two SourceRanges, because the paths may be different.

SourcePosition: Use absoloute path for the file parameter

---

bears/general/LineLengthBear.py
bears/tests/general/LineLengthBearTest.py

We probably want to allow ignoring lines that e.g. contain a URL or
something else that cannot be shortened. Checkstyle does it this way and
I think that is good.

LineLengthBear: Add ignore_length_regex

---

setup.py

Installations on virtualenv result in errors on Mac and Windows
for unicode decode errors thrown by missing locales, This can
be resolved by adding locale before the setup.
Fixes: https://github.com/coala-analyzer/coala/issues/1268

Setup.py: Locale get and set avoids unicode error

---

docs/Users/Install.md

Some users can face a problem with setuptools throwing an error
This can be fixed by installing setup tools. This patch updates
the documentation for fixing errors for no module named
setuptools.
Fixes https://github.com/coala-analyzer/coala/issues/1288

Install.md: Add setuptools documentation

---

coalib/collecting/Collectors.py
coalib/parsing/DefaultArgParser.py
coalib/processes/Processing.py
coalib/tests/collecting/CollectorsTest.py

Currently there is not method to limit the files which coala would run on
in the command line arguments (without changing the coafile). This commit
adds a new argument namely "--limit-files" which ensures that coala does
not analyze any file outside the glob patterns mentioned in this argument.
This is useful specially when coala's analysis is required in only 1 file
like in the case of editor plugins.
Fixes https://github.com/coala-analyzer/coala/issues/1315

Collectors: Add limit_paths() & expose it in args

---

.misc/appveyor.yml

appveyor.yml: Appveyor clean up the PATH setting
change `appveyor.yml` for better readibility so that python paths are added in one line and Java paths are added in the next line
Fixes https://github.com/coala-analyzer/coala/issues/1334

Appveyor clean up the PATH setting.

---

.misc/tests.sh

Python 3.5 now supports PyLint. So, remove the skip.
Fixes https://github.com/coala-analyzer/coala/issues/1452

tests.sh: Allow PyLint Test for 3.5

---

.gitignore
conftest.py
setup.cfg
test-requirements.txt

Run pytest on multiple cores simultaneously using pytest-xdist
Due to undeterministic line of LocalBearTestHlper based
tests, we set PYTHONHASHSEED=0 to remove randomness from
hashes being computed in python.
Fixes https://github.com/coala-analyzer/coala/issues/1407

pytest: Run on multiple cores simultaneously

---

.misc/appveyor.yml
.misc/deps.osx.sh

GoImports added to deps.osx and appveyor build for travis
and appveyor to pass the goimports test.

.misc: Add missing goimports

---

coalib/coala_dbus.py
coalib/tests/coalaDbusTest.py

Move lambdas to functions so that they can be tested in
coalaDbusTest.py

coala_dbus: Move lambdas to functions

---

coalib/bearlib/abstractions/Lint.py

Tutorial link 'Linter Bears' added to the docstring of class `Lint`.
Fixes https://github.com/coala-analyzer/coala/issues/1551

lint: Add tutorial link to class docstring

---

coalib/tests/coalaCITest.py
coalib/tests/coalaFormatTest.py
coalib/tests/coalaJSONTest.py
coalib/tests/coalaTest.py

Earlier I had used `git grep "from bears"` to check if I had missed anything.
The integration tests do not need to import bears, so this removes the bears dependency from them

Fix a few more things to get bear independency

---

coalib/coala_json.py
coalib/parsing/DefaultArgParser.py
coalib/tests/coalaJSONTest.py

Add an argument option -o to coala-json to open a json file
and write the required output into the json file.
Add documentation on failure of the command telling correct
command coala-json to be executed
coala-json will display json data to console
coala-json -o filename.json implementation displays success message
Fixes https://github.com/coala-analyzer/coala/issues/846

coalib: Add flag -o to coala-json

---

setup.cfg

`-r s` shows more information about why a test has been
skipped. This is useful information and needs to be shown.
Fixes https://github.com/coala-analyzer/coala/issues/1623

pytest: Add cmd options to show skip reasons

---

coalib/output/ConsoleInteraction.py
coalib/results/result_actions/ShowPatchAction.py
coalib/tests/output/ConsoleInteractionTest.py
coalib/tests/results/result_actions/ShowPatchActionTest.py

Fixes https://github.com/coala-analyzer/coala/issues/1064

ConsoleInteraction: Revalidate actions when something happens

---

docs/Users/Tutorials/Linter_Bears.rst

Explanation of how `'{filename}'` is to be used in Linter Bears added to the tutorial.
First of the three updates to be made at: https://github.com/coala-analyzer/coala/issues/1557
/cc @AbdealiJK @sils1297

Linter Bear docs: Cover {filename}

---

coalib/results/SourcePosition.py
coalib/tests/output/ConsoleInteractionTest.py
coalib/tests/output/dbus/DbusDocumentTest.py
coalib/tests/output/dbus/DbusTest.py
coalib/tests/results/ResultFilterTest.py
coalib/tests/results/ResultTest.py
coalib/tests/results/result_actions/OpenEditorActionTest.py

This commit changes the path for affected files from absolute
to relative path w.r.t current directory path. This change
is essential for coala-html to work
Fixes https://github.com/coala-analyzer/coala/issues/1593

Sourceposition.py: Return relative paths

---

coalib/results/SourcePosition.py
coalib/tests/output/ConsoleInteractionTest.py
coalib/tests/output/dbus/DbusDocumentTest.py
coalib/tests/output/dbus/DbusTest.py
coalib/tests/results/ResultFilterTest.py
coalib/tests/results/ResultTest.py
coalib/tests/results/result_actions/OpenEditorActionTest.py

This reverts commit 47bb29a737e30b71214e0a4ef239498e7b325acf.
This commit introduced a known bug, the commit will be reapplied later
with a fix.

Revert "Sourceposition.py: Return relative paths"

---

coalib/output/ConsoleInteraction.py

This commit increases visibility of the tabs and spaces by
changing the color from gray to cyan, when the
SpaceConsistencyBear yields a Result.
Fixes https://github.com/coala-analyzer/coala/issues/1640

ConsoleInteraction: Tabs and spaces appear in cyan

---

coalib/bearlib/abstractions/Lint.py

When Lint tests are happening, we need better data to be able to
debug things.
One possibility is to use DEBUG log_messages, but this would give
a lot of data when `-L DEBUG` is used in the cmdline. Hence, we
simply save these variables to `self` so that LocalBearTestHelper
can handle it in a better way.
Related to https://github.com/coala-analyzer/coala-bears/issues/72

Lint: Save important debug info to self

---

coalib/misc/ContextManagers.py
coalib/tests/misc/ContextManagersTest.py

Like retrieve_stdout(), retrieve_stderr() is used for getting the
stderr buffer.
Fixes https://github.com/coala-analyzer/coala/issues/1658

ContextManagers: add retrieve_stderr()

---

coalib/collecting/Collectors.py

This adds a return annotation to collect_all_bears_from_sections()
function in Collectors.py
Fixes https://github.com/coala-analyzer/coala/issues/1495

Collectors.py: Add return annotation to function

---

docs/Users/Tutorials/Linter_Bears.rst

Added spaces before some parentheses in the "Right place for
'{filename}'" section.
Related to https://github.com/coala-analyzer/coala/issues/1557

Linter_Bears.rst: Add space before parentheses

---

coalib/output/ConsoleInteraction.py
coalib/tests/output/ConsoleInteractionTest.py

severity_str will output the corressponding severity message
Fixes: https://github.com/coala-analyzer/coala/issues/1313

coala-format: Add severity_str option

---

docs/Users/Tutorials/Self_Correcting_Bears.rst

Fixed a minor typo in `Self_Correcting_Bears.rst`

Self Correcting Bears doc: Fix typo

---

coalib/output/ConsoleInteraction.py
coalib/tests/coalaFormatTest.py
coalib/tests/output/ConsoleInteractionTest.py

ConsoleInteraction: Refactor format_str
In ConsoleInteraction.py, changed format_str in print_results_formatted
to match params. Also made changes to ConsoleInteractionTest.py
for consistency.
Fixes #1701

ConsoleInteraction: Refactor format_str

---

docs/Users/Install.rst

Changed vertualenv to virtualenv in docs/Users/Install.rst
Fixes https://github.com/coala-analyzer/coala/issues/1691

Install.rst: Fix typo in documentation

---

.travis.yml

.travis.yml : Fix the typo xontainer -> container
The third commented line had a typo "xontainer", which got fixed in this commit to "container".
Fixes https://github.com/coala-analyzer/coala/issues/1755

.travis.yml: Fix typo xontainer -> container

---

coalib/misc/Decorators.py

Documentation of get_public_members(obj) incorrectly mentions that
the method returns a list, whereas actually a dictionary is returned.
The Documentation is corrected and the key-value pair is mentioned.
Fixes https://github.com/coala-analyzer/coala/issues/1739

Decorators: Improves documentation

---

coalib/coala_delete_orig.py
coalib/tests/coalaDeleteOrigTest.py

When the user doesn't specify a `.coafile` there
is already an error message saying so, making this
line redundant.
Fixes https://github.com/coala-analyzer/coala/issues/1688

coala_delete_orig: Remove redundant message

---

coalib/results/Diff.py

Fixes https://github.com/coala-analyzer/coala/issues/1765

coalib/results/Diff.py: Fix typo in from_clang_fixit class

---

coalib/processes/Processing.py
coalib/tests/processes/ProcessingTest.py
docs/Users/Tutorials/Tutorial.rst

Previously a comment with `ignore` followed by
bear names in it will result in the following line
not being impacted by the bears. This commit
introduces globs for the same so that multiple matching
bears can be ignored easily.
Fixes https://github.com/coala-analyzer/coala/issues/1781

bear ignore: Add inline glob for bear ignore

---

coalib/bearlib/languages/definitions/__init__.py
coalib/bearlib/languages/definitions/c.coalang
coalib/bearlib/languages/definitions/python3.coalang

Currently .coalang files use escaped spaces for
multiword keys (example: `comment\ delimiter`). This
reduces readability a lot. Using underscores instead
will make this much easier and also future proof this.

coalang: Change multiword keys to be underscored

---

coalib/bearlib/languages/LanguageDefinition.py
coalib/bearlib/languages/definitions/__init__.py
coalib/bearlib/languages/definitions/c.coalang
tests/bearlib/languages/LanguageDefinitionTest.py

Add keywords and special characters for C and C++
Also added two new routines in coalang LanguageDefinition
that are useful.

coalang: Add keywords and special characters

---

.coafile

This section currently checks for broken or invalid
links into our docs, but is currently disabled so it
passes CI tests. It can be simply be enabled and ran
for a newcomer to replace or remove the links :)
Fixes https://github.com/coala-analyzer/coala/issues/1812

.coafile: Add disabled section for docs

---

coalib/bearlib/abstractions/Lint.py
tests/bearlib/abstractions/LintTest.py

Sometimes, linter bears need to check for a command as a
prerequisite. This commit introduces two new variables:
* prerequisite_command: the command to run as a list
* prerequisite_fail_msg: the message to display if the command
fails.
Two function now check for prerequisites:
* _check_executable() -> checks if the executable presents
* _check_command() -> check if the command prerequisite_command
returns an exitcode 0, else return prerequisite_fail_msg
Fixes coala-analyzer#1803

Lint: Refactor prerequisite checking

---

docs/index.rst

Line 142 had a spelling mistake : 'methode' instead
of 'methods'.
Fixes https://github.com/coala-analyzer/coala/issues/1872

docs: Fix typo in index.rst

---

coalib/parsing/CliParsing.py
coalib/parsing/DefaultArgParser.py
coalib/settings/ConfigurationGathering.py
tests/parsing/CliParsingTest.py
tests/settings/ConfigurationGatheringTest.py

When the user adds the flag `--no-config` to his coala command
the program will now default to the most basic coafile while
ignoring the coafile that may be present in the user diretory.
Fixes https://github.com/coala-analyzer/coala/issues/1838

coafile: Add option to ignore coafile

---

coalib/bearlib/languages/definitions/python3.coalang

python3.coalang had an unescaped # which caused it to be
unrecognisable by the parser. This PR escapes that

python3.coalang: Escape #

---

coalib/bearlib/abstractions/Lint.py
tests/bearlib/abstractions/LintTest.py

Used `shlex` module to split arguments in
subprocess.call() command
Fixes: https://github.com/coala-analyzer/coala/issues/1874

Lint: Fix subprocess command

---

README.rst

Add a list of advantages for users on why to use coala 
in the README page as it is the first page that a developer reads.
Fixes https://github.com/coala-analyzer/coala/issues/1851

README.rst: Add "Why use coala?" to README

---

coalib/misc/Constants.py
coalib/misc/Exceptions.py
docs/Users/Exit_Codes.rst
tests/misc/ExceptionsTest.py

Currently, when a requirement for coala is not met, the
default crash message is printed and exited. This commits handles
this exception by displaying why coala crashed along with
information about which package is at fault.
Fixes https://github.com/coala-analyzer/coala/issues/1748

Exceptions: Handle package version conflicts

---

requirements.txt

This one uses ~= and this we should escape dependency problems a bit.

requirements: Use latest PyPrint

---

coalib/coala_delete_orig.py
coalib/collecting/Collectors.py
coalib/misc/Constants.py
coalib/output/dbus/DbusDocument.py
coalib/parsing/Globbing.py
coalib/processes/Processing.py
coalib/settings/Section.py
coalib/settings/Setting.py
docs/Users/Glob_Patterns.rst
tests/parsing/GlobbingTest.py
tests/settings/SettingTest.py

When the coala directory's full path has brackets, the whole system breaks
because it is interpreted as alternatives. To fix this, the brackets are
escaped before use and then unescaped, leaving all functionality intact.
Fixes https://github.com/coala-analyzer/coala/issues/1613

Globbing: Add escape function for globs

---

coalib/bearlib/abstractions/Lint.py

Rename '_check_command' in file 'coalib/bearlib/abstractions/Lint.py'
to '_check_executable_command'
Fixes https://github.com/coala-analyzer/coala/issues/1887

Lint.py: Rename `_check_command` in Lint class

---

docs/Getting_Involved/Writing_Good_Commits.rst

Add example commit message about typos in
newcomer page in docs.
Fixes https://github.com/coala-analyzer/coala/issues/1757

docs: Add example commit message for typos

---

coalib/results/Diff.py
coalib/results/LineDiff.py
tests/results/DiffTest.py
tests/results/LineDiffTest.py

AssertionError doesn't make sense.
Fixes https://github.com/coala-analyzer/coala/issues/1951

LineDiff: Raise ConflictError on conflict

---

coalib/settings/Section.py
docs/Users/Tutorials/Writing_Bears.rst
tests/settings/SectionTest.py

To prevent misinterpretation of bear directories as glob expressions
we need to escape these characters. Also, we need to add real paths
to `sys.path` instead.
Introduced an extra assertion in tests to validate if bear directories
work as expected by having a directory with an unintended glob
expression.
Also mention that bear directories cannot be globs. Instead they
must be comma separated values.
Fixes https://github.com/coala-analyzer/coala/issues/1932
Fixes https://github.com/coala-analyzer/coala/issues/1831

Section: Escape bear directories before globbing

---

docs/Getting_Involved/Newcomers.rst

Add double backticks to make Pull Request more visible. I've also taken the
liberty of replacing mentions of `PR` with `Pull Request`.
Fixes #1783

Docs: Highlight `Pull Request` in Newcomer document

---

coalib/results/ResultFilter.py
tests/results/ResultFilterTest.py

This method ensures that deleted files and newly created files are
present in both dictionaries across coala runs. So that there are no
key errors.
Fixes: https://github.com/coala-analyzer/coala/issues/1866

ResultFilter: Add ensure_files_present method

---

.misc/appveyor.yml
.misc/deps.nltk.sh
.misc/deps.osx.sh
.misc/deps.sh
circle.yml

This commit fetches `nltk_data` so that imperative
mood test from `GitCommitBear` would work for coala.
Fixes https://github.com/coala-analyzer/coala/issues/2011

deps.nltk.sh: Add nltk_data installation in coala

---

coalib/bearlib/abstractions/Lint.py
coalib/bears/Bear.py
coalib/collecting/Dependencies.py
coalib/misc/Decorators.py
coalib/output/ConsoleInteraction.py
coalib/processes/BearRunning.py
coalib/settings/SectionFilling.py
docs/Users/Tutorials/Writing_Bears.rst

Frequently, we need to use the name of the bear
inside the bear.
This should add the name() function which allows
users to just do self.name() easily.
Fixes https://github.com/coala-analyzer/coala/issues/1893

Bear: Add helper function name()

---

coalib/results/Diff.py

Only tuples can be concatenated with tuples and lists with lists, mixing
is a bad idea and gives exceptions.

Diff: Convert newvalue to tuple if needed

---

coalib/processes/Processing.py
tests/processes/ProcessingTest.py

If a stop comment is not provided, the rest of the file from the
start comment will be ignored.
Fixes https://github.com/coala-analyzer/coala/issues/2003

Processing: Provide ignoring without stop comment

---

coalib/bearlib/abstractions/Linter.py

If there's no match, groups.get will return None and not an empty string
which isn't int convertible.
CC @Makman2 for review

Linter: Accept non-matches when converting

---

coalib/bearlib/abstractions/Linter.py

This is apparently used for some GNU stuff.

Linter: Accept information as severity by default

---

coalib/bearlib/abstractions/Linter.py
tests/bearlib/abstractions/LinterTest.py

If no explicit value is provided for a default value when using a
built-in output format, then it still appears in the partialmethod'ed
signature. `FunctionMetadata` grabs the metadata and forwards them to
the coala help. Now all arguments are omitted when defining a built-in
output format.

Linter: Omit partialmethod'ed signatures

---

coalib/results/Result.py

In class Result, ValueError message was corrected grammatically from
severity is no valid RESULT_SEVERITY to severity is not a valid RESULT_SEVERITY.
Fix: https://github.com/coala-analyzer/coala/issues/2020

Correct error message generated by Result.py

---

docs/Users/Exit_Codes.rst

Exit_Codes: Apply double backticks to references to `coala`
It is a command, so when it is referenced it should be in double
backticks.
As indicated, all references were replaced.
* A typo was also found & corrected
* Highlighting other custom words.
Fixes #2022

In docs/Users/Exit_Codes.rst apply double backticks to references to "coala"

---

docs/Users/Install.rst

This commit addresses the fix for error
caused due to using outdated PIP, in Install docs.
Fixes https://github.com/coala-analyzer/coala/issues/2124

Install.rst: Add PIP upgrade info

---

coalib/bearlib/abstractions/Linter.py

So users are able to log stuff.

Linter: Allow `self` in `create_arguments`

---

README.rst

This section is no longer used.
Fixes https://github.com/coala-analyzer/coala/issues/2162

README.rst: Remove OS X build section

---

coalib/coala_main.py
coalib/settings/ConfigurationGathering.py

`parse_cli` already has an option to collect `arg_parser`
and use it at [coalib/parsing/CliParsing.py#L41](https://github.com/coala-analyzer/coala/blob/master/coalib/parsing/CliParsing.py#L41).
`run_coala` should essentially collect the argparser
as it's the main method for executing the coala for all
purpose. This would allow to create a wrapper around
`default_arg_parser` and use that for processing. Failing
to do so throws an error as coala don't recognise new arg
options that aren't available in default_arg_parse.
Reference at [coalib/parsing/CliParsing.py#L51](https://github.com/coala-analyzer/coala/blob/master/coalib/parsing/CliParsing.py#L51)
Fixes https://github.com/coala-analyzer/coala/issues/1914
CC @AbdealiJK  @sils1297  @Uran198

coala_main.py: Pass argparser to `run_coala`

---

coalib/bears/requirements/PythonRequirement.py

Multiple method supports taking lists
as arguments.
Fixes https://github.com/coala-analyzer/coala/issues/2178

PythonRequirement: Add lists to multiple

---

coalib/results/Diff.py

Previously split_diff might not yield a diff at all for e.g. renamings.

Diff: Let split_diff return empty diffs

---

docs/Getting_Involved/Newcomers.rst

In line 106 of Newcomers.rst, changed "Your pull request doesn't," to
"Your pull request doesn't get accepted," as specified in issue #1993.
Fixes https://github.com/coala-analyzer/coala/issues/1993

Newcomer docs

---

coalib/output/ConsoleInteraction.py

Adds two spaces before description lines after the first
so that they all line up nicely
Fixes: https://github.com/coala-analyzer/coala/issues/2222

Formatting: Fix description indentations

---

test-requirements.txt
tests/settings/ConfigurationGatheringTest.py
tests/settings/conftest.py

Some of the ConfigurationGatheringTest test cases will fail if there are
any bears installed locally. To get around this for now we can simply
disable importing of all bears for this entire test suite.
Fixes https://github.com/coala-analyzer/coala/issues/2210

ConfigurationGatheringTest: Do not import bears

---

coalib/parsing/DefaultArgParser.py
tests/parsing/DefaultArgParserTest.py

Changes the help output to remove the metavars from the long descriptions.
They are still kept in the usage section.
Fixes https://github.com/coala-analyzer/coala/issues/2228

DefaultArgParser: Remove metavars

---

coalib/coala_main.py
coalib/results/result_actions/ApplyPatchAction.py
tests/coalaCITest.py
tests/results/result_actions/ApplyPatchActionTest.py

There's no need to crawl *every directory* every time for origs. This is
probably a huge performance hit on HDDs.

ApplyPatchAction: Keep track of origs

---

coalib/bears/Bear.py
coalib/collecting/Collectors.py
coalib/output/ConsoleInteraction.py
tests/collecting/collectors_test_dir/bears_local_global/bears1.py
tests/collecting/collectors_test_dir/bears_local_global/bears2.py
tests/output/ConsoleInteractionTest.py
tests/test_bears/JavaTestBear.py
tests/test_bears/LineCountTestBear.py

There's no point in having a tuple, and
('C','C++') should be the same with ('C++','C').

LANGUAGES: Change from tuple to set

---

coalib/bearlib/abstractions/Linter.py

This is not that useful, the bear writer should rather provide a URL for
more information manually, which is already done for most linter bears
anyway.
This reverts commit 60495403c9261f3ea8158213d5bf1330a6eb9b48.

linter: Don't show executable name automatically

---

coalib/bears/requirements/GemRequirement.py

This attribute is by default empty, and
can be specified if any flags are to be
used upon installation.

GemRequirement: Add require attribute

---

coalib/misc/StringConverter.py

Changed default arg into function using tuple
Fixes<https://github.com/coala-analyzer/coala/issues/2376>

StringConverter: Inline default argument of `list_delimiters` into function using a tuple

---

coalib/bearlib/abstractions/ExternalBearWrap.py
tests/bearlib/abstractions/external_bear_wrap_testfiles/ExternalBearWrapTest.py
tests/bearlib/abstractions/external_bear_wrap_testfiles/test_external_bear.py

Fixes https://github.com/coala-analyzer/coala/issues/2406
Fixes https://github.com/coala-analyzer/coala/issues/2368

ExternalBearWrap: Change JSON spec

---

coalib/bears/requirements/GoRequirement.py
tests/bears/requirements/GoRequirementTest.py

The install_command method builds the command from its Go attribute.
The is_installed method checks whether Go is installed or not.
Fixes https://github.com/coala-analyzer/coala/issues/2398

GoRequirement: Add installation methods

---

coalib/output/ConsoleInteraction.py
tests/output/ConsoleInteractionTest.py

When there is just one tab in one line, it throws an error because
it cant find the sourcerange end. This corrects it by decreasing
the sourcerange column end by 1.
Fixes https://github.com/coala-analyzer/coala/issues/2180

ConsoleInteraction: Fix empty line tab display

---

coalib/results/Result.py

Until we have a proper deterministic ordering, non-deterministic ordering is better than no coala at all.

Remove diffs from auto-generated ordering in Result

---

coalib/misc/DictUtilities.py

Change the result of inverse_dict to the correct value
Fixes https://github.com/coala-analyzer/coala/issues/2438

DictUtilities.py: Fix incorrect example in docstring

---

coalib/coala_main.py

Adding `arg_list` to `run_coala` provides control over
argument list for the APIs that uses `run_coala` to run
coala. For example: coala-html uses `run_coala` and requires some modification
in `arg_list` which isn't possible without exposing arg_list from run_coala
CC @sils1297 @Uran198

coala_main.py: Pass `arg_list` to run_coala params

---

coalib/processes/Processing.py
tests/processes/ProcessingTest.py

~~As the enumeration starts with 1 and addressing of lists is zero-based,
we need to decrement the `line_number`.~~

Processing: Use the right line for ignore range

---

coalib/bearlib/abstractions/ExternalBearWrap.py
coalib/bearlib/abstractions/Linter.py
coalib/bears/Bear.py
coalib/coala_delete_orig.py
coalib/coala_main.py
coalib/misc/Exceptions.py
coalib/output/ConfWriter.py
coalib/output/ConsoleInteraction.py
coalib/parsing/CliParsing.py
coalib/parsing/ConfParser.py
coalib/parsing/DefaultArgParser.py
coalib/parsing/LineParser.py
coalib/processes/communication/LogMessage.py
coalib/results/TextRange.py
coalib/settings/FunctionMetadata.py

Does not replace or in line 30 of
coalib/bearlib/languages/LanguageDefinition.py and
in line 139 of
coalib/bearlib/langugaes/documentation/DocstyleDefinition.py
because for any empty case of coalang_dir, we need the other one
and not the empty case.
Also does not replace whenever x is boolean.
Fixes https://github.com/coala-analyzer/coala/issues/1544

Replace or with inline if and vice-versa

---

coalib/output/ConsoleInteraction.py

When multiple settings are missing for a bear, the questions
may be out of order, with other questions in between them. This
may be inconvinient. So sorting the questions by the bears
should group the settings.
Fixes https://github.com/coala-analyzer/coala/issues/2530

ConsoleInteraction: Sort questions by bear

---

coalib/processes/Processing.py

This should decrease the I/O load and fix a bug where the
"Files that will be checked" message appears twice when run in
debug mode.
Fixes https://github.com/coala-analyzer/coala/issues/2544

Processing: Reuse file dicts loaded to memory

---

coalib/results/SourceRange.py
coalib/results/TextRange.py

Addresses #1963. Also fixes the docstring for `TextRange`, which had the same problem.

Fix range docstrings

---

docs/Users/Tutorials/Writing_Bears.rst

`self.new_result()` inside `run()` already takes over the `origin=self`
part, that was the whole purpose of this function.
As this is quite important, I just took this over myself :3

Writing_Bears.rst: Correct code example

---

setup.py

coalang files are needed for the new documentation extraction
functions that will be used to create new routines in coala-bears.

setup: Package coalang files

---

coalib/bearlib/abstractions/Lint.py

Updated the spelling for "succesfully" to "successfully" as per issue - https://github.com/coala-analyzer/coala/issues/2478

Updated the spelling for successfully in lint.py

---

docs/Users/Tutorials/Tutorial.rst
docs/Users/Tutorials/Writing_Bears.rst

The Tutorial.rst and Writing_Bears.rst files didn't include the
--show-description flags. Without them it shows a list of the Bears
without the full descriptions as spoken about in the tutorial.
Closes https://github.com/coala-analyzer/coala/issues/2528

Tutorial: Added --show-description to --show-bears

---

coalib/parsing/CliParsing.py
coalib/parsing/LineParser.py

Replace every mention of "touples" with "tuple." This affects both
comments and named variables, but doesn't affect functionality.
Closes https://github.com/coala-analyzer/coala/issues/2412

Parser: Fix instances of "touples"

---

coalib/parsing/CliParsing.py

Removes an unneeded assignment of arg_list in parse_cli.
Because parse_args uses sys.argv as default, we don't need to
assign it beforehand if none is given.
Closes https://github.com/coala-analyzer/coala/issues/2170

CliParsing.py: Remove arg_list assignment

---

coalib/collecting/Collectors.py

Argument bear_dirs of icollect_bears function renamed to bear_dir_glob
Fixes https://github.com/coala-analyzer/documentation/issues/52

Collectors.py: Rename argument bear_dirs

---

coalib/collecting/Collectors.py
tests/collecting/CollectorsTest.py

Improves the warning message when the user prompts to run a
bear and no matching bears are found.
Closes https://github.com/coala-analyzer/coala/issues/2402

Improve warning message

---

coalib/output/ConsoleInteraction.py
tests/output/ConsoleInteractionTest.py

It was not a useful functionality and was it is
not needed.

Remove ``sections`` parameter from ``show_bear``

---

coalib/output/ConsoleInteraction.py

Change the docstring to use :param settings_names_dict.
Closes https://github.com/coala-analyzer/coala/issues/2667

ConsoleInteraction.py: Rename param in docstring

---

coalib/coala_main.py
coalib/misc/CachingUtilities.py
tests/misc/CachingUtilitiesTest.py

This will ensure a cache store flush when the list of sections
to run changes.
Fixes https://github.com/coala-analyzer/coala/issues/2708

Caching: Compute hash only for enabled sections

---

coalib/results/result_actions/ShowPatchAction.py

Fix typo: ShowPatchAction.py: `Wether` -> `Whether`

Fix typo: ShowPatchAction.py: `Wether` -> `Whether`

---

coalib/output/ConsoleInteraction.py
tests/output/ConsoleInteractionTest.py

coala gives the user various options, among which "Apply no further
actions" is one of the options. This commit makes it as a default action
i.e. when there is no input from user
Closes https://github.com/coala-analyzer/coala/issues/2702

ConsoleInteraction:Add default behavior

---

coalib/bearlib/spacing/SpacingHelper.py
tests/bearlib/spacing/SpacingHelperTest.py

When converting spaces to tabs, spaces are being
added whenever one space is sufficient to reach
the next tab stop.
Fixes https://github.com/coala-analyzer/coala-bears/issues/811
Fixes https://github.com/coala-analyzer/coala-bears/issues/816

Keep existing tab instead of adding a space

---

circle.yml

The coala-ci -V command in circle.yml shows a lot of unnecessary info.
Removing it helps display only the relevant information
Fixes https://github.com/coala/coala/issues/2777

circle.yml: Remove -V tag

---

coalib/output/printers/LogPrinter.py
tests/output/printers/LogPrinterTest.py

Instead of asking the user to run coala with ``-L DEBUG``,
it's better to have exception tracebacks default.
Closes #2660

LogPrinter: Change log type DEBUG to log type info

---

coalib/output/ConsoleInteraction.py

print_affected_lines
Adds the document string to make it more understandable.
Closes https://github.com/coala/coala/issues/2801

ConsoleInteraction.py: Add document string to the method

---

coalib/settings/ConfigurationGathering.py

Fixes a typo in a docstring of the load_config_file function.
Closes https://github.com/coala/coala/issues/2661

ConfigurationGathering: Fix typo in docstring

---

coalib/output/ConsoleInteraction.py

Renamed result_list to result in docstring for print_affected_files.
Changed content of the docstring for result parameter.
Closes https://github.com/coala/coala/issues/2809

Change invalid parameter in docstring

---

CONTRIBUTING.rst
README.rst
coalib/parsing/DefaultArgParser.py
setup.py

everything is renamed, except Scrutinizer Code Quality (README 239-240) because coala account not exists.
ref #2813

rename coala-analyzer to coala

---

README.rst

README.rst: Remove (experimental) from caching feature point
Since the file caching support feature is now enabled by default, it is no longer experimental. Thus the word "experimental" must no more appear in the line describing the caching feature.
Fixes #2841

README.rst: Remove (experimental) from caching feature point

---

coalib/output/printers/ListLogPrinter.py

Issue: https://github.com/coala/coala/issues/2109
Remove definition of log_message from ListLogPrinter as it is already defined in LogPrinter

Remove code duplication in printers

---

coalib/settings/ConfigurationGathering.py

ConfigurationGathering.py: Add arg_parser doc
Add parameter arg_parser and its definition in the docstring
Closes https://github.com/coala/coala/issues/2811

Add arg_parser doc

---

coalib/bearlib/__init__.py
coalib/settings/FunctionMetadata.py
tests/settings/FunctionMetadataTest.py

This is useful in the generation of bear-docs to remove the
deprecated params from listing.

FunctionMetadata: Store params that are deprecated

---

coalib/collecting/Collectors.py
tests/collecting/CollectorsTest.py

This PR fixes issue #1476 
I have refactored the error message from <code>No bears were found matching 'pyLintBear'.</code> to <code>No bears matching 'pyLintBear' were found.</code>

Collectors: Fix error message

---

coalib/output/ConsoleInteraction.py
coalib/output/Interactions.py
coalib/settings/SectionFilling.py
tests/output/ConsoleInteractionTest.py
tests/output/InteractionsTest.py

Mention the section name when a required setting is
missing for the user.
The user will know what section is used.
Closes https://github.com/coala/coala/issues/2589

Mention the section when a setting is missing

---

tests/results/ResultTest.py

The variable expected_file is not used in that method.
Fixes https://github.com/coala/coala/issues/2915

ResultTest.py: Remove unused variable

---

README.rst

The installation of coala fails if the pip version is too low. The requirements for Python and pip have been added to make them easy to find.
This is the second pull request (in addition to https://github.com/coala/documentation/pull/238) needed to fix https://github.com/coala/documentation/issues/237

README.rst: Add min pip version

---

coalib/misc/CachingUtilities.py

Replaces "==" with "is" to check if "file_path" is
"None", to comply with PEP8.
Closes https://github.com/coala/coala/issues/2920

CachingUtilities.py: Replace "==" with "is"

---

README.rst

There is a change in line 149, changing langauge to language.
Closes https://github.com/coala/coala/issues/2935

README.rst: Fix typo "langauge" -> "language"

---

coalib/bearlib/__init__.py

Changes ``nondeterministic`` to ``non-deterministic``.
Closes https://github.com/coala/coala/issues/2838

bearlib/__init.py: Fix typo in docstring

---

coalib/bearlib/abstractions/Linter.py

Updates deprecated link to new link.
Fixes coala#2976

Linter.py: Replace deprecated link

---

README.rst

As it is already mentioned in Installation guidelines about minimum requirements, there's no need of having a separate prerequisites section to repeat the same thing.
Closes https://github.com/coala/coala/issues/2977

README.rst: Remove Prerequisite section

---

coalib/collecting/Importers.py
tests/collecting/ImportersTest.py

Make `_iimport_objects()` return all the objects found in the module if the `file_paths` is passed as the only param.
Fixes https://github.com/coala/coala/issues/2400

Importers: Allow file_paths as the only param

---

circle.yml
tests/bears/requirements/GoRequirementTest.py

'go' is not a buildable package and thus fails the install check of
GoRequirement. 'fmt' is the standard formatter that should come with go
and is definitely available even with an empty directory at $GOPATH
Backports 15c346699cd2 to releases/0.8, as this is one of the problems
with the coala/docker-coala-base Travis builds.

GoRequirement: Fix Test

---

coalib/bearlib/abstractions/Linter.py

Add space after comma just before "error" in coala.coalib.bearlib.abstraction.Linter.py line 703
closes https://github.com/coala/coala/issues/3088

Linter.py: Add missing space after comma

---

tests/bears/BearTest.py

Implements @userzimmermann 's suggestions on last merge
Verify that test_download_cached_file is caching the file
by verifyign that the first run time matches the second run.
Also verify that the file does not exisist when starting.
Add tear_down to TestBear class to delete its data directory
when it's work is done

BearTest.py: Add timestamp test to verify caching

---

coalib/bearlib/abstractions/Linter.py

Linter.py: Add Missing backtick on line 705,
https://github.com/coala/coala/blob/master/coalib/bearlib/abstractions/Linter.py#L705
This is syntactically correct .
Fixes https://github.com/coala/coala/issues/3089

Linter.py: Add Missing backtick

---

requirements.txt
test-requirements.txt

A version spec like ~=0.1 would also install 0.9.5, if it's not
specified as ~=0.1.0.
Discussed at https://gitter.im/coala/coala?at=5838551f8d65e3830e9c369e

Update requirements to use ~=, properly

---

coalib/bearlib/languages/definitions/CSS.py
coalib/bearlib/languages/definitions/CSharp.py
coalib/bearlib/languages/definitions/Java.py
coalib/bearlib/languages/definitions/JavaScript.py

The language definitions for CSS, Java and JavaScript used
a single string value for the extensions attribute, as opposed to
tuples used elsewhere where multiple values may be needed,
including the aliases attribute.
Also add attribute extensions to the C# language definition.
cc @sils

Language: Change Language.extensions to tuples

---

coalib/bearlib/languages/__init__.py
coalib/bearlib/languages/definitions/Unknown.py

This language definition is to be used when language is not known.
Backport of https://github.com/coala/coala/pull/3173

Language: Add Unknown language

---

requirements.txt

libclang-py3 3.4 retains compatibility with clang 3.4,
being identical source code to libclang-py3 0.2 except
it includes one bug fix.
https://github.com/coala/coala/issues/3187

Upgrade libclang-py3 from 0.2 to 3.4

---

docs/Developers/Writing_Good_Commits.rst

This fixes 'Possible title underline, too short for the title'
issues reported by RSTcheckBear on the file.
Closes https://github.com/coala/coala/issues/3147

Writing_Good_Commits.rst: Fix spacing issues

---

PULL_REQUEST_TEMPLATE.md
README.rst
RELEASE_NOTES.rst
docs/Developers/Git_Basics.rst
docs/Developers/Writing_Documentation.rst
setup.py

Changed all instances of 'readthedocs.org' to 'readthedocs.io' and to 'api.coala.io' in case of Developers Section.
Reason: Moved the docs to the new url.
Closes https://github.com/coala/coala/issues/2085 
Ping! @sils

Change TLD from .org to .io

---

docs/Developers/Writing_Linter_Bears.rst

The text "API documentation" links now to
"http://api.coala.io/en/latest/".
Closes coala/documentation#21
@Adrianzatreanu 
@userzimmermann

Writing_Linter_Bears.rst: Link to API documentation

---

README.rst

use_spaces option is more clearer now
by having an url about the SpaceConsistencyBear.

README.rst: Add clearer message to README's Usage section

---

coalib/bearlib/abstractions/Linter.py
tests/bearlib/abstractions/LinterTest.py

Using capture groups affect the performance of coala, and it should be
discouraged.
Fixes https://github.com/coala/coala/issues/2070
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/coala/coala/2895)

Linter: Warn the user to not to use capture groups

---

coalib/__init__.py
tests/coalaTest.py

The logic in 805d8a0c to prevent installation on Python 3.3
was incorrect as Version 3.3.1 is greater than Version 3.3,
so only 3.3.0 was rejected by the current logic.
Fixes https://github.com/coala/coala/issues/3310

assert_supported_version: Reject Python 3.3.x

---

tests/processes/ProcessingTest.py

When we write Ignore all, all of the bears should
be ignored for that specific line.
Closes https://github.com/coala/coala/issues/3307

ProcessingTest.py: Add test for 'Ignore all'

---

coalib/bearlib/aspects/__init__.py

This ensures the correct formatting.
Fixes #3329

coalib/bearlib/aspects/__init__.py: Fix doc string syntax

---

.misc/deps.sh

Fails the build if it detects less than 2 circle containers because our tests
cannot run on only one container
Closes https://github.com/coala/coala/issues/3352

deps.sh: Fail if less than 2 circle containers

---

coalib/processes/Processing.py
tests/processes/ProcessingTest.py

Some other linters use 'noqa' so the addition of this keyword would make coala backwards compatible.
closes #2533

Add `noqa` to the keywords to start ignoring bears

---

.travis.yml
setup.py

Avoids pycodestyle import errors.
All of the imports from coalib do not depend on large amounts of coalib.

setup.py: Move Python version assert after imports

---

.travis.yml

d960d125 moved .misc/tests.sh into an if statement,
followed by other commands.  This meant that if tests.sh
failed the exit status would be lost.

TravisCI: Error on failed tests

---

README.rst

The resolution of the coala banner is
1920 x 693, it has now been resized to
1086 × 387 to fit the page and stop the
scrolling caused by the large image.
Fixes: https://github.com/coala/coala/issues/3340

README.rst: coala banner too big on pypi page

---

tests/bearlib/abstractions/LinterTest.py

Replaced assertRaises with assertRaisesRegex in LinterTest.py file
I am not confident about the strings used, incase I have done it wrong, please tell me, I will fix it. 
Task: https://codein.withgoogle.com/dashboard/task-instances/4861422196490240/

assertRaisesRegex used in LinterTest.py

---

coalib/settings/DocstringMetadata.py
tests/settings/DocstringMetadataTest.py

Ensures that there is no unneeded space after opening parenthesis
while prompting a user for required setting.
Fixes https://github.com/coala/coala/issues/3164

DocstringMetadata.py: Remove unneeded space

---

.travis.yml

It is no longer necessary.
Related to https://github.com/coala/coala/issues/3184

TravisCI: Remove explicit py upgrade

---

tests/bearlib/abstractions/LinterTest.py

Change the variable name PARAM_TYPERERROR_RE to
PARAM_TYPE_ERROR_RE.
Fixes https://github.com/coala/coala/issues/3418

LinterTest.py: Fix typo in variable name

---

coalib/results/Result.py

It modifies docstring param definition of diffs
as it was confusing. There should be only one
diff object attached with a particular filename.
Also, it modifies Result.apply code to make it
more readable.
Fixes https://github.com/coala/coala/issues/3034

Result.py: Modify docstring definition of diffs

---

test-requirements.txt

pytest dependencies are higher and more important
than those listed by its plugins.
Closes https://github.com/coala/coala/issues/3184

test-requirements: Put pytest before its plugins

---

coalib/results/result_actions/PrintAspectAction.py
tests/results/result_actions/PrintAspectActionTest.py

The ``PrintAspectAction.py`` is an action that prints
information pertaining to the Aspect associated with
a Result.
Fixes https://github.com/coala/coala/issues/2959

result_actions: Write an AspectResultAction

---

.travis.yml
circle.yml

Before we can remove the python dependencies from
the coala-bears install requirements, the other coala
repositories need to switch to using the 'alldeps'
extra.
Related to https://github.com/coala/coala-bears/issues/1000

CI: Use coala-bears extra 'alldeps'

---

coalib/output/ConsoleInteraction.py
coalib/processes/Processing.py
coalib/results/result_actions/IgnoreResultAction.py
coalib/results/result_actions/OpenEditorAction.py
coalib/results/result_actions/PrintAspectAction.py
coalib/results/result_actions/PrintDebugMessageAction.py
coalib/results/result_actions/PrintMoreInfoAction.py
coalib/results/result_actions/ResultAction.py
coalib/results/result_actions/ShowPatchAction.py
tests/output/ConsoleInteractionTest.py
tests/processes/ProcessingTest.py
tests/results/result_actions/ApplyPatchActionTest.py
tests/results/result_actions/IgnoreResultActionTest.py
tests/results/result_actions/OpenEditorActionTest.py
tests/results/result_actions/PrintAspectActionTest.py
tests/results/result_actions/PrintDebugMessageActionTest.py
tests/results/result_actions/PrintMoreInfoActionTest.py
tests/results/result_actions/ShowPatchActionTest.py

This commit changes the is_applicable method to return
the 'not_applicable' message when the result action is not applicable.
It also change the message type from:
Selected default action `PatchAction` for bear `Bear`
is not applicable.
To:
`Bear`: `Custom not_applicable message`
Closes https://github.com/coala/coala/issues/3169

Custom 'not applicable' message for result action

---

coalib/parsing/DefaultArgParser.py
coalib/processes/Processing.py
tests/processes/ProcessingTest.py

Added settings for turning off the warning
about patches not being auto applicable
`coala --no-autoapply-warn` turns off
warning
Closes #3392

Processing.py: Setting for turning off warning

---

coalib/results/result_actions/OpenEditorAction.py
tests/results/result_actions/OpenEditorActionTest.py

If files are to be opened with an editor that is
not known to coala a warning is emitted.
Closes https://github.com/coala/coala/issues/3467

OpenEditorAction: Emit warning for unknown editors

---

coalib/results/result_actions/IgnoreResultAction.py
tests/results/result_actions/IgnoreResultActionTest.py

Adds support for using multiline comment delimiters, if the
language does not have singleline delimiters.
If no delimiters are found, emits a warning.
Closes #https://github.com/coala/coala/issues/3441

IgnoreResultAction: Add Multiline comment support

---

tests/parsing/CliParsingTest.py

Using unittest.assertRaises should be avoided. unitest.assertRaisesRegex has an extra parameter to check the exception message, and should be used instead. By checking the exception message, the unit test verifies that the exception is precisely the one which was expected, rather than only of the same type as expected.
Related to https://github.com/coala/coala/issues/3374

CliParsingTest.py: Use unittest.asserRaisesRegex

---

coalib/bearlib/abstractions/Linter.py

@sils @Makman2 
IMO the only way to solve https://github.com/coala/coala/issues/3323 :
* Define `LinterBase` and `LinterMeta` globally in `Linter` module and not dynamically in `_create_linter` function, because dynamically created classes can't be pickled
* Set `klass.options = options` to make them available as `cls.options` and `self.options` in `LinterBase` methods instead of accessing `options` through the method closures as done in the dynamic class creation approach
* Explicitly derive all `@linter` bears from `LinterBase`:
```python
@linter(...)
class SomeLinterBear(LinterBase):
...
```
The above looks ugly, but that can maybe further redesigned with some other way for setting linter options than with `@linter` decorator.
My changes don't break `@linter` bears that don't …

Redesign @linter for Windows compatibility

---

coalib/results/result_actions/OpenEditorAction.py

Add emacs to `KNOWN_EDITORS` in OpenEditorAction.py
Closes https://github.com/coala/coala/issues/3510

OpenEditorAction: Add emacs

---

.misc/appveyor.yml

Dependency management has been moved from the coala repository
to a standalone package, so this Appveyor build definition
no longer needs node or go.

AppveyorCI: Remove unneeded cache directories

---

coalib/bears/Bear.py

Bear.maintainers_emails uses `else cls.MAINTAINERS` instead of `else cls.MAINTAINERS_EMAILS`.
Fixes https://github.com/coala/coala/issues/3566

Bear.py : Updated the maintainers_emails method of Bear class

---

tests/parsing/GlobbingTest.py

This change adds a test for the sequence ([xy]) on fnmatch function.
Fixes: https://github.com/coala/coala/issues/2297

Globbing.py : Add test for the sequence ([xy])

---

.coafile

Catches the redundant space before colon
Fixes https://github.com/coala/coala/issues/3572

coafile: Fix regex in commit section

---

.coafile

Fixes regex which allowed commit messages with two colons to pass and also removed redundancy in regex.
Fixes https://github.com/coala/coala/issues/3587

coafile: Fix shortlog regex

---

coalib/results/Diff.py
tests/results/DiffTest.py
tests/results/result_actions/ShowPatchActionTest.py

The use of argument original_line in change_line function
is now deprecated. Another **issue** to be opened on modifying
the relevant changes ( both in coala/coala and coala/coala-bears )
Closes https://github.com/coala/coala/issues/3024

Diff.py: Deprecate change_line method

---

coalib/output/ConsoleInteraction.py
coalib/parsing/DefaultArgParser.py
coalib/results/Result.py
tests/coalaJSONTest.py
tests/results/ResultTest.py

Result message is split into massage_base
and message_arguments for easier grouping.
Closes https://github.com/coala/coala/issues/3156

Result.py: Add message arguments

---

docs/Developers/Writing_Linter_Bears.rst

Writing_Linter_Bears.rst : Changed 'check' to 'checks' (grammatical error)
In this I have changed the Grammatical Error according to the issue given. 
Fixes: https://github.com/coala/documentation/issues/396
- [# ] I have rebased properly. Please see [our tutorial on rebasing](http://coala.io/git#rebasing).
- [ #] I have gone through the [commit guidelines](http://coala.io/commit) and I've followed them.
- [ #] I have followed the [guidelines for the commit shortlog](http://coala.io/commit#shortlog).
- [ #] I have followed the [guidelines for the commit body](http://coala.io/commit#commit-body).
- [# ] I have included the issue URL with the 'Fixes' keyword if the commit fixes a *real bug* and the 'Closes' keyword if it adds a feature or enhancement. For details, check the [issue reference …

Fixed grammatical error in Linter Bear docs

---

coalib/results/Result.py
tests/results/ResultTest.py

`message` should be formatted only if `message_arguments` are
provided. This allows bears to have `{` or `}` in their message without
the need to escape formatting.
Closes https://github.com/coala/coala/issues/3606

Result.py: Format message only if arguments provided

---

requirements.txt

Require dependency_management 0.3.1,
allowing Maven and Distribution-based requirements.

requirements.txt: Upgrade dependency_management

---

.travis.yml

Places jobs for unsupported Python versions after the
supported versions, so newcomers dont read those first.
---
Note: `UNSUPPORTED=true` is only for visual effect ; e.g. https://travis-ci.org/jayvdb/coala/builds/194116155

.travis.yml: Move unsupported Python versions

---

coalib/bears/Bear.py
requirements.txt
test-requirements.txt
tests/bears/BearTest.py

Rewrote `download_cached_file` in `requests` for better maintainability
and reliability. Also used `requests_mock` for the tests.
Related to https://github.com/coala/coala/issues/3332

Bear.py: Rewrite download_cached_file in requests

---

coalib/parsing/DefaultArgParser.py

This adds default log level - INFO to `-L help`.
Closes issue https://github.com/coala/coala/issues/3618

DefaultArgParser.py: Adds Default log level to `-L help`

---

.travis.yml

Travis OSX queue has had 1300+ jobs backed up for many
hours now.
Fixes https://github.com/coala/coala/issues/3611

.travis.yml: De-activate OSX job

---

.coafile

No `urlopen()` can be found in the code base right now. This pull request will prevent urlopen from being used in the future, as was suggested in #3620.

Blacklist `urlopen`

---

coalib/misc/Shell.py

This fixes issues with running .bat with `shell=True` under Windows.
Fixes https://github.com/coala/coala/issues/3654

Shell: Use shutil.which on Windows

---

.travis.yml
circle.yml
coalib/misc/Shell.py

`@linter` bears can produce wrong results when the external linting tools fail, which can't be checked with the current `coalib.misc.Shell` API. No chance to check the `returncode` of the process created by `run_shell_command`.
This is most probably also the reason for https://github.com/coala/coala-bears/issues/1235
Currently `run_shell_command` only returns the `(stdout, stderr)` tuple from `Popen.communicate`. I wrapped that in a backwards-compatible `tuple`-derived `ShellCommandResult` class which additionally stores the `Popen` instance and has a `.code` property to easily check the return code of the process.

Add ShellCommandResult for accessing return codes

---

coalib/bears/Bear.py
tests/bears/BearTest.py

It modifies get_non_optional_settings method
to also get settings recursively from its
dependencies.
Fixes https://github.com/coala/coala/issues/3149

Bear.py: Modify get_non_optional_settings

---

.misc/deploy.coverage.sh
.travis.yml
circle.yml
test-requirements.txt

Currently codecov-bash is used, which involves an uncached fetch
of a unversioned bash script.
Using codecov-python allows the tool to be cached, and greater
reliability due to versioned releases of the tool.
In addition, codecov-bash does not work on Windows, and our
developer base is better tuned to investigate any python
related problems.
Fixes https://github.com/coala/coala/issues/3718

Use codecov-python

---

coalib/misc/Shell.py

The doctest uses python3 syntax while invoking `python`,
which fails if the executable `python` is the Python 2 runtime.
Fixes https://github.com/coala/coala/issues/3780

ShellCommandResult: Fix doctest

---

docs/Developers/Testing_Bears.rst

The  arguments of Result.from_values() enclosed in []s and missing comma added.
Closes  #3770
them. …

Testing_Bears.rst: Enclose in brackets

---

coalib/bears/Bear.py
tests/bears/BearTest.py

requests.Response.raise_for_status raises an exception
when the HTTP status code is not 200.
Mocked test only verifies exceptions exception is raised.
Testing of mid-stream failures not included.
Fixes https://github.com/coala/coala/issues/3803
Related to https://github.com/coala/coala-bears/issues/1461
them.
likely receive a lot of …

Bear: Raise exception on problematic HTTP status

---

.misc/appveyor.yml

Exclude only branch 'sils/*'.
Closes https://github.com/coala/coala/issues/3516
Related to https://github.com/coala/coala/issues/3664

AppVeyor CI: Allow builds on forks

---

coalib/results/SourceRange.py
coalib/results/TextPosition.py
tests/processes/ProcessingTest.py
tests/results/ResultTest.py
tests/results/SourceRangeTest.py
tests/results/TextPositionTest.py
tests/results/TextRangeTest.py

It overloads __le__ and __ge__ operators
in TextPosition.py to explicitly check
for None values.
Fixes https://github.com/coala/coala/issues/3094

 TextPosition.py: Overload < and > operators

---

coalib/results/Result.py

Result.py: Change order of param in docs
In coalib/results/Result.py:68, change in position of message_arguments param in docs to make its order same as method parameters. 
Fixes https://github.com/coala/coala/issues/3769

Change order of param in docs of Result.py

---

coalib/parsing/LineParser.py
tests/parsing/LineParserTest.py

Adds warning if comment does not have
whitespace before or after #.
Closes https://github.com/coala/coala/issues/2926

LineParser.py: Print warning for comments

---

.misc/appveyor.yml

Use `DownloadFile` instead of curl. The latter seems to
be absent for some reason (even though their docs claim
otherwise).

appveyor.yml: Use builtin download command

---

tests/results/result_actions/OpenEditorActionTest.py

Some users have the `EDITOR` environment variable set before
running the tests.
Fixes https://github.com/coala/coala/issues/3952

OpenEditorActionTest: Unset EDITOR before test

---

docs/Developers/Git_Basics.rst

The origin in the rebasing example is not explicitly mentioned to be the
remote of either https://github.com/coala/coala or
https://github.com/coala/coala-bears. This makes it clear what origin
refers to in this context.
Closes: https://github.com/coala/coala/issues/3947
them.
likely receive a lot of bot comments and build failures …

Git_Basics.rst: Specify rebasing example's origin

---

coalib/processes/Processing.py
tests/processes/ProcessingTest.py

When a bear could not be run because of a missing requirement,
the files were cached anyway so if we install the requirement
and run again, the files are ignored.
This change removes from cache all files only from a section
where a bear could not be run.
Fixes: https://github.com/coala/coala/issues/3693
them.
likely receive a lot of …

Processing: Reset cached files if a bear isn't run

---

coalib/parsing/ConfParser.py
tests/parsing/ConfParserTest.py

Add warning if the user defines a setting in the
coafile that is already defined.
Closes https://github.com/coala/coala/issues/3316
them.
When asked …

ConfParser.py: Add override settings warning

---

coalib/bearlib/__init__.py
tests/bearlib/DeprecateSettingsTest.py

@wraps(func) prevents the loss of doc string
of func, which occurs due to the use of
decorator on func.
Fixes https://github.com/coala/coala/issues/3946
them. …

bearlib: Add @wraps to wrapping_function

---

coalib/bearlib/aspects/__init__.py
coalib/bearlib/aspects/base.py
coalib/bearlib/aspects/meta.py
coalib/bearlib/aspects/taste.py

aspects: Typo error for classnames in pydoc

---

coalib/output/ConsoleInteraction.py

ConsoleInteraction.print_result: Fix docstring
Fixes https://github.com/coala/coala/issues/4018

ConsoleInteraction.py: Typo in docstring 

---

coalib/bearlib/languages/documentation/DocumentationExtraction.py

Remove parameter description for marker
Add parameter description for docstyle_definition.
Closes https://github.com/coala/coala/issues/4030
them. …

DocumentationExtraction.py: Fix docstring parameters

---

tests/bearlib/aspects/TasteTest.py

taste.languages field was added to test_init_defaults function
Fixes https://github.com/coala/coala/issues/3929

TasteTest.py: Add missing field

---

coalib/bearlib/abstractions/Linter.py
coalib/bears/Bear.py
coalib/bears/meta.py
tests/bears/BearTest.py

Implementation for https://github.com/coala/coala-bears/issues/1517
* Following my proposal in https://github.com/coala/coala-bears/pull/1391#discussion_r106233373 - slightly modified from list to dict ;)
* Allowing:
```python
from coalib.bearlib.aspects.Metadata import CommitMessage
```
```python
class SomeAspectsBear(Bear, aspects={
'detect': [CommitMessage.Shortlog.ColonExistence],
'fix': [CommitMessage.Shortlog.TrailingPeriod],
}):
...
```
```python
>>> SomeAspectsBear.aspects
{'detect': [<aspectclass 'Root.Metadata.CommitMessage.Shortlog.ColonExistence'>],
'fix': [<aspectclass 'Root.Metadata.CommitMessage.Shortlog.TrailingPeriod'>]}
```
@sils @Asnelchristian @Techievena @adhikasp @andreiraduta1101

Define bear aspects the magic metaclass way

---

tests/bearlib/abstractions/LinterTest.py

Usage of assertRaises was replaced by assertRaisesRegex which has
an extra parameter for exception message
Related to [coala#3374](https://github.com/coala/coala/issues/3374)

LinterTest.py: Use assertRaisesRegex

---

coalib/bearlib/languages/documentation/DocumentationExtraction.py
coalib/misc/BuildManPage.py

Triple backticks are not RST syntax, resulting in literal backticks
in the output generated by Sphinx.
Fixes https://github.com/coala/coala/issues/4012
them. …

Remove triple backticks from RST

---

coalib/coala.py
tests/coalaFormatTest.py

Give --format flag precedence over --ci when
both --format --ci args are given.
Closes https://github.com/coala/coala/issues/3999
them.
When asked for …

coala.py: Format the output of CI mode when both --format and --ci are given

---

coalib/bearlib/aspects/collections.py
coalib/bears/meta.py
tests/bearlib/aspects/CollectionsTest.py
tests/bears/BearTest.py

Create ``list``-derived ``aspectslist`` class to be used as value type 
for the ``Bear.aspects`` dictionary.
Closes https://github.com/coala/coala/issues/4054
@coala/aspects-developers

aspects: Create aspectlist

---

coalib/bearlib/aspects/__init__.py
coalib/bearlib/aspects/root.py
tests/bearlib/aspects/ModuleTest.py

Closes #4058 with some magic... Just like the Pythonic aspects playground deserves it ;) 
Allowing to directly index the `aspects` module for case-insensitively looking up an aspect by name:
```python
>>> import coalib.bearlib.aspects
>>> coalib.bearlib.aspects['Metadata']
<aspectclass 'Root.Metadata'>
>>> coalib.bearlib.aspects['commitmessage']
<aspectclass 'Root.Metadata.CommitMessage'>
>>> coalib.bearlib.aspects['shortlog.colonExistence']
<aspectclass 'Root.Metadata.CommitMessage.Shortlog.ColonExistence'>
```
When migrating to a separate **coala-aspects** project as proposed in #4038 , the above will further simplify to:
```python
>>> import coala_aspects
>>> coala_aspects['Metadata']
<aspectclass 'Root.Metadata'>
>>> coala_aspects['commitmessage']
<aspectclass …
```

Wrap aspects module for fancy aspect lookup

---

coalib/coala_main.py
coalib/output/Logging.py
tests/coalaCITest.py
tests/coalaJSONTest.py
tests/coalaTest.py
tests/collecting/CollectorsTest.py
tests/test_bears/ErrorTestBear.py

Adds a new logging handler `CounterHandler`, which
counts the number of logged errors.
Adds logic in coala_main to exit with a non-zero
code if any errors were logged during the run.
Closes https://github.com/coala/coala/issues/3087
them.
pass on every single …

coala_main: Non-zero exit code if errors logged

---

docs/Developers/Git_Basics.rst

Make remote names that keep track of the original coala/coala-bears
repository and the reader's fork consistent. Change remote names to
refer to the original repository as "upstream". This makes it clearer 
which repository we're referring throughout the guide.
Closes https://github.com/coala/coala/issues/3948

Git_Basics.rst: Make remote names consistent

---

coalib/bearlib/languages/definitions/Golang.py
coalib/bearlib/languages/documentation/DocumentationComment.py
coalib/bearlib/languages/documentation/golang.coalang
tests/bearlib/languages/documentation/DocumentationCommentTest.py
tests/bearlib/languages/documentation/documentation_extraction_testdata/default.go

This is not entirely conformant to the code style convetions laid out by golang. Comments that have an empty line after the comment should *not* qualify as doc comments. However, we don't have the methods to check for stuff like that.
Closes https://github.com/coala/coala/issues/4068

docstyle: Add docstlye definition for Golang

---

setup.py
tests/__init__.py

Sometimes docker images have locale problem.
I found that `locale.getlocale()` can
return (None, None).
So I fixed that when it return (None, None) then setlocale for it.
* setup.py: Catch (None, None) locale
* tests/__init__.py: Catch (None, None) locale
Fixes https://github.com/coala/coala/issues/3906
them.
likely receive a lot of …

setup.py, tests/__init__.py: Catch (None, None) locale

---

.travis.yml

Add an ``exit`` if UNSUPPORTED==true, and move the other
commands up to the top level of script block.
Follows style of https://github.com/coala/coala-bears/commit/a0f258e

.travis.yml: Escape script after unsupported check

---

docs/Developers/Writing_Linter_Bears.rst

This commit adds the SEE_MORE attribute to the Writing_Linter_Bear
section in the doc with a concrete example.
Closes https://github.com/coala/coala/issues/4138
them. …

docs: Add attribute to Bear development doc

---

coalib/core/Core.py

ProcessPoolExecutor defaults to max cpus.
Fixes https://github.com/coala/coala/issues/4159
Related to https://github.com/coala/coala/issues/3715

Remove unnecessary default max workers

---

coalib/misc/Shell.py

Shell.get_shell_type was last used as part of the Lint class that
was removed without deprecation.
This function is not covered by any tests.
Related to https://github.com/coala/coala/issues/2049
Related to https://github.com/coala/coala/issues/3715

Shell: Remove unused get_shell_type

---

coalib/testing/LocalBearTestHelper.py
tests/test_bears/TestBear.py
tests/testing/LocalBearTestHelperTest.py

Fixes https://github.com/coala/coala/issues/4158 , and implements `check_invalidity` as requested at https://github.com/coala/coala/issues/2197 .

LocalBearTestHelper: Remove pragma: no cover

---

.misc/check_setuptools.py

Add '--format=legacy' to pip list invocation as the
default format will switch to columns in the future.
Fixes https://github.com/coala/coala/issues/4141

.misc/check_setuptools.py: Add format to pip list

---

coalib/core/Core.py

Allows to group sequences using a key. Supports out-of-order-processing
of elements. That's why it's worse to use Python's `itertools.groupby`,
because it does not support out-of-order-processing.

core: Add group function

---

coalib/parsing/DefaultArgParser.py
test-requirements.txt

Adding argcomplete to test-requirements.txt allows simple
compatibility testing with argcomplete.
Closes https://github.com/coala/coala/issues/4163

test-requirements.txt: Add argcomplete

---

tests/output/ConsoleInteractionTest.py

This ensures that the EDITOR is not started when running the
ConsoleInteractionTest.
Fixes #4184
them. …

ConsoleInteractionTest.py: mock subprocess

---

coalib/parsing/Globbing.py

Cosmetically, the return keyword and opening list bracket
should be separated by a space.
Fixes https://github.com/coala/coala/issues/4228
them.
When …

Globbing.py: add appropriate whitespace

---

coalib/results/Diff.py
tests/results/DiffTest.py

Removes the `self.has_changes` property, since its functionality can be
accessed from the bool conversion.
Fixes inconstency of `__bool__` that results from looking at
`self._changes`:
removing one line, then adding the same content again resulted in
`bool(diff) == True`, instead of False.
`__bool__` now uses the mechanism that was employed by `has_changes`, to
fix this bug.
Closes #4178
them.
our bot …

Diff.py: Remove has_changes and fix __bool__

---

docs/Developers/Codestyle.rst

In the Codestyle documentation, lines 64, 65 have been changed from
> This will raise a ``TypeError`` if ``a``, ``b`` or ``c`` are not
> strings and ``c`` is not ``None``.
to the current state.
Closes https://github.com/coala/coala/issues/3478
them.
pass on …

Codestyle.rst: Rephrase sentence

---

coalib/bearlib/languages/__init__.py
coalib/bearlib/languages/definitions/html.py

This allows HTML linters to add ignore comments
Closes https://github.com/coala/coala/issues/4260
Please advise on the usage of string_delimiters, multiline_string_delimiters, and encapsulators.  It is not clear what these are used for or what the proper values are for HTML.
them.
likely receive a lot of bot comments and build …

html.py: Add HTML Language

---

test-requirements.txt
tests/bears/BearTest.py
tests/core/BearTest.py

Replaced time.sleep with freezegun in tests.
Closes: https://github.com/coala/coala/issues/4262

tests: Get rid of all the time.sleeps

---

coalib/testing/LocalBearTestHelper.py

Add `settings` argument to `LocalBearTestHelper.check_validity`
and `LocalBearTestHelper.check_invalidity`.
Closes https://github.com/coala/coala/issues/4247
them. …

LocalBearTestHelper:Add settings to check_validity

---

test-requirements.txt
tests/bears/BearTest.py

And don't use `requests.packages.urllib3`, which doesn't exist anymore in latest `requests` release
**Closes** https://github.com/coala/coala/issues/4293

BearTest: Directly import urllib3

---

coalib/bears/Bear.py
coalib/coala.py
coalib/coala_ci.py
coalib/coala_format.py
coalib/coala_json.py
coalib/coala_main.py
coalib/coala_modes.py
coalib/output/Interactions.py
coalib/parsing/CliParsing.py
coalib/parsing/DefaultArgParser.py
coalib/processes/BearRunning.py
coalib/processes/DebugProcessing.py
coalib/processes/Processing.py
coalib/settings/ConfigurationGathering.py
tests/TestUtilities.py
tests/coalaCITest.py
tests/coalaDebugFlagTest.py
tests/coalaDebugTest.py
tests/coalaJSONTest.py
tests/coalaTest.py
tests/collecting/CollectorsTest.py
tests/test_bears/RaiseTestBear.py

@sils @Makman2 
Instead of the ERROR output from https://github.com/coala/coala/issues/3322 you can now get this:
```
> coala --debug
Executing section Default...
PicklingError("Can't pickle <PycodestyleBear linter class (wrapping 'pycodestyle')>: attribute lookup PycodestyleBear on coalib.bearlib.abstractions.Linter failed",)
> c:\users\zimmermann\miniconda3\envs\coala\lib\multiprocessing\reduction.py(59)dump()
57 def dump(obj, file, protocol=None):
58     '''Replacement for pickle.dump() using ForkingPickler.'''
---> 59     ForkingPickler(file, protocol).dump(obj)
60
61 #
ipdb> Traceback (most recent call last):
File "<string>", line 1, in <module>
File "C:\Users\Zimmermann\Miniconda3\envs\coala\lib\multiprocessing\spawn.py", line 106, in spawn_main
exitcode = _main(fd)
File …
```

Add --debug flag and internal debug arguments

---

coalib/bearlib/languages/Language.py
requirements.txt

Use `packaging.version.Version` instead of `float` for storing versions to support micro version numbers while keeping comparability
Closes https://github.com/coala/coala/issues/4325
Prerequisite for #4109

Store Language.versions as Version instances

---

tests/coalaTest.py
tests/misc/CachingTest.py

Three tests allowed coala to have an internal exception occur,
which was then captured and reported as a success in the test
assertions.
These invocations of coala where seeking user input, which
failed under pytest as tests should not depend on user input.
Fixes https://github.com/coala/coala/issues/4249

tests: Avoid exception in test logic

---

circle.yml

So that proper `sphinx` and `sphinx-argparse` releases are used for building docs in CircleCI process
Closes https://github.com/coala/coala/issues/4332
The missing installation of `docs-requirements` is also not consistent with https://github.com/coala/documentation/blob/master/README.rst#how-to-build and https://github.com/coala/documentation/blob/master/Users/Install.rst#generating-documentation

circle.yml: Install docs-requirements

---

coalib/bearlib/languages/documentation/DocumentationComment.py
tests/bearlib/languages/documentation/DocumentationCommentTest.py

assemble() accounts for `marker[1]==marker[2]`
Fixes https://github.com/coala/coala/issues/2645
them. …

DocumentationComment.py: Add `marker[1]==marker[2]`

---

coalib/bears/Bear.py
coalib/processes/Processing.py
tests/processes/ProcessingTest.py
tests/processes/section_executor_test_files/.coafile
tests/processes/section_executor_test_files/ProcessingGlobalTestRawFileBear.py
tests/processes/section_executor_test_files/ProcessingLocalTestRawFileBear.py

Processing allows raw files if the Bear state that it uses raw
files. Bear that uses binary files can't be mixed with Bear that uses
text files. If this is enabled, bears are incharge of doing the file
handling (opening it, closing it, reading it, etc).
Closes https://github.com/coala/coala/issues/3529

Allow Bears to use raw files

---

coalib/misc/Compatibility.py
setup.cfg

The Python 3.4 CI jobs should require coverage of the code adding backwards compatibility for JSONDecodeError which is missing only in Python 3.4.
Closes https://github.com/coala/coala/issues/4157
(Includes https://github.com/coala/coala/pull/4337)

Compatibility.py: Require coverage on Python 3.4

---

setup.cfg
test-requirements.txt
tests/bearlib/abstractions/LinterTest.py

`LinterTest.test_process_directory` is the last test that is skipped
on Appveyor CI.  It was unnecessarily avoided on Windows as `pwd`
isnt commonly found on Windows, but it can be installed.
Activate pytest-error-for-skips to prevent new platform specific
test methods being introduced.
Related to https://github.com/coala/coala/issues/3715

LinterTest: Run test_process_directory on Windows

---

coalib/bearlib/aspects/Smell.py

This corrects the typo `max_paramters` -> `max_parameters`.
Fixes https://github.com/coala/coala/issues/4380

MethodSmell aspect: Correct typo

---

.rultor.yml

The docker `coala/rultor-python` installs `pip3`.  If it doesnt,
something larger has failed and installing `pip3` isnt helpful.
Closes https://github.com/coala/coala/issues/4393

.rultor.yml: Do not install pip3

---

coalib/bearlib/languages/documentation/DocumentationExtraction.py
tests/bearlib/languages/documentation/DocumentationExtractionTest.py
tests/bearlib/languages/documentation/documentation_extraction_testdata/default.py

Add regex method to ignore fancy strings.
Closes https://github.com/coala/coala/issues/4291
them. …

DocumentationExtraction: Ignore fancy string

---

coalib/bearlib/aspects/collections.py
coalib/bears/meta.py
tests/bearlib/aspects/CollectionsTest.py
tests/bears/BearTest.py

Closes https://github.com/coala/coala/issues/4401

AspectList: Follow class name convention

---

coalib/bearlib/languages/documentation/DocumentationComment.py
coalib/bearlib/languages/documentation/DocumentationExtraction.py
tests/bearlib/languages/documentation/DocumentationCommentTest.py
tests/bearlib/languages/documentation/DocumentationExtractionTest.py

DocumentationComment accept `position` instead
of `range` in `__init__`.
Amend tests to comply with changes.
Closes https://github.com/coala/coala/issues/2646
them. …

DocumentationComment.py: Accept `position`

---

coalib/bearlib/aspects/collections.py
tests/bearlib/aspects/CollectionsTest.py

Overload aspectlist so it could be instanced from a list of string
containing aspects name. The reason of this overloading is to make
it possible to instanced list of desired aspects found in coafile.
```python
>>> aspectlist(['coalaCorrect', 'aspectsYEAH'])
[<aspectclass '...coalaCorrect'>, <aspectclass '...aspectsYEAH'>]
```
Replacement of https://github.com/coala/coala/pull/4379
Closes https://github.com/coala/coala/issues/4382

AspectList: Overload __init__ to accept strings

---

coalib/bearlib/aspects/base.py
coalib/bearlib/aspects/collections.py
tests/bearlib/aspects/CollectionsTest.py
tests/bearlib/aspects/InstanceTest.py
tests/bearlib/aspects/conftest.py

Closes https://github.com/coala/coala/issues/4384
Relates to https://gitlab.com/coala/GSoC-2017/issues/301

AspectList: Add ``get()`` method

---

coalib/bearlib/aspects/__init__.py
tests/bearlib/aspects/ModuleTest.py

Create ``get()`` function as wrapper of ``__getitem__`` that doesn't 
raise error when trying to access non-existant aspect.
Closes https://github.com/coala/coala/issues/4411
Relates to https://gitlab.com/coala/GSoC-2017/issues/314

aspectModule: Add ``get()`` method

---

docs/Developers/Newcomers_Guide.rst

Fixes: #3276 
- Fix Newcomers_Guide, `$ git checkout -b <branchname>` now appears as inline code.

Newcomers_Guide.rst: Fix inline code 

---

coalib/testing/LocalBearTestHelper.py

Improve AssertionError message so if ``msg`` is maybe really empty,
we don't have a superfluous ``\n``.
Closes https://github.com/coala/coala-bears/issues/1870
them. …

execute_bear: Improve ``AssertionError`` message

---

docs/Developers/Newcomers_Guide.rst

Added a sum of the reasons to not work on issues on the master
branch, in the Newcomers_Guide fork section.
Closes https://github.com/coala/coala/issues/4423

Newcomers_Guide.rst: Reason to work on a branch

---

coalib/bears/Bear.py
coalib/testing/LocalBearTestHelper.py
tests/coalaJSONTest.py
tests/coalaTest.py
tests/collecting/CollectorsTest.py
tests/test_bears/TestBearDep.py
tests/testing/LocalBearTestHelperTest.py

Add mechanism to get bear dependencies in
`LocalBearTestHelper.get_results()`.
Closes https://github.com/coala/coala/issues/2860
them.
When asked for …

LocalBearTestHelper: Add get dependency mechanism

---

coalib/bearlib/abstractions/Linter.py

Pass through arguments list to avoid arguments
that are None.
If argument is None, 'None' gets added to the
arguments string for verbosity.
Closes https://github.com/coala/coala/issues/4433

Linter.py: Stop TypeError raised on debug logging

---

coalib/bearlib/aspects/base.py
tests/bearlib/aspects/InstanceTest.py

Modify aspectbase constructor to recursively init their children
subaspects.
Note that accessing child instance MUST be done through `.subaspects`
dict.
```python
>>> commit_msg = coala_aspects['CommitMessage']('py')
>>> commit_msg
<...Metadata.CommitMessage object at 0x...>
>>> commit_msg.subaspects
{'Emptiness': <...CommitMessage.Emptiness object at 0x...>,
'Shortlog': <...CommitMessage.Shortlog object at 0x...>, ...}
>>> commit_msg.subaspects['Emptiness'] # Got instance
<..CommitMessage.Emptiness object at 0x...>
>>> commit_msg.Emptiness # Got aspectclass instead
<aspectclass 'Root.Metadata.CommitMessage.Emptiness'>
```
We can also set children taste through its parent.
```python
>>> commit_msg = coala_aspects['CommitMessage'] ('py', shortlog_tense='past')
>>> …
```

aspectbase: Recursively instance aspect children

---

coalib/bearlib/aspects/collections.py
tests/bearlib/aspects/CollectionsTest.py

Extend AspectList class to have `excludes` attribute that hold list of
aspect that marked as exception of the list. Trying to access aspect
or subaspect of item in `excludes` will always give False/None.
```.python
>>> Metadata not in AspectList([Root], excludes=[Metadata])
True
>>> AspectList([Root], excludes=[Metadata]).get('metadata')
None
```
This feature will be used to excluding ("deactivate") an aspect that
was defined in user's coala configuration.
Closes https://github.com/coala/coala/issues/4438
Note that this PR is dependent (and blocked) by https://github.com/coala/coala/pull/4427 and contain commit from that PR too.

AspectList: Add ``exclude`` attribute

---

coalib/bearlib/languages/documentation/DocstyleDefinition.py

To avoid ConfParser warnings resulting from section overrides with common keys, resulting in `coala-bears` CI **FAIL** on building docs with `sphinx-build -W`, like mentioned in https://github.com/coala/coala-bears/pull/1819#issuecomment-309059574 :
https://circleci.com/gh/coala/coala-bears/6570#tests/containers/1 :
```
Warning, treated as error:
param_start setting has already been defined in section PYTHON. The previous setting will be overridden.
make: *** [html] Error 1
make: Leaving directory `/home/ubuntu/coala-bears/docs'
```
Fixes https://github.com/coala/coala/issues/4470
Prerequisite for https://github.com/coala/coala-bears/pull/1819
@sils @Makman2

DocstyleDefinition .get_available_definitions: Renew parser foreach *.coalang

---

coalib/results/HiddenResult.py

Add `generate_repr` and `generate_ordering` decorators
on HiddenResult class.
Closes https://github.com/coala/coala/issues/4457
them. …

HiddenResult: Add generate_repr, generate_ordering

---

coalib/bearlib/languages/documentation/DocBaseClass.py
tests/bearlib/languages/documentation/DocBaseClassTest.py
tests/bearlib/languages/documentation/DocumentationCommentTest.py

Add DocBaseClass
Merge DocumentationExtraction with DocBaseClass
Closes https://github.com/coala/coala/issues/2659
them. …

DocBaseClass: Add DocBaseClass

---

.travis.yml

The old precise workers, using Node.js v0.10.36, are
being replaced with Trusty workers that use nvm and
have v7 as default.  Install csslint globally in nvm
and cache $HOME/.nvm.
Fixes https://github.com/coala/coala/issues/4513

.travis.yml: Add csslint to PATH

---

.travis.yml
test-requirements.txt
tests/bears/BearTest.py

When requests was undergoing frequent breakages, a `ProtocolError`
was being raise unexpectedly when provoking a broken read scenario.
This exception was added as an alternative as it was at least
a predictable error occurring, allowing the remainder of the
test method to verify the resulting behaviour of the method,
and there were far bigger problems occurring at the time
due to `requests` being broken several time a day.
Depending on urllib3 for this ProtocolError is problematic,
as requests has its own version requirements for urllib3,
and those must take precedence over coala testing needs.
A conflict between requests and urllib3 has broken the
docker image.
It seems ProtocolError is not being thrown any longer,
and removing it bypasses the urllib3 conflict.
Should a ProtocolError …

BearTest: Remove urllib3 ProtocolError

---

coalib/bearlib/aspects/__init__.py
coalib/bearlib/languages/Language.py
coalib/settings/ConfigurationGathering.py
coalib/settings/Section.py
tests/bearlib/languages/LanguageTest.py
tests/settings/ConfigurationGatheringTest.py
tests/settings/SectionTest.py

Enable bear to access aspects that defined in configuration files.
Given a coafile:
```
[all]
files = **.py
bears = coalaBear
aspects = coalaCorrect, shortlog.colonexistence
language = Python 3.6
shortlog_colon = false
```
Then, bears can access those aspects with defining a keyword argument
``aspects`` in ``run()`` method.
```python
class SomeBear(LocalBear):
def run(self, filename, file, aspects:aspectlist=None):
print(aspects)
print(aspects[1])
print(aspects[1].shortlog_colon)
```
Depends on https://github.com/coala/coala/pull/4389
Relates to https://gitlab.com/coala/GSoC-2017/issues/142
Closes https://github.com/coala/coala/issues/4324

Processing: Preprocess and pass aspects to bear

---

coalib/collecting/Collectors.py
coalib/settings/ConfigurationGathering.py
tests/collecting/CollectorsTest.py
tests/settings/ConfigurationGatheringTest.py

These functions were removed in 498c731, breaking
coala-quickstart.
CollectorsTest is also restored.
New test added to ConfigurationGatheringTest, as the previous
covered code path no longer uses get_filtered_bears.
Fixes https://github.com/coala/coala/issues/4519

Restore functions removed in bear filter rewrite

---

tests/TestUtilities.py
tests/coalaJSONTest.py
tests/coalaTest.py
tests/parsing/FilterTest.py
tests/settings/ConfigurationGatheringTest.py

TEST_BEARS_COUNT is used in many different location and tedious
to change.
Closes https://github.com/coala/coala/issues/4545

TestUtillites: Add TEST_BEARS_COUNT

---

coalib/bearlib/aspects/collections.py
coalib/bears/Bear.py
coalib/bears/meta.py
tests/bearlib/aspects/CollectionsTest.py
tests/bears/BearTest.py

Replacement of https://github.com/coala/coala/pull/4111
Closes https://github.com/coala/coala/issues/4094

AspectList: Connect with holder bear

---

coalib/bearlib/languages/documentation/DocBaseClass.py
tests/bearlib/languages/documentation/DocBaseClassTest.py
tests/bearlib/languages/documentation/DocumentationCommentTest.py
tests/bearlib/languages/documentation/documentation_extraction_testdata/default.c
tests/bearlib/languages/documentation/documentation_extraction_testdata/default.java

Bug fix for java docstyles having no trailing
spaces before marker[1] and marker[2]
Fixes https://github.com/coala/coala/issues/4029
them.
When asked …

DocBaseClass: Fix java docstyle bug

---

coalib/bearlib/languages/documentation/DocumentationComment.py
tests/bearlib/languages/documentation/DocumentationCommentTest.py
tests/bearlib/languages/documentation/documentation_extraction_testdata/default.py

`assemble()` now adds a blank line before or after
docstring based on top_padding and bottom_padding.
Closes https://github.com/coala/coala/issues/4200
them. …

DocumentationComment.py: Add blankline padding

---

coalib/bearlib/aspects/base.py
coalib/bearlib/aspects/collections.py
coalib/bears/Bear.py
coalib/collecting/Collectors.py
coalib/settings/ConfigurationGathering.py
coalib/settings/SectionFilling.py
tests/TestUtilities.py
tests/bearlib/aspects/CollectionsTest.py
tests/bearlib/aspects/InstanceTest.py
tests/coalaJSONTest.py
tests/collecting/CollectorsTest.py
tests/test_bears/AspectTestBear.py

Closes https://github.com/coala/coala/issues/4531

Implement basic bear collection by aspect

---

coalib/settings/ConfigurationGathering.py

ConfigurationGathering.py: Change description
Change load_configuration function description to replace duplicate parameter name with fourth parameter name
Closes: https://github.com/coala/coala/issues/4533

Change load_configuration function description

---

coalib/testing/LocalBearTestHelper.py

Add `**process_output_kwargs` argument to `new_process_output(...)`
and `old_process_output(...)` because the keyword arguments were
not taken care of in bbb99f95cd2c5530bae765b2b011e76d85d639b4.
Fixes https://github.com/coala/coala/issues/4576
Related to https://github.com/coala/docker-coala-base/issues/219
them.
likely receive a …

LocalBearTestHelper: Add **process_output_kwargs

---

coalib/bearlib/abstractions/Linter.py
coalib/bearlib/abstractions/LinterClass.py
coalib/testing/LocalBearTestHelper.py

Introduce a virtual base class for linters and use it to
improve the check inside `LocalBearTestHelper`.
i.e. Instead of checking `hasattr(cls, 'process_output')`, an
`isinstance(cls, LinterClass)` is safer and easier to understand.
Closes https://github.com/coala/coala/issues/4594
them.
likely receive a lot of bot comments and …

coalib/abstractions: Add LinterClass.py

---

coalib/bearlib/languages/documentation/DocumentationExtraction.py
tests/bearlib/languages/documentation/DocBaseClassTest.py
tests/bearlib/languages/documentation/documentation_extraction_testdata/default.py

Ignore whole triple quote string literal DocComment.
Fixes https://github.com/coala/coala/issues/4631
them. …

Ignore triple quote string literals.

---

coalib/coala_main.py
coalib/output/ConsoleInteraction.py
coalib/processes/Processing.py
coalib/results/result_actions/DoNothingAction.py
tests/output/ConsoleInteractionTest.py
tests/results/result_actions/DoNothinActionTest.py

Closes https://github.com/coala/coala/issues/4628

gsoc: Add Do (N)othing Action

---

coalib/settings/ConfigurationGathering.py
tests/coalaCITest.py

Adds option to silence warnings by `load_configuration` method when
`get_filtered_bears` method is called.
Closes https://github.com/coala/coala/issues/4621

ConfigurationGathering: Add option to silence warnings

---

coalib/bearlib/languages/documentation/DocstyleDefinition.py
coalib/bearlib/languages/documentation/DocumentationComment.py
coalib/bearlib/languages/documentation/DocumentationExtraction.py
coalib/bearlib/languages/documentation/default.coalang
coalib/bearlib/languages/documentation/doxygen.coalang
tests/bearlib/languages/documentation/DocBaseClassTest.py
tests/bearlib/languages/documentation/DocstyleDefinitionTest.py
tests/bearlib/languages/documentation/DocumentationCommentTest.py
tests/bearlib/languages/documentation/documentation_extraction_testdata/default.py

Add `padding` in DocstyleDefinition which
are now acquired from `.coalang`. Add
`top_padding` and `bottom_padding` which
automatically instantiate from
`instantiate_padding` in DocBaseClass. Add
supporting test cases.
Related to https://github.com/coala/coala/issues/4200
them.
likely receive a lot of bot comments and build failures …

DocumentationAPI: Add `padding`

---

coalib/bearlib/__init__.py
coalib/bearlib/languages/Language.py
coalib/results/Diff.py

doctest option +ELLIPSIS is enabled by default in pytest
Fixes https://github.com/coala/coala/issues/3065

doctest: Remove unnecessary +ELLIPSIS

---

coalib/collecting/Collectors.py
tests/collecting/CollectorsTest.py

Show warning if some of requested aspects could not be fulfilled
by coala.
Closes https://github.com/coala/coala/issues/4656

Collectors: Warn unfulfilled aspects

---

coalib/bears/Bear.py
tests/bears/BearTest.py
tests/processes/BearRunningTest.py

GitCommitBear fails but the exit status is not set. This PR solves this problem by promoting the warning to error
Fixes: #4567
them. …

  Bear.py: Promotes log entry from warning to error 

---

coalib/bearlib/aspects/__init__.py
coalib/bearlib/aspects/decorators.py
coalib/bearlib/aspects/meta.py
tests/bearlib/aspects/DecoratorsTest.py

```python
@map_setting_to_aspect(
remove_all_unused_imports=(get_aspect('UnusedImport')
.remove_non_standard_import),
remove_unused_variables=get_aspect('UnusedLocalVariable'))
def run(self, filename, file,
remove_all_unused_imports: bool=True,
remove_unused_variables: bool=True):
pass
```
The `run` argument will be overrided by aspect's setting 
(only if it present). This make bear's aspectization much more easy.
Closes https://github.com/coala/coala/issues/4661

Aspect: Create ``map_setting_to_aspect`` decorator

---

coalib/output/ConsoleInteraction.py
coalib/processes/Processing.py
coalib/results/result_actions/GeneratePatchesAction.py
tests/output/ConsoleInteractionTest.py
tests/results/result_actions/GeneratePatchesActionTest.py

Add action that generates patches depending on the file
Closes https://github.com/coala/coala/issues/4599

gsoc: Add Action: Generate Patches

---

coalib/bears/Bear.py
coalib/settings/ConfigurationGathering.py
coalib/settings/Section.py
coalib/settings/Setting.py
docs/Developers/Writing_Native_Bears.rst
tests/bears/BearTest.py
tests/coalaTest.py
tests/settings/ConfigurationGatheringTest.py
tests/settings/SectionTest.py
tests/settings/SettingTest.py
tests/test_bears/AspectTestBear.py

Closes https://github.com/coala/coala/issues/4580 https://github.com/coala/coala/issues/4463

Aspects: Add more robust setting checks

---

coalib/results/HiddenResult.py

HiddenResult.__init()__ now has all the parameters of Result.__init()__
This is meant to make HiddenResult objects work like Result objects.
Closes https://github.com/coala/coala/issues/4454

HiddenResult: Add all parameters of Result.__init()__

---

docs/Developers/Writing_Native_Bears.rst

Relates to https://github.com/coala/coala/issues/4665
Contain commit from https://github.com/coala/coala/pull/4662

Add docs on writing aspect bear

---

docs/_templates/searchbox.html

This template overrides the default searchbox.html template shipped with
sphinx hence, allowing usage of custom search like DocSearch.
Closes https://github.com/coala/coala/issues/4695
them. …

searchbox.html: Use docsearch instead of default

---

coalib/results/Result.py

Enclose code object in double backticks.
SourceRange under param was enclosed in
backticks.
Closes https://github.com/coala/coala/issues/4671
them. …

Result: Enclose SourceRange in double backticks

---

README.rst

Changes the Get Involved URL to the correct one.
Closes https://github.com/coala/coala/issues/4710

README.rst: Update Get Involved URL

---

coalib/testing/LocalBearTestHelper.py

Return call is redundant and hence removed.
This could also cause confusing to python 2 users 
where this is invalid syntax.
Closes https://github.com/coala/coala/issues/4735
them.

LocalBearTestHelper.py: Removed redundant return.

---

coalib/output/Interactions.py

Function declaration declares settings_names_dict as an input parameter, but docstring references this parameter as settings. This commit changes the docstring to correctly reference settings_names_dict.
Closes https://github.com/coala/coala/issues/4739
them. …

Interactions.py: Modify docstring to correct param name

---

coalib/results/HiddenResult.py

Improves the docstring so that it better describes the reason for the
existence of the `contents` parameter in the HiddenResult class.
Closes https://github.com/coala/coala/issues/4672
them. …

HiddenResult.py: Improve help for `contents` parameter

---

tests/bearlib/aspects/DecoratorsTest.py

BEAR_KIND was not imported in DecoratorsTest.py
and hence was showing undefined name error during
execution of kind function.
Fixes https://github.com/coala/coala/issues/4702
them.
After you submit your pull request, **DO NOT click …

DecoratorsTest.py: Import BEAR_KIND

---

coalib/bearlib/languages/documentation/DocstyleDefinition.py

DocstyleDefinition.py: Align init docstring
I have aligned the init docstring according to the codestyle given at http://api.coala.io/en/latest/Developers/Codestyle.html.
Closes https://github.com/coala/coala/issues/4645
them.

DocstyleDefinition.py: Align init docstring

---

tests/coalaJSONTest.py

Test if using `--output` overwrites files instead
of appending
Closes https://github.com/coala/coala/issues/4810
them. …

Add test: Test output file overwriting

---

coalib/core/Core.py
tests/core/CoreTest.py

The event-loop can't know that is has to close the executor, as it's
always passed explicitly to `run_in_executor()`.

core: Explicitly shutdown executor

---

coalib/core/Core.py
tests/core/CoreTest.py

... when scheduling all dependency bears. Bears that offload no tasks
may cause the event-loop to close too early while other bears had no
chance to submit their tasks.
Fixes https://github.com/coala/coala/issues/4505

core: Do not close event loop too early

---

tests/parsing/FilterTest.py

Fixes https://github.com/coala/coala/issues/4845
Changes `assertRaisesRegex` to `assertIn(..., stdout)` in:
https://github.com/coala/coala/blob/539a4e5c626e7ee839793ce5f29c62a96284359b/tests/parsing/FilterTest.py#L101-L110

Fix FilterTest.test_filter_by_unknown

---

tests/output/ConsoleInteractionTest.py

Rename second occurrence of `test_acquire_actions_and_apply` to `test_acquire_actions_and_apply_single` (it's testing the `apply_single` parameter)
Fixes https://github.com/coala/coala/issues/4859 and enables proper testing for https://github.com/coala/coala/pull/4179

ConsoleInteractionTest: Fix method name used twice

---

coalib/output/Interactions.py
tests/output/InteractionsTest.py

The documentation for section parameter was not provided
in the docstring. This commit adds the documentation.
Closes https://github.com/coala/coala/issues/4740
them. …

Interactions.py : Add deprecation message for section parameter

---

coalib/output/ConsoleInteraction.py
coalib/results/result_actions/IgnoreResultAction.py
coalib/results/result_actions/OpenEditorAction.py
coalib/results/result_actions/PrintAspectAction.py
coalib/results/result_actions/PrintDebugMessageAction.py
coalib/results/result_actions/PrintMoreInfoAction.py
coalib/results/result_actions/ResultAction.py
coalib/results/result_actions/ShowPatchAction.py
tests/output/ConsoleInteractionTest.py
tests/results/result_actions/IgnoreResultActionTest.py

This avoids asking the users if they want to add an ignore comment,
AFTER they already applied one.
Includes a new parameter for Action.is_applicable, which can be
checked for earlier actions.
Change in behaviour for IgnoreResultAction:
If this action was already used before, Action.is_applicable will
always return false, even on other failure cases.
Closes https://github.com/coala/coala/issues/3375
them.
individually.* It is not sufficient to have "fixup commits" on your …

Ignore Action: Remove action after comment added

---

coalib/output/Interactions.py
coalib/settings/SectionFilling.py
tests/output/InteractionsTest.py
tests/settings/SectionFillingTest.py

The section parameter in fail_acquire_setting
is deprecated.This commit adapts all calls to
the function without the section parameter.
Closes https://github.com/coala/coala/issues/4866
them. …

Interactions.fail_acquire_settings: Remove section parameter

---

coalib/output/ConsoleInteraction.py
tests/output/ConsoleInteractionTest.py

Disables "No bears to show." message when
--json flag is used.
Fixes https://github.com/coala/coala/issues/4668
them. …

ConsoleInteraction: Remove no bears message

---

docs/Developers/Newcomers_Guide.rst

Tells the newcomer to merge only one difficulty/newcomer issue.
Fixes https://github.com/coala/coala/issues/4771
them.

Newcomers_Guide.rst: Allow only one newcomer issue

---

coalib/parsing/DefaultArgParser.py
tests/coalaCITest.py
tests/coalaDebugFlagTest.py
tests/coalaDebugTest.py
tests/coalaFormatTest.py
tests/coalaJSONTest.py
tests/coalaTest.py
tests/misc/CachingTest.py

Use a new `PathArg` type for all cmdline arguments that represent file system paths. It replaces OS-native directory separators with Unix-style forward slashes. Windows-style backslashes would otherwise be interpreted as escaping syntax and therefore removed when turning cmdline arguments into coala settings, what makes interactively working with coala in a Windows cmdline a pain ;)
Closes https://github.com/coala/coala/issues/4356
cc @Makman2 @jayvdb

DefaultArgParser: Uni(xi)fy directory separators

---

coalib/bearlib/aspects/Formatting.py

Fix for little mistake in https://github.com/coala/coala/pull/4989
Relates to https://github.com/coala/coala/issues/4982

Formatting.py: Change indentation taste type to str

---

coalib/settings/ConfigurationGathering.py
tests/coalaDeleteOrigTest.py
tests/settings/SettingTest.py

Instances of `re.escape` not changed:
`Globbing.py`: 3 Instances
`DocumentationExtraction.py`: 1 Instance
Reason: Not sure whether to change them or not 
OR
using `re.escape()` in a way that it is intended to use, not operating on file paths, operating on file globs and the paths will ultimately be changed due to the other changes made.
Closes https://github.com/coala/coala/issues/4890

Change instances of re.escape() with PathArg()

---

coalib/bearlib/abstractions/Linter.py

The ``filename`` param didn't exist in given scope.
Regarding global-bear feature conception
the ``file_dict`` field is expected instead.
It can be accessed via ``self``.
Closes https://github.com/coala/coala/issues/4939
them. …

Linter.py: Fix GlobalBear example in docstring

---

docs-requirements.txt

Change the version of sphinx to less than 1.6.6
to fix the CI break.
Fixes https://github.com/coala/coala/issues/5058

docs-requirements: Fix CI break

---

docs/Developers/Writing_Good_Commits.rst

Clear disambiguation between closes and fixes
keywords used for issue reference.
Closes https://github.com/coala/coala/issues/4976
them.
When asked …

Writing_Good_Commits.rst: Clear disambiguation

---

requirements.txt
tests/bearlib/abstractions/LinterTest.py
tests/results/DiffTest.py

A recent test breakage forced the requirements to limit the version
of the "unidiff" package below 0.5.5. It was identified on an upstream
issue that coala's tests tested against invalid unified-diffs (context
lines were wrong), but this wasn't accurately catched by "unidiff", it
just processed the actual diff content.
The current tests are now modified to have valid context lines.

Support unidiff 0.5.5

---

.coafile

Changed the wrong command in .coafile from 
`default_action: *: ShowPatchAction` --> 
`default_actions = *: ShowPatchAction`
which is the correct command.
Closes https://github.com/coala/coala/issues/5043
them. …

.coafile : Fix Wrong Command

---

docs/Developers/Newcomers_Guide.rst

This corrects a grammatical error, changes it from "to to" --> "to".
Closes #5087

Newcomers_Guide.rst: correct grammatical mistake

---

docs/Developers/Testing_Bears.rst

Result : The from_values() function of Result class accepts a file as a parameter.
Fixes #5003

Testing_Bears.rst: add `filename` parameter in `Result.from_values()`

---

coalib/testing/LocalBearTestHelper.py
tests/testing/LocalBearTestHelperTest.py

The command line is not displayed in case of
test-fail in execute_bears function when a
linter is used. This commit fixes that issue.
Closes https://github.com/coala/coala/issues/4901
them. …

LocalBearTestHelperTest.py: Display command line

---

coalib/settings/ConfigurationGathering.py
coalib/settings/SectionFilling.py
tests/coalaCITest.py
tests/settings/SectionFillingTest.py

If a section is disabled using `enabled=Flase` or something like
this `TODOS.enabled=False` in `.coafile` where TODOS is section name,
then that section will be disabled and won't ask for any additional
parameters.
Fixes https://github.com/coala/coala/issues/4849

Ignore additional parameters if a section disabled

---

coalib/testing/LocalBearTestHelper.py
tests/testing/LocalBearTestHelperTest.py

Add ``assertObjectsEqual(..)`` method that compares individual
fields of the Result object and yields better, easy to understand
messages in case of an attribute mismatch.
Closes https://github.com/coala/coala/issues/4302
them. …

LocalBearTestHelper: Add ``assertObjectsEqual``

---

docs/Developers/Linter_Bears_Advanced.rst

Mentions how returning `None` inside `generate_config` works
Closes https://github.com/coala/coala/issues/4119
them. …

Linter_Bears_Advanced.rst: Explains return `None`

---

setup.py

The man page was installed in unaccessible location `site-packages`
Now it will get installed in an accessible location.
Closes https://github.com/coala/coala/issues/4894
them. …

setup.py: Fix the location of Man Page

---

coalib/testing/LocalBearTestHelper.py

This adds ``check_order`` parameter in docstring
of ``check_results`` which was previously missing.
Closes https://github.com/coala/coala/issues/5126
them. …

LocalBearTestHelper: Add ``check_order`` in doc

---

.gitignore

Added tagfile names that need to be ignored by git in case the
developer is using VIM editor and needs to generate tags using ctags,
etags or gtags.
Closes https://github.com/coala/coala/issues/5162
them. …

.gitignore: Add names to ignore tag files in vim

---

docs/Developers/Linter_Bears_Advanced.rst

This changes value=2 -> value2.
Closes https://github.com/coala/coala/issues/5165

Linter_Bears_Advanced.rst: Fix typo

---

coalib/core/Bear.py
coalib/core/Core.py
tests/core/BearTest.py
tests/core/CoreTest.py

Bears can now define dependencies at instantiation for `BEAR_DEPS`,
depending on different section settings.
The Bear class makes now a copy of the dependencies specified in
`BEAR_DEPS`, so users can directly modify the set inside `__init__`
(which prevents modifying the class wide dependencies that are always
needed).
For that, the core test bears had to be adapted, because before
picklibility of those test bears was not necessary to run the
core.
Closes https://github.com/coala/coala/issues/4560

core: Make bear dependencies instance bound

---

docs/Developers/Writing_Linter_Bears.rst

In line: LANGUAGES = {"Python", "Python 2", "Python 3"} with change " --> '.
Fixes https://github.com/coala/coala/issues/3832

Writing_Linter_Bears.rst: Improve quotes style

---

coalib/bearlib/abstractions/Linter.py

This corrects the docstring of ``process_diff`` and changes it from
"An instance of ``coalib.results.Diff``" to "A ``coalib.results.Diff``".
Closes https://github.com/coala/coala/issues/5251
them. …

Linter.py: Correct docstring

---

.travis.yml

The jobs for unsupported platforms 2.7 & 3.3 do not need to run
so frequently, and any breakages are usually related to upstream
dropping support for 2.7 or 3.3, rather than a local problem.
The master builds will break, and usually we'll need to pin
something to get around the problem.  Ultimately, failure to
verify that these old versions fail in a predictable manner
should not prevent us adding new features or dependencies.
Closes https://github.com/coala/coala/issues/4323
up your stuff for …

.travis.yml: Skip unsupported except on master

---

coalib/core/Core.py

The cache look-up only looks for the parameters
of ``execute_task`` and not the section to get
the cached result of a bear.
Fixes https://github.com/coala/coala/issues/5270
them.
After you submit your pull request, **DO NOT click …

Core.py: Removes section from docstring

---

coalib/parsing/Globbing.py
tests/parsing/GlobbingTest.py

Removes the `if` statement from `fnmatch()` that
used to return `True` if no globs were given
Fixes: https://github.com/coala/coala/issues/2302
them. …

Globbing.py: Return false if globs are absent

---

tests/misc/ExceptionsTest.py
tests/output/ConsoleInteractionTest.py

This removes the clang related code from ExceptionsTest.py and
ConsoleInteractionTest.py. clanglib-py3 is changed to version_1 and
version_2 and ClangCloneDetectionBear is changed to CloneDetectionBear.
Closes https://github.com/coala/coala/issues/5250
them. …

Related clang stuff removed

---

setup.py

This fixes the invalid classifier `Python :: 3.4.4` to `Python :: 3.4` which is valid according to https://pypi.python.org/pypi?%3Aaction=list_classifiers
Closes https://github.com/coala/coala/issues/5318
them. …

setup.py: Revert use of invalid classifier

---

docs/Developers/Writing_Good_Commits.rst

Change: add No WIP prefix
Fixes https://github.com/coala/coala/issues/5287
them. …

Writing_Good_Commits.rst: Add No WIP prefix

---

requirements.txt

colorlog was pinned to 2.x. colorlog 3.0 has been released for a
few months, and is now starting to cause conflicts in versions,
which causes coala to fail.
The changes in colorlog 3.0 and 3.1 do not adversely effect coala.
Closes https://github.com/coala/coala/issues/4992

requirements.txt: Upgrade to colorlog 3.1

---

coalib/results/result_actions/OpenEditorAction.py

Couldn't find any documentation regarding command line arguments.
Tried several commands to enter into a specific line/column but none
worked. 'notepadqq {filename}' works.
Closes https://github.com/coala/coala/issues/5244
them. …

OpenEditorAction.py: Add notepadqq to known editors

---

.travis.yml

Adds python 3.4.3 unsupported check to Travis CI
Closes https://github.com/coala/coala/issues/5319
them. …

.travis.yml : Add python 3.4.3 check

---

.coafile

New checks E252, W504 and W605 of pycodestyle 2.4.0
are breaking the builds. This adds those checks to
`pycodestyle_ignore` list.
Closes https://github.com/coala/coala/issues/5372
them. …

.coafile: Ignore new pycodestyle's checks

---

tests/bearlib/languages/documentation/DocstyleDefinitionTest.py
tests/results/TextPositionTest.py
tests/results/TextRangeTest.py

Changing the typo "instantation" --> "instantiation"
in the following files:
tests/results/TextPositionTest.py
tests/results/TextRangeTest.py
tests/bearlib/languages/documentation/DocstyleDefinitionTest.py
Fixes https://github.com/coala/coala/issues/5373
them. …

tests/: Fix typos "instantation"

---

.coafile
.moban.dt/core-setup.py.jj2
.moban.yaml
.travis.yml
setup.py
test-requirements.txt

coala-mobans provides a set of metadata common to
all repositories, with local overrides.
requirements.txt is generated using the default
moban provided requirements.txt.jj2.

Build setup.py and requirements.txt using moban

---

tests/output/ConsoleInteractionTest.py

``coala_utils`` decorator ``check_logs`` relies on
``textfixtures``, a dependency it shoul not have.
Inlining the decorator will allow it to be removed.
Related to https://github.com/coala/coala/issues/5335
them. …

ConsoleInteractionTest: Remove check_logs usage

---

.moban.yaml
coalib/bearlib/abstractions/Linter.py
requirements.txt
tests/bearlib/abstractions/LinterTest.py

New option `strip_ansi` implemented that strips ansi characters that
lead to colored output of linters.
Closes https://github.com/coala/coala/issues/5281
them. …

Linter.py: Support colorised output from linters

---

.coafile
tests/testing/LocalBearTestHelperTest.py

This E241 is a check for multiple spaces after a comma. It is
an important code style check.
them. …

E241 check is being enforced

---

docs/Developers/Git_Basics.rst

http://ohshitgit.com/ contains helpful git snippets when something has
gone wrong.
This commit adds the link to the website as well as some snippets and
paraphrased instructions into Git Basics.
Closes https://github.com/coala/coala/issues/4985
them.

Git_Basics.rst: Incorporate http://ohshitgit.com/

---

tests/parsing/FilterHelperTest.py

This adds an additional `FilterHelperTest` class and
tests `InvalidFilterException` by raising the exception
using `FilterHelper`.
Closes https://github.com/coala/coala/issues/4864
them.
instead.
Please consider helping us by reviewing other peoples pull requests as well:
- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are …

FilterHelperTest.py: Add `FilterHelperTest` class

---

coalib/output/ConsoleInteraction.py

Now, `ask_for_action_and_apply()` tries to apply the DoNothingAction,
if it is chosen by the user, instead of simply returning.
Closes https://github.com/coala/coala/issues/5260
them. …

ConsoleInteraction.py: Apply the DoNothingAction

---

coalib/bearlib/languages/Language.py
tests/bearlib/languages/LanguageTest.py

The __contains__ method in the Language class only checks
if self.versions is a superset of item.versions. This change
adds a subset check so if self.versions is a subset
of item.versions, __contains__ will return True.
Closes https://github.com/coala/coala/issues/4690

Language.py: Fix __contains__ method

---

coalib/collecting/Collectors.py
tests/collecting/CollectorsTest.py
tests/collecting/collectors_test_dir/bears/nameBear.py

Allow bear names to be used without the "Bear"
suffix at the end.
Closes https://github.com/coala/coala/issues/2290

Collectors.py: Use bear names without suffix

---

coalib/bearlib/abstractions/Linter.py
docs/Developers/Writing_Linter_Bears.rst
tests/bearlib/abstractions/LinterTest.py

Control line-index and column-index conversion
to handle zero-based and one-based conventions.
Closes https://github.com/coala/coala/issues/5346
them. …

linter: Add new parameters to normalize numbers

---

coalib/collecting/Collectors.py
coalib/misc/IterUtilities.py
coalib/parsing/Globbing.py
tests/collecting/CollectorsTest.py

This change allows users to specify directory globs in the form:
.../test/
.../test
.../test/**
.../test/*
These patterns now ignore the content of the whole directory and all
subdirectories.
Closes https://github.com/coala/coala/issues/4673
them.
pass on …

Collectors.py: Add support to ignore directories

---

coalib/misc/Constants.py
tests/settings/ConfigurationGatheringTest.py

This changes 'deafult' --> 'default' in Constants.py and GatheringTest.py.
Fixes https://github.com/coala/coala/issues/5366
them. …

Constants.py, GatheringTest.py: Fix typo

---

tests/collecting/CollectorsTest.py

This commit deletes the unneeded ``ignored_file_paths`` and ``limit_file_paths`` parameters from the ``test_file_invalid`` method.
Fixes https://github.com/coala/coala/issues/5340
them. …

CollectorsTest.py: Remove unnecessary parameters

---

coalib/misc/CachingUtilities.py

Removes unnecessary imports on CachingUtilities.pickle_load docstring.
Closes https://github.com/coala/coala/issues/5441
them. …

CachingUtilities.py: Removes unnecessary imports

---

tests/settings/ConfigurationGatheringTest.py

…onstants.user_coafile state save
Constants.user_coafile is now saved and restored from setUp() and tearDown()
Fixes #5445
- [ *] I read the [commit guidelines](http://coala.io/commit) and I've followed
them.
- [ *] I ran coala over my code locally. (*All commits have to pass
likely receive a lot of bot comments and build failures …

ConfigurationGatheringTest.py: Save user_coafile before modify

---

.misc/appveyor.yml

pip now complains about being downgraded when being
executed via the `pip` command on Windows.
Closes https://github.com/coala/coala/issues/5466

appveyor.yml: Run pip install as Python module

---

coalib/misc/Shell.py

... instead of python which is not availabe on Linux systems without
having Python 2 installed (Python 3 is called python3 on command
line). Now Python 2 is not necessary for the modified doctest
to execute.

Shell: Use sys.executable in doctest

---

coalib/bearlib/languages/definitions/TypeScript.py

TypeScript.py: Update TypeScript keywords
This fix ensures that coala discovers all TypeScript
keywords.
Closes https://github.com/coala/coala/issues/5490
them. …

Update TypeScript keywords

---

coalib/testing/BaseTestHelper.py
tests/testing/BaseTestHelperTest.py

`observed_result` is result generated from a bear and `expected_result` is tester's expected result from the bears.
Related to https://gitlab.com/coala/GSoC/GSoC-2018/issues/307
Closes https://github.com/coala/coala/issues/3676

BaseTestHelper.py: Add `BaseTestHelper` class

---

coalib/bearlib/languages/Language.py

This changes aliases of `TrumpScript` in the
doctests so that `TypeScript` and `TrumpScript`
have different aliases and so do not collide.
Fixes https://github.com/coala/coala/issues/5541
them. …

Language: Change `TrumpScript` aliases

---

coalib/bearlib/aspects/__init__.py
coalib/bearlib/aspects/decorators.py
tests/bearlib/aspects/DecoratorsTest.py

Create decorator `map_ambiguous_setting_to_aspect` for
mapping bear settings to aspects in cases where data_types
and values are different in bear settings and aspects.
A typical example is `use_spaces` (bear setting) and
`indent_type` (taste of `Indentation` aspect).
This is part of `Convert Bear To Aspects` GSoC 2018 project.
them.
our bot will still report the issues for the previous commit.) You …

aspects: Create `map_ambiguous_setting_to_aspect`

---

coalib/bearlib/abstractions/Linter.py
coalib/results/Result.py

Linter.py: replace range variable with different name
Result.py: replace range variable with different name
This fixes the issue of using range as a variable name
Fixes https://github.com/coala/coala/issues/3398
them.
After you …

Replace range variable with different name

---

setup.cfg
test-requirements.txt

pytest 3.3 fails to replicate the prior behaviour
with regards to doctest which use logging.
Related to https://github.com/coala/coala/issues/5543

Use Pytest 3.6

---

.ci/check_man.sh
.circleci/config.yml

This removes unneeded addition to $MANPATH for CircleCI.
Also, wheel is built and installed with root privileges, so man
page gets placed under the proper path.
Closes https://github.com/coala/coala/issues/5321
them.
After you …

CI: Check man page without altering $MANPATH

---

coalib/bearlib/languages/Language.py
coalib/bearlib/languages/LanguageDefinition.py
coalib/bearlib/languages/definitions/C.py
coalib/bearlib/languages/definitions/CPP.py
coalib/bearlib/languages/definitions/CSharp.py
coalib/bearlib/languages/definitions/Fortran.py
coalib/bearlib/languages/definitions/Golang.py
coalib/bearlib/languages/definitions/Java.py
coalib/bearlib/languages/definitions/JavaScript.py
coalib/bearlib/languages/definitions/Matlab.py
coalib/bearlib/languages/definitions/PHP.py
coalib/bearlib/languages/definitions/PowerShell.py
coalib/bearlib/languages/definitions/Python.py
coalib/bearlib/languages/definitions/Shell.py
coalib/bearlib/languages/definitions/TypeScript.py
coalib/bearlib/languages/definitions/Vala.py
coalib/bearlib/languages/definitions/__init__.py
coalib/bearlib/languages/definitions/m4.py
coalib/results/result_actions/IgnoreResultAction.py

This changes `comment_delimiter` to `comment_delimiters`
and uses tuple for it, in order to support languages having
multiple comment delimiters.
Closes https://github.com/coala/coala/issues/5591
them. …

languages: Allow more than one comment delimiter

---

coalib/bearlib/abstractions/Linter.py
tests/bearlib/abstractions/LinterTest.py

Add linter option to remove an error message,
if line/column number is 0.
Closes https://github.com/coala/coala/issues/5600
them. …

Linter: Add option to remove 0 number

---

tests/bears/BearTest.py
tests/core/BearTest.py

Use httpbin instead of httpbin because
of SSL certification error.
Closes https://github.com/coala/coala/issues/5628

BearTest: Replace httpstat with Google teapot

---

coalib/bearlib/aspects/Formatting.py
coalib/bearlib/aspects/Metadata.py
coalib/bearlib/aspects/Redundancy.py
coalib/bearlib/aspects/Security.py
coalib/bearlib/aspects/Smell.py
coalib/bearlib/aspects/Spelling.py
coalib/bearlib/aspects/meta.py
coalib/bearlib/aspects/root.py
coalib/results/Result.py
tests/bearlib/aspects/ClassTest.py
tests/bearlib/aspects/conftest.py
tests/results/result_actions/PrintAspectActionTest.py

This renames class name `docs` to `Docs` so that
it follows CapWords convention.
Closes https://github.com/coala/coala/issues/5626
them.
When asked …

aspects: Rename class `docs` to follow CapWords

---

.misc/check_unsupported.sh

Small improvements by sharing the logic with bears repository.
The use of `coverage run` has been discontinued as coverage of
`setup.py` is not needed for assert_supported_version
as bears repo now has mock tests for that function.
Related to https://gitlab.com/coala/mobans/issues/65
them.
likely receive a lot of bot comments and …

check_unsupported.sh: Use template

---

coalib/output/ConsoleInteraction.py

This adds color and a new symbol to enhance invalid option error message
Closes https://github.com/coala/coala/issues/5225
them. …

ConsoleInteraction.py: Improve error message

---

coalib/parsing/CliParsing.py
tests/parsing/CliParsingTest.py

Add conflict check for arguments `-config` and `--no-config`
Fixes https://github.com/coala/coala/issues/5115
them. …

CliParsing.py: Throw error for conflicting arguments

---

coalib/coala_modes.py

Warn if log_printer is used in mode_normal function.
Closes https://github.com/coala/coala/issues/4972
them. …

coala_modes.py: Warn for log_printer param

---

coalib/bears/Bear.py
tests/bears/BearTest.py
tests/bears/DebugBearsTest.py

Add the code of Settings inspection
toolset so that user can access the
settings of a Bear in Debug environment
and add initial test.
Related to https://github.com/coala/coala/issues/5545

Bears.py: Add Debugger Setting toolset

---

coalib/bears/Bear.py
coalib/bears/GlobalBear.py
coalib/processes/Processing.py
tests/bears/BearTest.py
tests/processes/ProcessingTest.py

Add initial Fix the API breakage problem
because of `debugger` flag in bear base
class.
Related to https://github.com/coala/coala/issues/5676

Bear: Remove debugger from init

---

.coafile

Removed E133,E242 and E303 from pycodestyle_ignore list.
Fixes https://github.com/coala/coala/issues/5389
them.

.coafile: Change in pycodestyle_ignore list

---

coalib/results/Diff.py

This changes condition of the third example in the docstring to
'If ``-1`` is given'.
It prevents bear developers from using any arbitrary negative value.
Closes https://github.com/coala/coala/issues/5329
them. …

Diff.py: Modify docstring of split_diff function

---

coalib/bearlib/__init__.py
tests/bearlib/DeprecateSettingsTest.py

Adds support for splitting deprecated arg into multiple new args.
Adds test for it as well.
Closes https://github.com/coala/coala/issues/5683
them. …

deprecate_settings: Support splitting setting

---

coalib/parsing/CliParsing.py
coalib/parsing/ConfParser.py
tests/parsing/ConfParserTest.py

Corrected typo in variable name comment_seperator and changed it to comment_separator.
Added comment_seperator as a deprecated argument.
Closes https://github.com/coala/coala/issues/5510
them.

CliParsing.py,ConfParser.py : Change in variable name

---

coalib/bearlib/languages/definitions/C.py
coalib/bearlib/languages/definitions/CPP.py
coalib/bearlib/languages/definitions/CSS.py
coalib/bearlib/languages/definitions/CSharp.py
coalib/bearlib/languages/definitions/Fortran.py
coalib/bearlib/languages/definitions/Golang.py
coalib/bearlib/languages/definitions/Java.py
coalib/bearlib/languages/definitions/JavaScript.py
coalib/bearlib/languages/definitions/Python.py
coalib/bearlib/languages/definitions/Tcl.py
coalib/bearlib/languages/definitions/VisualBasic.py
coalib/bearlib/languages/definitions/__init__.py

This adds characters used to escape delimiters/quotes
for each language in their respective language
definitions.
This is part of `Convert Bear To Aspects` GSoC project.
them. …

language: Add `string_delimiter_escape` to language definitions

---

coalib/core/PersistentHash.py
tests/core/PersistentHashTest.py

Task objects are now sorted first before
computing their persistent hash
Closes https://github.com/coala/coala/issues/5188
them. …

PersistentHash: Preserve Order

---

coalib/processes/Processing.py

Fix logging message related to file dict collection.
Fixes https://github.com/coala/coala/issues/5708
them. …

Processing.py: Fix file dict logging

---

docs/Developers/Git_Basics.rst

Git_Basics.rst: add how to install Git via XCode on MacOS
closes #3843

Included terminal command to install Git via XCode on MacOS

---

coalib/collecting/Collectors.py
tests/collecting/CollectorsTest.py

Remove the trailing globstar from ignore glob patterns and warn the user
about it. This ensures that the entire directory is not globbed.
Closes https://github.com/coala/coala/issues/5737
them. …

Collectors.py: Discard trailing ** in ignore glob

---

coalib/testing/LocalBearTestHelper.py

LocalBearTestHelper had an undeclared dependency on pytest-timeout
so it would not work unless the user had install pytest-timeout.
None of our bear test suites use this timeout argument, as the
timeout set in their repo configuration is sufficient.
Fixes https://github.com/coala/coala/issues/5508
them.
likely receive a lot of bot …

LocalBearTestHelper: Decommission timeout

---

docs/Developers/Git_Basics.rst

Character length of commit body is changed from 50 to 72.
Closes #5777
@PrajwalM2212

Git_Basics.rst: Maximum line length of commit body change to 72

---

coalib/settings/ConfigurationGathering.py
coalib/settings/SectionFilling.py
tests/settings/SectionFillingTest.py

The parameter 'targets' was inserted into the middle of the
argument list, breaking existing usage of it.
It should also not be necessary to provide this parameter,
as usage of this function may not have CLI determined
targets.
Fixes https://github.com/coala/coala/issues/5805
them.
likely receive a lot of bot comments and build …

SectionFilling: Make targets optional

---

docs/Developers/Writing_Native_Bears.rst

Writing_Native_Bears.rst:Fix typo on line 205
This fixes typo and removes the extra 
us on line 205 in coala documentation.
Fixes https://github.com/coala/coala/issues/5766

Fixing typo in Writing_Native_Bears.rst

---

coala
tests/bearlib/abstractions/external_bear_wrap_testfiles/ExternalBearWrapTest.py
tests/bearlib/abstractions/external_bear_wrap_testfiles/test_external_bear.py

The tests were failing due to new feature in autopep8,
i.e. E402 - Fix module level import not at top of file.
Closes #5834
them. …

Fixed CI errors due to autopep8 upgrade

---

coalib/parsing/Globbing.py
tests/parsing/GlobbingTest.py

This reverts commit 8e9bacff940cb6b9e4e76bc3c1c4071b55499d9e.
Fixes https://github.com/coala/coala/issues/5808
them. …

Revert "Globbing.py: Return False if globs are..."

---

docs/Developers/Writing_Good_Commits.rst

This fix uses real commits as examples for more clarity.
Closes  https://github.com/coala/coala/issues/5819

Writing_Good_Commits.rst: Use better examples

---

coalib/parsing/ConfParser.py
coalib/results/SourcePosition.py
coalib/settings/ConfigurationGathering.py
coalib/settings/Setting.py
tests/parsing/ConfParserTest.py
tests/results/SourcePositionTest.py
tests/settings/SettingTest.py

This adds SourcePosition to Setting.origin which helps
in identifying the starting line number of a setting in 
.coafile.
Related to https://github.com/coala/coala/issues/5044
them. …

Setting.py: Add SourcePosition to Setting.origin

---

coalib/bearlib/languages/__init__.py

Fixes  #5745 
I've used a tool called `isort` https://pypi.org/project/isort/.
It helps sorting the imported module in alphabetical order just by running a command and saves time.

__init__.py: Arrange imports alphabetically

---

coalib/collecting/Collectors.py
tests/collecting/CollectorsTest.py

The warning is necessary only when the rest of the ignore path is a
canonical directory which doesn't contain any wildcards. This commit
adds a check to ensure that if the path contains other wildcards, the
warning isn't generated.
Fixes #5856
them.
pass on …

collecting: Fix incorrect trailing '**' warning

---

coalib/testing/LocalBearTestHelper.py
tests/testing/LocalBearTestHelperTest.py

The timeout parameter is unused and this patch
logs a deperecation warning for that.
Closes https://github.com/coala/coala/issues/5812
them.
When …

LocalBearTestHelper.py: Add deprecation warning

---

coalib/bearlib/languages/__init__.py
coalib/bearlib/languages/definitions/DOT.py
tests/TestUtilities.py

This pull request adds dot language definition.
New language definition is placed in coalib/bearlib/languages/definitions/dot.py
Closes https://github.com/coala/coala/issues/5823

Dot language definition

---

.coafile

This fixes the typo in .coafile from 'builting' --> 'builtin'
Closes #5949
them. …

.coafile: Fix docstring typo builting --> builtin

---

docs/Developers/Language_Naming_Format.rst
docs/Developers/Writing_Linter_Bears.rst
docs/Developers/Writing_Native_Bears.rst

Add language naming format note to bear doc
This adds language naming format information to
Writing_Native_Bears.rst and Writing_Linter_Bears.rst.
The information is stored in the file Language_Naming_Format.rst.
Closes https://github.com/coala/coala/issues/5826
See the below links for changes.
https://ibb.co/r3bTtfL
them.
likely …

Add language naming format note to bear doc

---

coalib/settings/Section.py
coalib/settings/Setting.py
tests/parsing/ConfParserTest.py
tests/settings/SettingTest.py

This adds end line number of a setting in coafile.
Related to https://github.com/coala/coala/issues/5044
them. …

Setting.py: Add end line number of setting

---

.travis.yml

This changes the unsupported Python
version from 3.4.3 to 3.4.1 on Travis CI.
Closes https://github.com/coala/coala/issues/6017
them. …

.travis.yml: Update unsupported Python version

---

.gitignore
.misc/appveyor.yml
.travis.yml
setup.py

Older setuptools/pip fails on installation
due to missing syntax in them. This fixes
that problem by avoiding such installation.
Related to: https://github.com/coala/coala/issues/6017
them. …

setup.py: Add minimum pip requirement check

---

coalib/output/ConsoleInteraction.py
tests/output/ConsoleInteractionTest.py

This modifies color_letter function to run as correctly
when there is a uppercase letter after "the" uppercase
letter in parenthesis and also if action has a associated warning then
it gets highlighted.
Fixes https://github.com/coala/coala/issues/6034

ConsoleInteraction: Modify color_letter function

---

tests/bearlib/languages/LanguageTest.py

This fixes the issue reported by autopep8 in LanguageTest.py file.
Closes https://github.com/coala/coala/issues/6141

LanguageTest.py: Fix autopep8 issue

---

.travis.yml
setup.cfg
test-requirements.txt

This along with PR [passes autopep8](https://github.com/coala/coala/pull/6145) and [restrict bandit version](https://github.com/coala/coala-bears/pull/2984) should fix the travis.ci pipeline.
Will make changes in coala-moban once these are approved.
closes #6133

travis.yml: Fix build issues

---

.misc/check_unsupported.sh
.misc/constants.ps1
.moban.yaml
.travis.yml
setup.py
test-requirements.txt

I have tested these changes by replacing the mobans gitlab link with my fork's link. It now successfully passes the [mobans test](https://travis-ci.com/github/anshalshukla/coala/builds/220587161) as well.
closes #6151

Mobans fix

---

coalib/bearlib/abstractions/Linter.py
tests/bearlib/abstractions/LinterTest.py
tests/settings/ConfigurationGatheringTest.py

`repr` methods in linter.py now returns memory location. Tests have been modified and successfully tested with 100% coverage.
closes #6051

repr methods of linter.py now returns memory location.

---

coalib/settings/Setting.py
tests/settings/SettingTest.py

Modify the `__repr__` method to return
memory location as well to comply with the
default behavior of the method.
Closes https://github.com/coala/coala/issues/6050

settings.py: Return memory location in `__repr__`

---

README.rst

The waffle service is defunct with all its resources/assets, see https://discourse.ros.org/t/replacement-for-waffle-io/8355.
Closes https://github.com/coala/coala/issues/5959

Readme remove the link to the dead waffle service
