coalib/results/Diff.py, coalib/results/LineDiff.py, coalib/results/result_actions/ResultAction.py, coalib/tests/results/DiffTest.py, coalib/tests/results/LineDiffTest.py, coalib/tests/results/result_actions/ResultActionTest.py
I'll do the introduction of the ResultAction objects on this branch. This also has implications on #167.
=> ResultAction

coalib/output/ConsoleInteractor.py, coalib/output/printers/ConsolePrinter.py, coalib/tests/TestHelper.py, coalib/tests/output/printers/ConsolePrinterTest.py, execute_all_tests.py
This is currently WIP, will add pending review when ready but I need travis.
=> Fixing windows tests

doc/getting_involved/CODESTYLE.md, doc/getting_involved/COMMIT_MESSAGES.md, doc/getting_involved/REVIEWING.md
This is a draft but i finished The first parts, so Plesse go for it and write down any concerns.
=> getting_involved: Add CODESTYLE.md

bears/misc/KeywordBear.py, bears/misc/LineCountBear.py, bears/misc/LineLengthBear.py, bears/spacing/SpaceConsistencyBear.py, bears/tests/LocalBearTestHelper.py, coalib/bears/Bear.py, coalib/bears/GlobalBear.py, coalib/bears/LocalBear.py, coalib/processes/BearRunner.py, coalib/tests/bears/BearTest.py, coalib/tests/bears/GlobalBearTest.py, coalib/tests/bears/LocalBearTest.py, coalib/tests/processes/BearRunnerTest.py, coalib/tests/processes/section_executor_test_files/GlobalTestBear.py, coalib/tests/processes/section_executor_test_files/LocalTestBear.py, doc/getting_involved/WRITING_BEARS.md
I have succesfully renamed the run_bear() method to run() and the run() method to execute(). I hope i did it correctly. Please review!
=> Bear: Rename run_bear() to run()

bears/misc/KeywordBear.py, coalib/output/ConsoleInteractor.py, coalib/tests/output/ConsoleInteractorTest.py
FIxes to close #296 and #300 .
=> Changed comment segregator and wording of comment

doc/getting_involved/TESTING.md, doc/sphinx/execute_all_tests.rst, doc/sphinx/index.rst
change ./execute_all_tests.py command in these files doc/getting_involved/README.md  ,  doc/getting_involved/TESTING.md
to  ./run_tests.md
Fixing : this bug #334
=> Documentation : change  Run all test command

coalib/output/ConfWriter.py
see #274
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/coala-analyzer/coala/pull/361%23issuecomment-77207818%22%2C%20%22https%3A//github.com/coala-analyzer/coala/pull/361%23issuecomment-77208264%22%2C%20%22https%3A//github.com/coala-analyzer/coala/commit/5b6290d06c2019e18dc9207993b9e55bbc7e1af2%23commitcomment-10034938%22%2C%20%22https%3A//github.com/coala-analyzer/coala/pull/361%23issuecomment-77208686%22%2C%20%22https%3A//github.com/coala-analyzer/coala/commit/a8df98ec67f8c4fd30895fa8e0149e585553755a%23commitcomment-10035005%22%2C%20%22https%3A//github.com/coala-analyzer/coala/commit/a8df98ec67f8c4fd30895fa8e0149e585553755a%23commitcomment-10035172%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22htt …
=> add newlines in coafiles auomatically

doc/getting_involved/COMMIT_MESSAGES.md
I love those PRs where I collect small changes totally unrelated to each other
=> misc small changes :)

RELEASE_NOTES.md, bears/misc/KeywordBear.py, bears/misc/LineLengthBear.py, bears/spacing/SpaceConsistencyBear.py, bears/tests/LocalBearTestHelper.py, bears/tests/spacing/SpaceConsistencyBearTest.py, coalib/bears/LocalBear.py, coalib/misc/StringConverter.py, coalib/processes/communication/LogMessage.py, coalib/settings/SectionManager.py, coalib/tests/TestHelper.py, coalib/tests/settings/SectionManagerTest.py, run_tests.py
thats some preparations for this for now but I'll add more later. Ready to review. (At least the ones not marked WIP)
=> parse user config file

coalib/parsing/Glob.py, coalib/tests/parsing/GlobTest.py
Syntax: prefix(either|or)postfix
=> "or"-functionality for glob

coalib/parsing/StringProcessing.py, coalib/tests/parsing/StringProcessingTest.py
=> Test restructurization for StringProcessing

coalib/parsing/StringProcessing.py, coalib/tests/parsing/StringProcessingTest.py
Function that removes all escape-sequences.
This one is a really short commit because I can only test the standard test-strings^^
I hope that's it.
=> StringProcessing: Add unescape() function

coalib/tests/parsing/StringProcessingTest.py
Yey a jubilee, 1100 commit! :)
=> Tests for position_is_escaped()

coalib/tests/output/ConsoleInteractorTest.py
=> ConsoleInteractorTest: Refactor comment

setup.py
As for https://docs.python.org/3/library/distutils.html we rather want
the enhanced setuptools functionality.
=> setup: Use setuptools

coalib/tests/TestHelper.py
=> testing: Sort tests alphabetically

.gitignore
Prevents files generated by sublime project to be committed by accident.
=> Ignore sublime project files

coalib/tests/parsing/StringProcessingTest.py, coalib/tests/parsing/StringProcessingTests/PositionIsEscapedTest.py, coalib/tests/parsing/StringProcessingTests/SearchForTest.py, coalib/tests/parsing/StringProcessingTests/SearchInBetweenTest.py, coalib/tests/parsing/StringProcessingTests/SplitTest.py, coalib/tests/parsing/StringProcessingTests/UnescapeTest.py, coalib/tests/parsing/StringProcessingTests/UnescapedSearchForTest.py, coalib/tests/parsing/StringProcessingTests/UnescapedSearchInBetweenTest.py, coalib/tests/parsing/StringProcessingTests/UnescapedSplitTest.py
=> Cleanup StringProcessingTest

coalib/parsing/__init__.py
3 Lines of documentation to review :)
=> StringProcessing: Add module description

.misc/.deploy.zanata.sh
=> deploy.zanata: Add shebang

coalib/collecting/Collectors.py, coalib/collecting/Importers.py, coalib/output/dbus/DbusDocument.py, coalib/parsing/Globbing.py, coalib/processes/Processing.py, coalib/tests/collecting/CollectorsTest.py, coalib/tests/parsing/GlobbingTest.py, coalib/tests/processes/ProcessingTest.py, docs/Glob_Patterns.md, mkdocs.yml
This PR adresses:
* #396 escaping for globs
* #460 document what our glob supports
* #596 need a function similar to fnmatch in glob
* #681 add examples to documentation
=> glob rework and fnmatch introduction

coalib/output/ConfWriter.py, coalib/parsing/ConfParser.py, coalib/parsing/StringProcessing.py, coalib/settings/FunctionMetadata.py, coalib/settings/Setting.py, coalib/tests/parsing/LineParserTest.py, coalib/tests/settings/DocumentationCommentTest.py, coalib/tests/settings/FunctionMetadataTest.py
@AbdealiJK I hope I don't miss something
That were all of those issue PyCharm told me^^
=> Turn default parameters into tuples

docs/requirements.txt, mkdocs.yml
Custom module to fix issues with code syntax highlighting in Notes
Fixes https://github.com/coala-analyzer/coala/issues/430
=> mkdocs: Add pymdown_extensions

.misc/deps.sh, .misc/generate_pot.sh, circle.yml
If the whole repo is taken, it has a change of taking .py files which
we did not write - and this may make it break.
=> zanata: Translate from coalib and bears only

README.md, bears/codeclone_detection/ClangCloneDetectionBear.py, bears/codeclone_detection/ClangCountVectorCreator.py, bears/codeclone_detection/ClangFunctionDifferenceBear.py, bears/codeclone_detection/CloneDetectionRoutines.py, bears/tests/codeclone_detection/ClangCloneDetectionBearTest.py, bears/tests/codeclone_detection/clone_detection_samples/LICENSE, bears/tests/codeclone_detection/clone_detection_samples/clones/python_casing.c, bears/tests/codeclone_detection/clone_detection_samples/clones/python_casing2.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s1a.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s1b.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s1c.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s2a.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s2b.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s2c.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s2d.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s3a.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s3b.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s3c.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s3d.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s3e.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s4a.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s4b.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s4c.c, bears/tests/codeclone_detection/clone_detection_samples/clones/s4d.c, bears/tests/codeclone_detection/clone_detection_samples/non_clones/builder_editorconfig.c, bears/tests/codeclone_detection/clone_detection_samples/non_clones/pythonparser.c
This takes more possible include paths into account.
=> CloneDetection: Use recursive glob for include path

bears/codeclone_detection/CountVector.py, bears/tests/codeclone_detection/CountVectorTest.py, coalib/misc/Decorators.py, coalib/results/Result.py, coalib/results/SourcePosition.py, coalib/settings/Section.py, coalib/settings/Setting.py, coalib/tests/misc/DecoratorsTest.py, coalib/tests/results/ResultTest.py, coalib/tests/results/SourcePositionTest.py
Easily generate `__repr__` functions!
=> @generate_repr - v2

setup.py
Fixes https://github.com/coala-analyzer/coala/issues/733
=> setup: Assert supported version before imports

.misc/deps.sh, README.md, docs/index.md
circleci has some issues due to which this commit is required. It's better
to leave this commit as it'll be harmless even when circleci is fixed.
=> circleci: Fix circleci issues

.misc/zanata.xml
This is log overdue and was forgotten.
=> zanata: Change to 0.3

.travis.yml, coalib/__init__.py, docs/Getting_Involved/Writing_Tests.md, docs/Users/Install.md, setup.py
Fixes https://github.com/coala-analyzer/coala/issues/920
=> Remote python 3.2 support

coalib/output/ConsoleInteraction.py, coalib/results/result_actions/ShowPatchAction.py, coalib/tests/output/ConsoleInteractionTest.py, coalib/tests/results/result_actions/TestShowPatchActionTest.py
preliminary PR, tests are missing
=> Add ShowPatchAction

coalib/collecting/Collectors.py, coalib/tests/collecting/CollectorsTest.py
=> collectors: Accept strings for file paths

coalib/results/result_actions/ShowPatchAction.py, coalib/tests/results/result_actions/ShowPatchActionTest.py
Fixes https://github.com/coala-analyzer/coala/issues/969
=> ShowPatchAction: Compress filename lines

coalib/results/SourceRange.py, coalib/tests/results/SourceRangeTest.py
this can be squashed to one commit if everything else is fine.
=> SourceRange object

coalib/coala_main.py, coalib/output/ConsoleInteraction.py, coalib/parsing/DefaultArgParser.py, coalib/settings/Section.py, coalib/settings/SectionFilling.py, coalib/tests/output/ConsoleInteractionTest.py, coalib/tests/settings/SectionTest.py
This allows the user to simply show a list of all bears.
=> Add --show-all-bears

coalib/parsing/DefaultArgParser.py, coalib/processes/Processing.py, coalib/tests/processes/ProcessingTest.py
related to https://github.com/coala-analyzer/coala/issues/1034
=> limit results

coalib/collecting/Collectors.py, coalib/parsing/DefaultArgParser.py, coalib/processes/Processing.py, coalib/tests/collecting/CollectorsTest.py
Not necessarily complete, i.e. a a command line options is missing, but this should work if the appropriate setting is set in the section.
=> ignore files in collectors

coalib/bears/Bear.py, coalib/tests/processes/BearRunningTest.py
Related: https://github.com/coala-analyzer/coala/issues/1061
=> Bear: Handle no return value

coalib/results/Result.py, coalib/tests/results/ResultTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1014
=> Result: Check for valid severity

bears/general/LineLengthBear.py
LineLengthBear : Documentation Spacing
Fixes https://github.com/coala-analyzer/coala/issues/947
=> Code Conventions

.misc/deploy.coverage.sh, .misc/deps.sh, .misc/tests.sh, bears/js/JSONFormatBear.py, circle.yml, docs/Users/Install.md, setup.py
We have dependencies that dropped support for this and it's holding a
lot of problems for us.
=> Remove python 3.2 support

coalib/settings/FunctionMetadata.py
fixes https://github.com/coala-analyzer/coala/issues/946
=> FunctionMetadata.py : if-none initialisation

coalib/collecting/Collectors.py
Otherwise nondeterministic - almost evil - things may happen.
=> Collectors: Work on list copy when removing ignored

coalib/bearlib/abstractions/Lint.py
Fixes https://github.com/coala-analyzer/coala/issues/1192
=> Lint: Check for None before conversion attempt

coalib/bearlib/languages/LanguageDefinition.py, coalib/coala_dbus.py, coalib/misc/Constants.py, coalib/misc/Exceptions.py, coalib/misc/StringConverter.py, coalib/output/Tagging.py, coalib/output/dbus/BuildDbusService.py, coalib/output/printers/EspeakPrinter.py, coalib/parsing/ConfParser.py, coalib/parsing/DefaultArgParser.py, coalib/processes/BearRunning.py, coalib/settings/ConfigurationGathering.py, coalib/settings/Section.py, coalib/tests/output/dbus/BuildDbusServiceTest.py, coalib/tests/output/dbus/DbusDocumentTest.py, coalib/tests/output/dbus/DbusTest.py, coalib/tests/output/printers/LogPrinterTest.py, coalib/tests/output/printers/StringPrinterTest.py, coalib/tests/processes/communication/LogMessageTest.py, coalib/tests/settings/ConfigurationGatheringTest.py, coalib/tests/settings/SectionTest.py, setup.py
As per Issue #917  , I have actually moved the constants outside the class.
=> Added constants outside the class

coalib/collecting/Collectors.py
Fixes https://github.com/coala-analyzer/coala/issues/1190
=> Refactored _yield_if_right_kind into a condition

run_tests.py
Fixes https://github.com/coala-analyzer/coala/issues/1217
=> tests: Make run_tests.py work with virtualenv

coalib/misc/ContextManagers.py, coalib/tests/MakeTempTest.py, coalib/tests/settings/ConfigurationGatheringTest.py
Related to https://github.com/coala-analyzer/coala/issues/1159
=> tests: Move make_temp() to ContextManagers

docs/Getting_Involved/Review.md
As suggested I have removed the rultor reader note from [Review.md](Review.md) file
=> Removed rultor reader note from Review.md

coalib/output/ConsoleInteraction.py, coalib/processes/Processing.py, coalib/tests/processes/ProcessingTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1226
=> ApplyPatchAction: Show error message on failing.

coalib/processes/Processing.py, coalib/results/Result.py, coalib/tests/processes/ProcessingTest.py, coalib/tests/results/ResultTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1188
=> Result:Show filename when autoapplying.

coalib/tests/misc/BuildManPageTest.py, coalib/tests/output/ConsoleInteractionTest.py, coalib/tests/output/dbus/BuildDbusServiceTest.py, coalib/tests/results/result_actions/ApplyPatchActionTest.py
Related to https://github.com/coala-analyzer/coala/issues/1159
=> tests: Implement make_temp()

coalib/results/Result.py, coalib/tests/results/ResultTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1233
=> Result: Fix Duplicate Filename

bears/c_languages/IndentBear.py, bears/natural_language/MarkdownBear.py, coalib/bearlib/abstractions/CorrectionBasedBear.py, coalib/bearlib/abstractions/Lint.py, coalib/tests/bearlib/abstractions/CorrectionBasedBearTest.py, coalib/tests/bearlib/abstractions/LintTest.py
Solves https://github.com/coala-analyzer/coala/issues/1225
=> Lint: Check for executable availability

coalib/parsing/DefaultArgParser.py, coalib/results/result_actions/ApplyPatchAction.py, coalib/tests/results/result_actions/ApplyPatchActionTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1186
=> ApplyPatchAction: Add option to deactivate creation of .orig files

coalib/parsing/DefaultArgParser.py
Usability testing with Ana has revealed that this is a weak point in our
documentation.
=> DefaultArgParser: Add bear explanation

docs/Users/Install.md
This PR fixes a minor issue, where a link is not properly written in markdown.
=> minor typo fix in installation doc

docs/Users/Install.md
Added a tiny note about requirement for python3 for coala.
Fixes https://github.com/coala-analyzer/coala/issues/1270
=> Install.md: Add note about python3 requirement

coalib/bearlib/languages/documentation/DocstyleDefinition.py, coalib/tests/bearlib/languages/documentation/DocstyleDefinitionTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1142
=> DocstyleDefinition: Use type-checks

coalib/bearlib/languages/documentation/DocstyleDefinition.py, coalib/tests/bearlib/languages/documentation/DocstyleDefinitionTest.py
=> added support for single marker_set in markers

coalib/misc/ContextManagers.py, coalib/tests/misc/ContextManagersTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1280
=> ContextManager: Have make_temp take arguments

.misc/deps.sh, bears/perl/PerlCriticBear.py, bears/tests/perl/PerlCriticBearTest.py, bears/tests/perl/test_files/perlcritic_bad.pl, bears/tests/perl/test_files/perlcritic_config.pl, bears/tests/perl/test_files/perlcritic_good.pl
Add the bears for perl critic for perl support
Add perl bear module and tests for perl
Add good perlcritic and bad perlcritic files for testing
Update appveyor and dependencies to run tests on CI
Fixes https://github.com/coala-analyzer/coala/issues/1259
=> bears: add PerlCritic bear and tests

.misc/appveyor.yml, .misc/deps.osx.sh, bears/go/GoLintBear.py, bears/tests/go/GoLintBearTest.py, bears/tests/go/test_files/golint_bad.go, bears/tests/go/test_files/golint_good.go, circle.yml
Add the bears for golint for deeper go support.
Add tests for good golint and bad golint files.
=> bears: Add Golint bear and tests

coalib/coala_delete_orig.py, coalib/coala_main.py, coalib/misc/ContextManagers.py, coalib/tests/coalaTest.py, setup.py
=> Add coala-orig to delete .orig files 

.coafile
Fixes the typo error in .coafile
Fixes https://github.com/coala-analyzer/coala/issues/1342
=> .coafile: Fix typo

coalib/output/ConfWriter.py, coalib/tests/output/ConfWriterTest.py, coalib/tests/parsing/ConfParserTest.py, coalib/tests/settings/ConfigurationGatheringTest.py
This PR tries to fix config file issues that have been reported.
=> Config file fixes

coalib/coala_delete_orig.py
Fixes [https://github.com/coala-analyzer/coala/issues/1359](url) , [https://github.com/coala-analyzer/coala/issues/1360](url)
=> Fixes issues #1359, #1360

coalib/coala_ci.py, coalib/output/ConsoleInteraction.py, coalib/tests/output/ConsoleInteractionTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1256
=> Add output to coala-ci(WIP)

.misc/deps.sh, bears/go/GoImportsBear.py, bears/tests/go/GoImportsBearTest.py
Add the bear for goimports for automatically adding / removing
missing or unwanted imports in golang
Fixes https://github.com/coala-analyzer/coala/issues/1332
=> bears: Add goimports bear

coalib/tests/TestUtilities.py, coalib/tests/coalaJSONTest.py, coalib/tests/coalaTest.py
Improve coverage by running `coala-json`
Fixes https://github.com/coala-analyzer/coala/issues/1384
=> coalaJSONTest.py: Add test to run coala-json

coalib/misc/ContextManagers.py
=> misc/ContextManager:Fix spelling error

README.rst
Corrected the link for Getting Involved Section.
Fixes #1350
=> docs: Correct link in README.rst

bears/python/PyLintBear.py
Fixes https://github.com/coala-analyzer/coala/issues/1417
=> PyLintBear.py: Remove sys.version_info check

bears/c_languages/codeclone_detection/ClangCloneDetectionBear.py
Fixes https://github.com/coala-analyzer/coala/issues/906
=> Update ClangCloneDetectionBear.py status message

coalib/processes/Processing.py, coalib/tests/processes/ProcessingTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1425
=> Processing.py: Modify Auto-apply message

RELEASE_NOTES.rst
Fixes https://github.com/coala-analyzer/coala/issues/1383
=> RELEASE_NOTES: Fix incorrect links

coalib/tests/bearlib/__init__.py
Fixes https://github.com/coala-analyzer/coala/issues/1343
=> tests/bearlib: Remove double documentation

requirements.txt
I updated the version of cpplint in requirements.txt
=> requirements: Updates cpplint version

docs/Getting_Involved/README.rst
Fixes https://github.com/coala-analyzer/coala/issues/1462
=> Getting Involved: Add Testing link

bears/html/HTMLLintBear.py, bears/tests/html/HTMLLintBearTest.py, requirements.txt
Fixes https://github.com/coala-analyzer/coala/issues/1478
Added a bear that user `html-linter`
Added a test for that bear
=> bears: Add HTMLLint bear

docs/Users/Writing_Bears.rst
Improve the grammar in docs of users/Writing_Bears.
Fixes #1484.
=> Improve grammar in docs of users/writing bears

.gitignore, .misc/appveyor.yml, .misc/deps.osx.sh
Fixes https://github.com/coala-analyzer/coala/issues/1412
=> Remove checkstyle.jar

bears/tests/vcs/git/GitCommitBearTest.py, bears/vcs/git/GitCommitBear.py, coalib/bears/Bear.py, coalib/tests/bears/BearTest.py
=> GitCommitBear should run from different directory

bears/js/JSONFormatBear.py, bears/tests/js/JSONFormatBearTest.py, coalib/misc/ContextManagers.py, coalib/results/result_actions/ApplyPatchAction.py, coalib/results/result_actions/OpenEditorAction.py
Fixes https://github.com/coala-analyzer/coala/issues/1527
=> JSONFormatBear: Add keep_unicode argument

coalib/misc/Constants.py
Fixes https://github.com/coala-analyzer/coala/issues/1571
=> Constants: Remove unused constant COVERAGE_DIR

coalib/parsing/DefaultArgParser.py
=> DefaultArgParser: Fix spelling mistake

README.rst
Fixes https://github.com/coala-analyzer/coala/issues/1576
=> README: fix the tutorial link

coalib/__init__.py
Fixes https://github.com/coala-analyzer/coala/issues/1590
=> coalib/__init__.py:Remove pypy support

setup.py
Fixes https://github.com/coala-analyzer/coala/issues/1574
=> setup.py: Remove '[]' from maintainer name in setup.py

bears/c_languages/codeclone_detection/ClangCountingConditions.py, coalib/collecting/Collectors.py, coalib/parsing/CliParsing.py, coalib/settings/FunctionMetadata.py, coalib/tests/settings/ConfigurationGatheringTest.py
Fixes: https://github.com/coala-analyzer/coala/issues/1548
=> coala: Replace variables named as dummy with _

coalib/misc/Constants.py, coalib/settings/Section.py
Fixes https://github.com/coala-analyzer/coala/issues/1646
Constants.py: Remove coalib_bears_root
Fixes https://github.com/coala-analyzer/coala/issues/1646
Constants.py: Remove coalib_bears_root
Fixes https://github.com/coala-analyzer/coala/issues/1646
=> Constants.py: Remove coalib_bears_root

docs/Users/Tutorials/Self_Correcting_Bears.rst
Added tutorial about self-correcting bears using `IndentBear` as an
example.
Fixes https://github.com/coala-analyzer/coala/issues/1638
=> Self-Correcting Bear Tutorial: Add to docs

coalib/output/Tagging.py, coalib/settings/ConfigurationGathering.py
change `not a is None` with `a is not None`
Fixes https://github.com/coala-analyzer/coala/issues/1494
=> Codestyle: not a is None -> a is not None 

README.rst
=> Appveyor badge - changed from sils1297's account to an account named coala

coalib/processes/Processing.py, coalib/tests/processes/ProcessingTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1232
=> Processing: Provide line & column in ignore ranges

docs/Users/Install.rst
Fixes https://github.com/coala-analyzer/coala/issues/1692
=> Install.rst: Fix typo at line 19

docs/Users/Tutorials/Linter_Bears.rst
Fixes https://github.com/coala-analyzer/coala/issues/1562
=> Linter_Bears.rst: Fix grammatic mistake

coalib/settings/Section.py
Fixes https://github.com/coala-analyzer/coala/issues/1711
=> Section.py: bear_dirs search for dirs recursively

coalib/settings/Section.py
Fixes https://github.com/coala-analyzer/coala/issues/1712
=> Section.py: Add --bear-dirs to sys.path

docs/General_Dev_Info/git_tutorial_1.rst
=> git_tutorial_1.rst: Fix grammatical errors

docs/Users/Install.rst
Fixes https://github.com/coala-analyzer/coala/issues/1715
=> docs/install : proxy installation

.coafile
Add this bear and fix issues that came up in the docs.
Fixes https://github.com/coala-analyzer/coala/issues/1697
=> coafile: Add LanguageToolBear for docs

coalib/collecting/Dependencies.py
Fixes https://github.com/coala-analyzer/coala/issues/1281
=>  Dependencies.py: Simplifies code in class CircularDependencyError

docs/Users/Git_Help.rst, docs/index.rst
This page should help newcomers to understand git
a little better, and make it easier for them to
get started on their first contribution.
Fixes https://github.com/coala-analyzer/coala/issues/1741
I will edit the newcomers page and guide it to this link once this gets merged :)
=> Git_help.rst: Add a git tutorial page

docs/Getting_Involved/Newcomers.rst, docs/index.rst
This page will ultimately be sent to all of the newcomers and
it will guide them appropriately, so they can start contributing
just by following the guide on this page.
Fixes https://github.com/coala-analyzer/coala/issues/1734
=> Getting_Involved/Newcomers.rst: Add a better newcomer page

docs/Users/Install.rst
Fixes https://github.com/coala-analyzer/coala/issues/1749
=> Install.rst : Fix typo Max -> Mac

docs/Users/Install.rst
Fixes https://github.com/coala-analyzer/coala/issues/1786
=> Install.rst: Fix minor changes

coalib/parsing/StringProcessing/Core.py
Fix https://github.com/coala-analyzer/coala/issues/1772
=> Core.py: Fix typo, escaped -> escape

setup.py
Fixes https://github.com/coala-analyzer/coala/issues/1792
=> setup: Package coalang files

docs/Users/Tutorials/Git_Help.rst
Fixes https://github.com/coala-analyzer/coala/issues/1774
=> Git_Help.rst: Add remote repo sync section

coalib/bearlib/languages/definitions/c.coalang, coalib/bearlib/languages/definitions/python3.coalang
Fixes https://github.com/coala-analyzer/coala/issues/1797
=> coalang: Escape whitespaces in keys

coalib/coala_delete_orig.py
Modify message about Couldn't delete...
Fixes #1514
=> coala_delete_orig: Remove unneeded ellipsis

docs/Getting_Involved/Newcomers.rst
Changes broken link in paragraph 'Start working'.
Fixes https://github.com/coala-analyzer/coala/issues/1782
=> Newcomers.rst: Fix broken link

docs/Users/Tutorials/Git_Help.rst
Fixes https://github.com/coala-analyzer/coala/issues/1789
=> Git_Help.rst: Section explaining commit squashing

coalib/coala.py, coalib/coala_ci.py, coalib/coala_format.py, coalib/coala_json.py, coalib/coala_main.py, coalib/results/ResultFilter.py
Some main routines may need this, it's e.g. needed for GitMate and in
general for things where we want to filter out old results.
=> run_coala: Return file dict

docs/Users/Tutorials/Linter_Bears.rst
Fixes https://github.com/coala-analyzer/coala/issues/1779
=> docs: Change regex link to python 3

coalib/output/ConsoleInteraction.py, setup.py, tests/output/ConsoleInteractionTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1843
=> setup: Pull in long description from readme

.misc/deps.osx.sh, .misc/deps.sh
Silencing just hinders debugging.
=> CI: Don't silence commandos

coalib/output/ConsoleInteraction.py, tests/output/ConsoleInteractionTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1825
Takes in `failed_actions` and asks  for related params in case of a failed execution
=> Update action everytime

coalib/output/ConsoleInteraction.py, coalib/parsing/CliParsing.py, tests/output/ConsoleInteractionTest.py
=> Fixes two newcomer issues

README.rst
Add `gitmate` badge from [shields.io](https://img.shields.io)
=> README: Add Gitmate Badge

coalib/output/ConsoleInteraction.py
Added documentation for console_printer in print_actions()
=> Fixes issue #1870

circle.yml
=> Newcomer fix

coalib/misc/StringConverter.py, coalib/settings/Setting.py, requirements.txt, tests/settings/SettingTest.py
Added url validation in settings. It will check if the given setting
is a valid url or not. If valid will return the settings as a string
else it will throw a Value error.
=> Setting: Add url validation.

.misc/deps.osx.sh, coalib/misc/Constants.py, requirements.txt
Replace manual management of configuration and user data storage
with appdirs.
Fixes https://github.com/coala-analyzer/coala/issues/1805
=> Constants: Change managing of user data

docs/Users/Install.rst, docs/Users/Tutorials/Self_Correcting_Bears.rst
Fixes https://github.com/coala-analyzer/coala-bears/issues/120
=> Rename IndentBear to GNUIndentBear

coalib/misc/ContextManagers.py, tests/misc/ContextManagersTest.py, tests/settings/ConfigurationGatheringTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1314
An issue in `coala-bears` should be open regarding:
- https://github.com/coala-analyzer/coala-bears/blob/master/tests/vcs/git/GitCommitBearTest.py#L157
- https://github.com/coala-analyzer/coala-bears/blob/master/bears/vcs/git/GitCommitBear.py#L43
=> ContextManagers: Add contexmanager for os.chdir()

docs/Users/Tutorials/Writing_Bears.rst
Fixes https://github.com/coala-analyzer/coala/issues/1871
=> docs: Add tutorial for dependancy management

coalib/settings/FunctionMetadata.py, docs/Users/Tutorials/Writing_Bears.rst
=> Narrow except clause when dealing with annotations

README.rst
This way it's easier to read.
Credits: @sils1297
=> README.rst: Restructure

coalib/misc/Annotations.py, tests/misc/AnnotationsTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1859
=> Annotations: Add function for chaining annotations

coalib/__init__.py, coalib/misc/Constants.py, coalib/output/dbus/BuildDbusService.py, setup.py
Fixes https://github.com/coala-analyzer/coala/issues/1957
=> Constants: Import appdirs when needed

tests/parsing/GlobbingTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1994
=> GlobbingTest: Ignore .pyc files

coalib/results/AbsolutePosition.py, coalib/results/SourceRange.py, tests/results/AbsolutePositionTest.py, tests/results/SourceRangeTest.py
Absolute Position to work with positions directlyd
=> SourceRange add position functionalities 

docs/Getting_Involved/Writing_Tests.rst
Fixes https://github.com/coala-analyzer/coala/issues/1999
=> docs: Add a note on goal of writing tests

CONTRIBUTING.md, README.rst, docs/Getting_Involved/Codestyle.rst, docs/Getting_Involved/Newcomers.rst, docs/Getting_Involved/README.rst, docs/Getting_Involved/Review.rst, docs/Getting_Involved/Testing.rst, docs/Getting_Involved/Writing_Documentation.rst, docs/Getting_Involved/Writing_Good_Commits.rst, docs/Getting_Involved/Writing_Tests.rst, docs/Users/Exit_Codes.rst, docs/Users/External_APIs.rst, docs/Users/Git_Hooks.rst, docs/Users/Glob_Patterns.rst, docs/Users/Install.rst, docs/Users/Tutorials/Git_Help.rst, docs/Users/Tutorials/Linter_Bears.rst, docs/Users/Tutorials/Self_Correcting_Bears.rst, docs/Users/Tutorials/Tutorial.rst, docs/Users/Tutorials/Writing_Bears.rst, docs/Users/coafile.rst
Fixes https://github.com/coala-analyzer/coala/issues/2017
=> coala: Make it italic throughout docs

docs/Users/Tutorials/Testing_Bears.rst, docs/index.rst
Fixes https://github.com/coala-analyzer/coala/issues/1916
=> docs: Add Testing_Bears.rst

.rultor.yml
Added apt-get install, apt-get update, pip3 install.
Fixes https://github.com/coala-analyzer/coala/issues/1904
=> .rultor.yml: Install dependencies

README.rst
Fixes https://github.com/coala-analyzer/coala/issues/1771
CC @AbdealiJK for reviwe
=> README: Add demo gif

README.rst, circle.yml, coalib/settings/ConfigurationGathering.py, docs/Users/Tutorials/Testing_Bears.rst, tests/bears/BearTest.py, tests/coalaCITest.py, tests/settings/ConfigurationGatheringTest.py
Fixes https://github.com/coala-analyzer/coala/issues/2030
=> get_config_directory: Use `files` origin

coalib/processes/Processing.py, tests/processes/ProcessingTest.py
=> debug: Output files that are checked

coalib/bearlib/abstractions/Linter.py, tests/bearlib/abstractions/LinterTest.py
=> Linter: Assume normal severity if not given

.codecov.yml, coalib/collecting/Importers.py, tests/coalaTest.py, tests/test_bears/LinterBear.py
=> _is_defined_in: Accept parent class locations too

coalib/bearlib/abstractions/Linter.py
This massively helps debugging linters.
Closes https://github.com/coala-analyzer/coala/issues/2060
=> Linter: Output command on debug

coalib/collecting/Importers.py
Importers.py, line 82: Chek -> Check
=> Issue 2058 fixed.

coalib/__init__.py, setup.py
=> coalib: Add get_version function

.codecov.yml, coalib/bearlib/abstractions/Linter.py, coalib/results/Diff.py, tests/bearlib/abstractions/LinterTest.py
Fixes https://github.com/coala-analyzer/coala/issues/2117
=> Diff: Add distance param

requirements.txt
This will also work on debian hopefully.
=> requirements: Use backwards compatible notation

coalib/bears/Bear.py, coalib/bears/requirements/PackageRequirement.py, coalib/bears/requirements/PythonRequirement.py
Requirements is a tuple that holds the requirements
that are to be installed for each bear. This helps
not maintaining a requirements.txt file.
=> Add PackageRequirements

docs/Users/Tutorials/Auto_Completion.rst
Makes it easier to follow and removes some unneeded redundancy.
=> Auto_Completion.rst: Unite guide for zsh and bash

tests/TestUtilities.py, tests/coalaTest.py, tests/output/ConsoleInteractionTest.py, tests/output/TaggingTest.py
Fixes https://github.com/coala-analyzer/coala/issues/2182
=> tests: Replace raise_error with mocks

docs/Getting_Involved/Newcomers.rst, docs/Users/Tutorials/Git_Help.rst
As per recommendation, keep/keeping is changed to maintain in the suggested files.
Fixes #2021
=> Changed `keep`/`keeping` to `maintain`

docs/Getting_Involved/Newcomers.rst
paragraph. Fixes https://github.com/coala-analyzer/coala/issues/1780
=> Newcomers.rst: moved the 'coala gitter' link in the 'Meet the community'

coalib/bearlib/languages/LanguageDefinition.py, coalib/bearlib/languages/definitions/c.coalang, coalib/bearlib/languages/definitions/cpp.coalang, coalib/bearlib/languages/definitions/python3.coalang, tests/bearlib/languages/LanguageDefinitionTest.py
Fixes https://github.com/coala-analyzer/coala/issues/1811
=> LanguageDefinition: Remove 'language_family'

tests/coalaTest.py
Split part of test_show_bears into test_show_all_bears, and removed a
redundant assertion.
=> coalaTest: Clean up test_show_bears

coalib/output/ConsoleInteraction.py, tests/output/ConsoleInteractionTest.py
Fixes https://github.com/coala-analyzer/coala/issues/2205
=> ConsoleInteraction: Suggest installing bears

coalib/parsing/Globbing.py, coalib/settings/ConfigurationGathering.py, tests/coalaCITest.py, tests/coalaJSONTest.py, tests/parsing/GlobbingTest.py
Fixes https://github.com/coala-analyzer/coala/issues/2241
=> load_config_file: Note `--save` on no config

coalib/coala.py, coalib/coala_ci.py, coalib/coala_dbus.py, coalib/coala_delete_orig.py, coalib/coala_format.py, coalib/coala_json.py
Fixes https://github.com/coala-analyzer/coala/issues/2206
=> binaries: Allow python -m coalib.... execution

coalib/coala_json.py, coalib/parsing/DefaultArgParser.py
Fixes https://github.com/coala-analyzer/coala/issues/2237
=> DefaultArgParser: Change output metavar to FILE

coalib/parsing/DefaultArgParser.py
Fixes https://github.com/coala-analyzer/coala/issues/2224
This diff is really ugly because of re-ordering a lot of the arguments...
=> DefaultArgParser: Add logical argument groups

coalib/settings/ConfigurationGathering.py
This fixes issues determined by usability testing.
=> ConfigurationGathering: Warn absent config values

coalib/collecting/Importers.py, coalib/misc/Future.py, coalib/parsing/Globbing.py
`scandir` is faster than listdir with pretty much the same API
Closes https://github.com/coala-analyzer/coala/issues/2319
=> Replace listdir with scandir

coalib/bears/Bear.py
This helps maintaining all the attributes
in each Bear, to be able to generate a
setup.py accordingly for each bear.
=> Bear.py: Add attributes for setup.py

docs/Users/Container.rst, docs/index.rst
Closes https://github.com/coala-analyzer/docker-coala-base/issues/9
CC @stefanoco if you want I can set you as author, for that I need your `Full Name <email@addesss>`
=> docs: Add docker container page

coalib/bearlib/abstractions/ExternalBearWrap.py, tests/bearlib/abstractions/external_bear_wrap_testfiles/ExternalBearWrapTest.py, tests/bearlib/abstractions/external_bear_wrap_testfiles/test_external_bear.py, tests/bearlib/abstractions/external_bear_wrap_testfiles/test_file.txt
external_bear_wrap decorator that gets an executable name as argument.
=> ExternalBearWrap: write external_bear_wrap decorator base

docs/Getting_Involved/Testing.rst
Adding information to the Prerequisites about needing python3
Fixes #2359  https://github.com/coala-analyzer/coala/issues/2359
=> Docs: Update Tutorial.rst

docs/Users/Install.rst
updating link to python.org on line 9 to go directly 
to https://www.python.org/downloads/ to download python3
=> Docs: Update install.rst

coalib/bears/Bear.py
Fixes https://github.com/coala-analyzer/coala/issues/2416
=> Bear: Change ``Simplification`` -> ``Redundancy``

coalib/bears/Bear.py
Closes https://github.com/coala-analyzer/coala/issues/2419
=> Bear.py: Add ``Code Simplification``

docs/index.rst
Fixes #2414
Link on side now reads Getting Started with coala
=> Docs: Index.rst Changing Coala to coala

coalib/output/ConsoleInteraction.py, coalib/results/Result.py, tests/output/ConsoleInteractionTest.py, tests/output/dbus/DbusDocumentTest.py, tests/output/dbus/DbusTest.py, tests/processes/ProcessingTest.py, tests/results/ResultTest.py
Closes https://github.com/coala-analyzer/coala/issues/2441
=> show_bear: Show CAN_DETECT and CAN_FIX as well

coalib/parsing/DefaultArgParser.py
Fixes https://github.com/coala-analyzer/coala/issues/2344
=> DefaultArgParser: Eval get_all_bears_names lazy

coalib/bears/Bear.py, docs/Getting_Involved/Writing_Tests.rst, docs/Users/FAQ.rst, docs/Users/Tutorials/Writing_Bears.rst
This is not something that I get offended about, but I think there's just no reason *not* to make this change.
=> docs: Use gender-neutral wording

coalib/coala.py, coalib/collecting/Collectors.py, coalib/output/ConsoleInteraction.py, coalib/parsing/DefaultArgParser.py, tests/coalaTest.py, tests/output/ConsoleInteractionTest.py
Closes https://github.com/coala-analyzer/coala/issues/2431
=> Add ``--show-capabilities``

coalib/results/Diff.py
Closes https://github.com/coala-analyzer/coala/issues/2489
=> Diff.py: changed "doesnt" -> "doesn't"

coalib/parsing/LineParser.py
Fixes https://github.com/coala-analyzer/coala/issues/2496
=> LineParser.py: Change seperate to separate

coalib/misc/CachingUtilities.py
Fix https://github.com/coala-analyzer/coala/issues/2483
=> CachingUtilities: Fix typo nonexist[a->e]nt

README.rst
Including the logo and overhauling the entire README page.
=> README: Update it

coalib/processes/Processing.py
Fixes https://github.com/coala-analyzer/coala/issues/2488
=> Processing: Change succesfully to successfully

coalib/processes/Processing.py
Closes https://github.com/coala-analyzer/coala/issues/2487
=> Processing: Change recieved to received

coalib/output/ConsoleInteraction.py
Fixes https://github.com/coala-analyzer/coala/issues/2546
=> ConsoleInteraction: Print colored output

docs/Users/Tutorials/Linter_Bears.rst, docs/Users/Tutorials/Writing_Bears.rst
Closes https://github.com/coala-analyzer/coala/issues/2548
=> Docs: Add notes on writing bears tutorials

tests/collecting/DependenciesTest.py
We can just use the default Bear class for this.
=> DependenciesTest: Remove BearWithoutDeps

coalib/output/ConsoleInteraction.py, tests/output/ConsoleInteractionTest.py
Fixes https://github.com/coala-analyzer/coala/issues/2557
=> ConsoleInteraction: Print number of missing line

coalib/bearlib/abstractions/Linter.py, tests/bearlib/abstractions/LinterTest.py
This reverts commit 6d96e937d3e026917a6ce2f02a8a9a06698531e4.
Apparently this seems to break things.
=> Revert "Linter: Accept list only on process..."

coalib/output/ConsoleInteraction.py
=> Fix typo, change its -> it is

coalib/output/ConfWriter.py
Fixes https://github.com/coala-analyzer/coala/issues/2485
=> Result: Change seperators -> separators

.misc/deps.sh, coalib/bears/requirements/RscriptRequirement.py, tests/bears/requirements/RscriptRequirementTest.py
Closes https://github.com/coala-analyzer/coala/issues/2571
=> Add RscriptRequirement

coalib/bears/LocalBear.py
closed https://github.com/coala-analyzer/coala/issues/2481
=> LocalBear : fix typo

coalib/output/ConsoleInteraction.py, requirements.txt, tests/output/ConsoleInteractionTest.py
Updated on 08/12/2016: https://asciinema.org/a/82541
=> Syntax highlighting

coalib/results/Result.py, tests/results/ResultTest.py
Fixes https://github.com/coala-analyzer/coala/issues/2605
=> Result.py: Adds condition on confidence in Result

coalib/results/Result.py
Closes https://github.com/coala-analyzer/coala/issues/2604
=> Result.py: Changes :param origin: description

requirements.txt
I need this for the param deprecation :)
=> requirement: Update coala_utils

coalib/results/Result.py
Closes https://github.com/coala-analyzer/coala/issues/2611
=> Result: Remove else condition on self.confidence

docs/Users/FAQ.rst
Fixes https://github.com/coala-analyzer/coala/issues/2472
=> FAQ: Change "docummented" to "documented"

coalib/collecting/Collectors.py
Fixing capitalization in parameter docs.
Fixes https://github.com/coala-analyzer/coala/issues/2506
=> Collectors: Capitalize param docs

coalib/results/Diff.py, tests/results/DiffTest.py
Closes https://github.com/coala-analyzer/coala/issues/2641
=> Diff: Increase `line_nr_end` in `delete_lines`

coalib/collecting/Collectors.py, coalib/misc/Constants.py, requirements.txt, tests/coalaTest.py
Fixes https://github.com/coala-analyzer/coala/issues/2705
=> Collectors: Improve dependency conflict message

.coafile, coalib/processes/Processing.py, coalib/settings/SectionFilling.py, tests/coalaJSONTest.py, tests/coalaTest.py, tests/collecting/CollectorsTest.py, tests/settings/SectionFillingTest.py, tests/test_bears/internal_folder/DependentBear.py
Fixes https://github.com/coala-analyzer/coala/issues/2709
=> Resolve dependencies before filling sections

coalib/output/ConsoleInteraction.py
Fixes https://github.com/coala-analyzer/coala/issues/2652
=> ConsoleInteraction: Sort settings by name

coalib/bearlib/naming_conventions/__init__.py
Fixes https://github.com/coala-analyzer/coala/issues/2694
=> __init__.py: Replace lambdas with returned string

.misc/deps.sh, coalib/bears/requirements/JuliaRequirement.py, tests/bears/requirements/JuliaRequirementTest.py
The install_command method builds the command from its Julia attribute.
The is_installed method checks whether Julia is installed or not.
~~Fixes #2435~~
=> JuliaRequirement: Add installation methods

README.rst
Change website link form http://coala-analyzer.org/ to http://coala.io/
Closes https://github.com/coala-analyzer/coala/issues/2741
=> README: Change website link

CONTRIBUTING.rst
Resolve Newcomer Guide and Good Commits page link
Closes https://github.com/coala-analyzer/coala/issues/2727
=> CONTRIBUTING: Resolve broken links

coalib/misc/Compatability.py
https://github.com/coala-analyzer/coala/issues/2743
=> Remove duplicated function and unify it in compat

setup.py
This will certainly fix the issue with pypi.
=> README: Add `author_email`

circle.yml, coalib/bears/Bear.py, tests/bears/BearTest.py
I changed the -L DEBUG to -V 
Good?
=> change -L DEBUG to -V , issue #2688

README.rst
The version is outdated so we need to update it
Closes https://github.com/coala/coala/issues/2742
=> README: Change version of 0.8.0 to 0.8.1

coalib/__init__.py
The existing help(coalib) command issues a list of packages inside coalib
without any description.Thus a small description of the coalib package
would help.
Fixes https://github.com/coala/coala/issues/1663
=> __init__.py: Add description of coalib.

coalib/output/ConsoleInteraction.py, coalib/results/result_actions/ApplyPatchAction.py, coalib/results/result_actions/OpenEditorAction.py, coalib/results/result_actions/PrintDebugMessageAction.py, coalib/results/result_actions/PrintMoreInfoAction.py, coalib/results/result_actions/ResultAction.py, coalib/results/result_actions/ShowPatchAction.py
Shorten action descriptions for users.
Closes https://github.com/coala/coala/issues/2701
=> Change: Action Descriptions

coalib/results/result_actions/OpenEditorAction.py, coalib/results/result_actions/ShowPatchAction.py
Updated docstring format for two functions in the result_actions directory.
Fixes https://github.com/coala/coala/issues/2779
=> OpenEditorAction and ShowPatchAction: Updated docstring format

coalib/output/ConsoleInteraction.py
Corrected few of the typos in the file and added a document string
to a method.
closes issue https://github.com/coala/coala/issues/2791
=> ConsoleInteraction : Correcting the typos

coalib/output/printers/LogPrinter.py
Fixes issue : https://github.com/coala/coala/issues/2486
=> LogPrinter: Fix "occured"->"occurred"

coalib/bears/requirements/GoRequirement.py, coalib/bears/requirements/NpmRequirement.py, coalib/parsing/Globbing.py, tests/bears/requirements/GoRequirementTest.py, tests/bears/requirements/NpmRequirementTest.py, tests/collecting/CollectorsTest.py
=> Fix ALL the things

coalib/output/ConsoleInteraction.py
fixed typo by changing od to of
Closes https://github.com/coala/coala/issues/2812
=> ConsoleInteraction.py Fix typo od->of

coalib/testing/BearTestHelper.py, coalib/testing/LocalBearTestHelper.py, tests/coalaJSONTest.py, tests/coalaTest.py, tests/collecting/CollectorsTest.py, tests/test_bears/TestBear.py, tests/testing/LocalBearTestHelperTest.py
bears should be testeable without coala-bears
Fixes https://github.com/coala-analyzer/coala-bears/issues/488
=> TestHelpers: Move from coala-bears to coala

ISSUE_TEMPLATE
This is how it would appear when someone is on the new-issue page:
Please comment if you feel there could be improvements. Otherwise consider for merging.
=> add ISSUE_TEMPLATE file. Fixes #2735

coalib/output/ConsoleInteraction.py
Closes https://github.com/coala/coala/issues/2836
=> Change afected->affected

README.rst
I guess the placement is appropriate for the section Awards. Different Awards section is needed as if any other awards adds up.
=> README.rst: Add yegor256.com #2924

coalib/testing/LocalBearTestHelper.py
[Please see this for a tutorial.](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing)
[commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html)
and I've followed them:
[guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
commit fixes a *real bug* and the `Closes` keyword if it adds a
feature/enhancement.
[See more here.](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference)
[guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
and they all pass. If any CI (below) is not green, please fix them. If
GitMate issues appear you will have to amend your commits, pushing new
commits on …
=> LocalBearTestHelper.py: Allow to pass bear setting

.gitignore, circle.yml, docs-requirements.txt, docs/.gitignore, docs/conf.py, docs/index.rst, docs/make.bat, setup.py
[Please see this for a tutorial.](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing)
[commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html)
and I've followed them:
[guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
[guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
commit fixes a *real bug* and the `Closes` keyword if it adds a
feature/enhancement.
[See more here.](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference)
and they all pass. If any CI (below) is not green, please fix them. If
GitMate issues appear you will have to amend your commits, pushing new
commits on …
=> Set up sphinx-apidoc to generate API docs

PULL_REQUEST_TEMPLATE.md
[Please see this for a tutorial.](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing)
[commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html)
and I've followed them:
[guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
[guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
commit fixes a *real bug* and the `Closes` keyword if it adds a
feature/enhancement.
[See more here.](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference)
and they all pass. If any CI (below) is not green, please fix them. If
GitMate issues appear you will have to amend your commits, pushing new
commits on …
=> Revise pull request template

coalib/coala_ci.py, coalib/coala_json.py, coalib/coala_main.py, coalib/processes/Processing.py, coalib/settings/ConfigurationGathering.py, tests/coalaCITest.py, tests/processes/ProcessingTest.py, tests/settings/ConfigurationGatheringTest.py
Fixes https://github.com/coala/coala/issues/1526
=> coala_ci: Enable autoapply

README.rst
Removed ``as the installation may not succeed with lower versions``
as it was redundant
Closes https://github.com/coala/coala/issues/2980
=> README.rst: Remove redundant line

coalib/parsing/LineParser.py
Edited the param explanations to begin with a
capital letter and end with a dot.
Closes https://github.com/coala/coala/issues/2983
=> LineParser.py: Edit docstring

coalib/coala.py, coalib/coala_ci.py, coalib/coala_main.py, coalib/output/ConsoleInteraction.py, coalib/parsing/DefaultArgParser.py, coalib/processes/Processing.py, tests/output/ConsoleInteractionTest.py, tests/processes/ProcessingTest.py
[Please see this for a tutorial.](http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#rebasing)
[commit guidelines](http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html)
and I've followed them:
[guidelines for the commit shortlog](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog).
[guidelines for the commit body](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#commit-body).
commit fixes a *real bug* and the `Closes` keyword if it adds a
feature/enhancement.
[See more here.](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#issue-reference)
and they all pass. If any CI (below) is not green, please fix them. If
GitMate issues appear you will have to amend your commits, pushing new
commits on …
=> Output: Ability to disable colour output

coalib/settings/ConfigurationGathering.py
To ``get_filtered_bears``. This is useful if another program
wants to use ``get_filtered_bears``.
Closes https://github.com/coala/coala/issues/3012
=> ConfigurationGathering: Add `arg_parser` param

README.rst
=> README: update pip prerequisite

coalib/coala.py, coalib/coala_ci.py, coalib/coala_format.py, coalib/coala_json.py, coalib/coala_modes.py, coalib/parsing/CliParsing.py, coalib/parsing/DefaultArgParser.py, tests/coalaCITest.py, tests/coalaFormatTest.py, tests/coalaJSONTest.py, tests/parsing/CliParsingTest.py
Closes https://github.com/coala/coala/issues/2279
=> Unite outputs to one binary

coalib/bearlib/languages/definitions/CPP.py
=> definitions/CPP: Use dict, not set

coalib/bearlib/aspects/__init__.py, coalib/bearlib/aspects/base.py, coalib/bearlib/aspects/meta.py, coalib/bearlib/aspects/taste.py, coalib/bearlib/languages/Language.py, coalib/results/Result.py, tests/bearlib/aspects/BaseTest.py, tests/bearlib/aspects/InstanceTest.py, tests/bearlib/aspects/RootTest.py, tests/bearlib/aspects/SubTest.py, tests/bearlib/aspects/TasteTest.py, tests/bearlib/aspects/conftest.py, tests/processes/ProcessingTest.py
=> Make aspectclass instances depend on a language

README.rst
Formatting error at line 193 has been fixed by adding a newline.
This should fix the pypi display
Fixes https://github.com/coala/coala/issues/3078
=> README.rst: Fix formatting error

.misc/deps.nltk.sh, .misc/deps.sh, circle.yml
GitCommitBear currently emits the error:
NLTK data missing, install by running following commands
`python3 -m nltk.downloader punkt .. averaged_perceptron_tagger`
=> Add nltk-data to CircleCI build

coalib/bearlib/languages/Language.py, docs/index.rst
=> Language: Add suggestive assert

circle.yml, setup.py
Removes duplicate code
closes https://github.com/coala/coala/issues/3075
=> circle.yml: Use ./setup.py docs

coalib/misc/CachingUtilities.py
=> CachingUtilities: Ignore default values

coalib/bears/Bear.py, tests/bears/BearTest.py
Since download_cached_file wasn't covered anymore,
added a test to cover it.
Fixes https://github.com/coala/coala/issues/3110
=> BearTest.py: Add test_download_cached_file

setup.py
They can still be bulit via
./setup.py build_manpage
Closes https://github.com/coala/coala/issues/1694
=> setup.py: Dont build manpages on Windows

requirements.txt
Temporary hotpatch to enable building again. Version 29
breaks windows building because it fails to include
cli-xx.exe.
=> requirments.txt: Pin back setuptools version

circle.yml, coalib/bears/Bear.py, requirements.txt, setup.py, test-requirements.txt, tests/bears/BearTest.py
Backport the test fixes for Bear.py to coala 0.9 to enable docker image build. We have no idea when this test started failing, only that it did.
@underyx 
@sils
=> Backport bear test fix

README.rst
It shows proper version.
Fixes https://github.com/coala/coala/issues/3099
=> README.rst: Update version badge

requirements.txt
Reverted hotpatch becuase upstream has updated and it
works now.
Closes https://github.com/coala/coala-bears/issues/1062
=> requirements.txt: Revert hotpatch

setup.cfg, test-requirements.txt
Add [tool:pytest] becuase [pytest] deprecated and conflicts
with pytest in disutils.
Fixes https://github.com/coala/coala/issues/3097
=> setup.cfg: Change [pytest] to [tool:pytest] on line 5

requirements.txt, test-requirements.txt
I wrote a tiny script that sorts the entries alphabetically (ignoring case)
requirements.txt and test-requirements.txt are sorted using the script.
The script is at https://github.com/Mariatta/requirements_atoz, in case it might be needed again in the future :)
Sort the entries in requirements.txt and test-requirements.txt alphabetically, ignoring case.
Closes https://github.com/coala/coala/issues/3138
=> Sort requirements.txt and test-requirements.txt

docs/Developers/Writing_Good_Commits.rst
Ensures that "More Examples" has font size of a subheading.
Replaces - with ~.
Fixes http://github.com/coala/coala/issues/3139
=> Writing_Good_Commits.rst: Change font size

coalib/settings/ConfigurationGathering.py
Fixes https://github.com/coala/coala/issues/3135
=> ConfigurationGathering: Add suppress instructions

coalib/bearlib/languages/__init__.py, coalib/bearlib/languages/definitions/Unknown.py
This language definition is to be used when language is not known.
It was requested on https://github.com/coala/coala-bears/pull/1100
=> Language: Add Unknown language

requirements.txt
needed so 0.9.1 the release can be made.
=> BACKPORT: requirements.txt: Revert setuptools 29.0 hotpatch NEEDED for 0.9.1 release

requirements.txt
Fixes https://github.com/coala/coala-bears/issues/751
=> Remove setuptools from requirements.txt

circle.yml, coalib/bearlib/__init__.py, coalib/bearlib/abstractions/Linter.py, coalib/parsing/Globbing.py, docs-requirements.txt, docs/Developers/Newcomers_Guide.rst, docs/Developers/Writing_Tests.rst, requirements.txt
Fixes https://github.com/coala/coala/issues/3199
=> Writing_Tests: Correct "Executing Tests" reference

.travis.yml
Uses ppa:staticfloat/juliareleases for Julia.
Uses Travis apt addon for R and clang.
Closes https://github.com/coala/coala/issues/3191
=> Basic Travis CI precise build script

coalib/coala_main.py
Fixes https://github.com/coala/coala/issues/3016
=> coala_main.py: Add param doc for 'arg_parser'

coalib/results/Diff.py, tests/results/DiffTest.py
Add a function, add_line, to add a line after a line number
Fixes https://github.com/coala/coala/issues/2649
=> Diff: Implement function add_line

docs/Developers/Newcomers_Guide.rst
Added survey link http://coala.io/newform
Closes https://github.com/coala/coala/issues/3142
=> Newcomers_Guide.rst: Add survey link

README.rst
Update Newcomer guide link from :
http://coala.readthedocs.io/en/latest/Developers/Newcomers_Guide.html
to :
http://coala.io/newcomer
Fixes #3232
=> Update newcomer_guide link

docs/Developers/Newcomers_Guide.rst
Mention that newcomers should not work on master branch.
Add instruction on how to create a branch.
Closes https://github.com/coala/coala/issues/3148
=> Advise newcomers to work on branch

docs/Developers/Writing_Good_Commits.rst
Closes https://github.com/coala/coala/issues/3257
=> Writing_Good_Commits.rst: Remove extra "and"

docs/Developers/Newcomers_Guide.rst
Specify a hyperlink to myfork.
Fixes https://github.com/coala/coala/issues/3293
=> Newcomers_Guide.rst: Review Process clearer

coalib/bearlib/languages/Language.py, tests/bearlib/languages/LanguageTest.py
=> LanguageMeta: Add __dir__ for lang auto-completion

coalib/collecting/Collectors.py, tests/collecting/CollectorsTest.py
Need it for https://github.com/coala/bearsh
@sils
=> Collectors: Add separate get_all_bears function

coalib/bearlib/languages/Language.py, tests/bearlib/languages/LanguageTest.py
Fixes https://github.com/coala/coala/issues/3160
=> Language.py: Raise AttributeError in __getattr__ 

docs-requirements.txt, docs/Developers/coala_settings.rst, docs/conf.py, docs/index.rst
Adds the required module for the documentation page to work.
docs/Developers/Documentation_coala_Settings.rst: Adds the documentation page
Uses the module installed to generate the documentation page
using the default_arg_parser function.
docs/conf.py: Adds the extension
Adds the extension for sphinx in the configuration file
docs/index.rst:Adds Doc page in index
Adds the documentation page in the index file so it appears.
Fixes: https://github.com/coala/documentation/issues/40
=> docs-requirements.txt: Adds sphinx-argparse

tests/processes/ProcessingTest.py
The " quotation marks have been changed to ' marks
to maintain consistency.
Fixes: https://github.com/coala/coala/issues/3343
=> Inconsistencies in quotation marks

docs/Developers/Review.rst
New indentation of block 5 of the file as it
considered block 6 to be the start of a new
list
Fixes https://github.com/coala/coala/issues/3249
=> Review.rst: Indent correctly Review file

docs/Developers/Newcomers_Guide.rst
Fixes https://github.com/coala/coala/issues/3239
=> fix: Edit links in Newcomers_Guide.rst

.coafile, .misc/deps.sh
Add section text applying SpaceConsistencyBear to
many miscellaneous text files, and fixing one case
of trailing whitespace.
Closes https://github.com/coala/coala/issues/3361
=> .coafile: Enforce space consistency on more files

setup.py
coalib/bearlib/languages/definitions/ no longer contains any data.
Closes https://github.com/coala/coala/issues/3363
=> setup.py: Delist directory with no package data

coalib/coala_main.py, coalib/coala_modes.py, tests/coalaTest.py
https://github.com/coala/coala/issues/3212
=> https://github.com/coala/coala/issues/3212

coalib/parsing/DefaultArgParser.py, docs/Developers/Newcomers_Guide.rst
This ensures the asterisk is bypassed in the docstring.
Fixes https://github.com/coala/coala/issues/3334
=> Fix rst problems in sphinx

coalib/output/ConsoleInteraction.py, tests/output/ConsoleInteractionTest.py
=> ConsoleInteraction.py: Restore format_str

.travis.yml, setup.cfg, test-requirements.txt
Fixes https://github.com/coala/coala/issues/3383
=> setup.cfg: Build wheel for Python 3.4-3.6 only

setup.py
This ensures that exit code is same as the error code of a failed build.
Fixes: https://github.com/coala/coala/issues/3333
=> setup.py: Return exitcode on docs error

docs/Developers/Git_Basics.rst
This section will help newcomers sort basic git issues.
Fixes: https://github.com/coala/coala/issues/3140
=> Git_Basics.rst: Add 'Common Git Issues' section

docs/Developers/Development_Setup.rst
Updates 'Installing from Git' section:
This updates the code in the 'Installing from Git' section with the 
proper one.
Closes https://github.com/coala/documentation/issues/364
=> Docs/Developers/Development_Setup.rst: Update installation section

coalib/output/ConsoleInteraction.py, coalib/parsing/DefaultArgParser.py, coalib/results/SourceRange.py
=> coalib: Fix affected_code placeholder render

README.rst
Change back badge image url to readthedocs
Fixes https://github.com/coala/coala/issues/3437
=> Fix documentation status badge

.misc/deps.sh, .travis.yml
=> CI: Remove Julia, R, Node, etc

coalib/parsing/DefaultArgParser.py
- use short url
- highlight the command line code
Fixes https://github.com/coala/coala/issues/3449
=> Improve text formatting in coala settings docs

.coafile, coala, coalib/bearlib/abstractions/ExternalBearWrap.py, coalib/bearlib/languages/Language.py, coalib/coala.py, coalib/coala_main.py, coalib/collecting/Collectors.py, coalib/parsing/ConfParser.py, coalib/settings/FunctionMetadata.py, coalib/settings/SectionFilling.py, setup.py, tests/bearlib/abstractions/external_bear_wrap_testfiles/test_external_bear.py, tests/coalaTest.py, tests/collecting/importers_test_dir/file_one.py, tests/results/SourcePositionTest.py
Adds PycodestyleBear in the autopep8 section and fixes the issues
discovered by the new bear.
Closes https://github.com/coala/coala/issues/3242
=> .coafile: Add PycodestyleBear

coalib/results/result_actions/OpenEditorAction.py, tests/results/result_actions/OpenEditorActionTest.py
This commit extends the OpenEditorAction to open
files at the line and column of the affected code,
if applicable and if the chosen editor supports it.
To determine if and how an editor supports lines
and columns, we keep a list of known editors,
which can easily be extended.
Closes https://github.com/coala/coala/issues/2698
=> OpenEditorAction: Open files at position

coalib/output/ConsoleInteraction.py
Add param docs to all the functions, with appropiate
function description and parameter description.
Closes #3452
@adtac
=> ConsoleInteraction.py: Add param docs for methods

docs/Developers/Writing_Linter_Bears.rst
=> Add a link of linter API documentation for resolve issue #3408

RELEASE_NOTES.rst
(cherry picked from commit a60b5767b7faea0346e3c0258230d9ea5b2d2694)
=> Forward port of RELEASE_NOTES from release 0.9.1

docs/Developers/Development_Setup.rst, docs/Developers/Newcomers_Guide.rst
=> Fixes #3460

requirements.txt
Update dependency_management from `0.1.7` to `0.2.0`
Closes #3484
=> requirements.txt: Update dependency_management version

coalib/parsing/DefaultArgParser.py
The --output option is used to write the results
into the given file, not the logs.
Closes https://github.com/coala/coala/issues/3475
=> DefaultArgParser: Modify help string

docs/Developers/Newcomers_Guide.rst
Fixes #3481 
Signed-off-by: Ce Gao <ce.gao@outlook.com>
=> Newcomers_Guide.rst: fix a link typo

coalib/output/ConfWriter.py, tests/output/ConfWriterTest.py
Added code to ConfWriter.py, which checks if the param given to
`-c` is a dir or not, if it is a dir then it adds `/.coafile` to
it. 
Also added tests to ConfWriterTest.py to test it with a
dir. 
Test: 
```
MBPs-MacBook-Pro:coala rhemon$ pytest tests/output/ConfWriterTest.py 
================================================================= test session starts ==================================================================
platform darwin -- Python 3.5.2, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
rootdir: /Users/mbp13inch/Documents/Workspace/coala, inifile: setup.cfg
collected 4 items 
tests/output/ConfWriterTest.py ....
=============================================================== 4 passed in 1.11 seconds ===============================================================
```
Fixes …
=> ConfWriter.py: Check if param for -c is dir

.coafile, docs/_static/custom.css
=> Fix docs/_static/custom.css file lint errors

coalib/bears/Bear.py
Closes https://github.com/coala/coala/issues/3038
=> Bear.py: Remove set_up/tear_down paragraph from doc comment

README.rst, docs/Developers/Review.rst
=> docs: Update review documentation

docs/Developers/Writing_Documentation.rst
As most of the coala documentation is written in rst
documents, a link to a tutorial on how to actually
do that is added in the document.
Closes https://github.com/coala/coala/issues/3521
=> Writing_Documentation.rst: Adds rst tutorial

requirements.txt
Updated the version used right now since there was a fix
in dependency management and got a new release. Also
changed coala-utils version to 0.6, after seeing error
in the tests.
=> Requirements.txt: dependency_management 0.3.0

coalib/output/ConsoleInteraction.py
Move join_names method to coala_utils/string_processing
Closes #3486
@sils
=> ConsoleInteraction.py: Move join_names to gitlab

RELEASE_NOTES.rst, docs/Developers/External_Bears.rst, docs/Developers/Newcomers_Guide.rst, docs/Developers/Writing_Linter_Bears.rst, docs/Developers/Writing_Native_Bears.rst, docs/index.rst
=> writing_Native_Bears.rst: Change in file name

coalib/settings/ConfigurationGathering.py
Fixes https://github.com/coala/coala/issues/3395
=> ConfigurationGathering.py

coalib/bearlib/languages/definitions/CSharp.py
This commit add fields string_delimiters and comment_delimiters
Fixes https://github.com/coala/coala/issues/3514
=> CSharp.py:Add fields for CSharp lang support

docs/Developers/Newcomers_Guide.rst
Note is changed in order to emphasis more on
solving difficulty/low issue and start reviewing.
Closes coala#3250
=> Newcomers_Guide.rst: Change in note

.coafile
Closes https://github.com/coala/coala/issues/3585
=> coafile: Change python3 to python 3

coalib/bearlib/languages/Language.py
Added a new strip() method to
the parse_lang_str function's
try statement to eliminate whitespace
Closes https://github.com/coala/coala/issues/3068
=> Language.py: Ignore whitespace in lookup

docs/Developers/Newcomers_Guide.rst, docs/Developers/Useful_Links.rst, docs/index.rst
Especially for newcomers there was an issue about
their orientation through the site in terms of finding
specific materials that can help them. Adds a new page
with the most useful stuff from a newcomer`s perspective.
Edits the index file from the root folder so that the
document can be added to the page.
Closes https://github.com/coala/coala/issues/3515
=> Useful_Links.rst: Adds new page

docs/Developers/Newcomers_Guide.rst, docs/_static/custom.css, docs/index.rst
Closes https://github.com/coala/coala/issues/3551
=> Add link to Code of Conduct to docs

coalib/bears/Bear.py, coalib/output/ConsoleInteraction.py, tests/output/ConsoleInteractionTest.py
The absolute path of the bear will be shown
with the show-details argument.
Closes https://github.com/coala/coala/issues/2663
=> ConsoleInteraction.py: Show file path of bear

PULL_REQUEST_TEMPLATE.md
Pull template: Add branch button warning
PULL_REQUEST_TEMPLATE.md now contains a warning about
the 'Update Branch' button
Closes https://github.com/coala/coala/issues/3406
=> Pull template: Add branch button warning

requirements.txt
Resolves a dep conflict with bears.
=> requirements.txt: Make requests version match properly

requirements.txt
=> Add deps fix to the 0.10 branch

coalib/misc/Shell.py
=> Remove call_without_output from Shell.py L7

.coafile, coalib/bears/Bear.py, coalib/processes/BearRunning.py
Reverts https://github.com/coala/coala/issues/3587 , and fixes https://github.com/coala/coala/issues/3660
=> Remove bare except

coalib/misc/Shell.py
@sils @justuswilhelm Continuation of https://github.com/coala/coala/pull/3678
=> Shell: Use shutil.which on Windows

RELEASE_NOTES.rst
=> RELEASE_NOTES: Add 0.10 release notes

RELEASE_NOTES.rst
=> RELEASE_NOTES: Fix malformed heading

docs/Developers/Writing_Good_Commits.rst
Removed "it is obvious that"
Closes https://github.com/coala/coala/issues/3260
=> Writing_Good_Commits.rst: Rephrase Line

coalib/bearlib/aspects/Redundancy.py
in line-98: coalib/bearlib/aspects/Redundancy.py
Closes https://github.com/coala/coala/issues/3684
=> Redundancy: Changed 'deco' to 'docs'

circle.yml
Add csslint to circle-ci
Closes https://github.com/coala/coala/issues/3707
them. …
=> circle.yml: Add csslint

coalib/output/Logging.py
Removes duplicate import statement
Closes https://github.com/coala/coala/issues/3592
=> logging.py: Remove unnecessary import

.misc/appveyor.yml, .misc/deps.sh, .misc/env_variables.sh, .misc/tests.sh, coalib/parsing/Globbing.py, coalib/processes/Processing.py, setup.cfg, test-requirements.txt
Adds clang to Appveyor (https://github.com/coala/coala/issues/3553) and use funky pragmas to ensure Windows code is properly tested (https://github.com/coala/coala/issues/3715)
=> Appveyor 100%

docs/Developers/Adding_CI.rst, docs/index.rst
Creates Adding_CI.rst file in docs/Developers that contains
instructions to add CI tools, that are used in coala, to the
forked repository.
Closes https://github.com/coala/coala/issues/3664
=> Instructions to add CI to fork

coalib/parsing/DefaultArgParser.py
**DefaultArgParser.py:** Change order of logging to DEBUG/INFO/WARNING/ERROR
Closes https://github.com/coala/coala/issues/3617
=> DefaultArgParser.py: Change order of logging

coalib/bears/Bear.py, tests/bears/BearTest.py
Mentions the absolute path of the file on which
the local bear failed
Closes https://github.com/coala/coala/issues/2693
=> Bear.py: Include filename on which the bear failed

docs/Developers/Writing_Good_Commits.rst
Drop the word 'only' from the statement 'It should
describe only one change and not more.'.
Closes https://github.com/coala/coala/issues/3258
them. …
=> Writing_Good_Commits.rst: Reword line

docs/Developers/Writing_Good_Commits.rst
Documentation linked to Git_Basics.rst to explain the procedure.
Closes https://github.com/coala/coala/issues/3747
them. …
=> Writing_Good_Commits.rst: Edit Commit Messages

docs/Developers/Development_Setup.rst
Fix newcomers' guide link in
the Repositories section on line
23
Closes https://github.com/coala/coala/issues/3716
them. …
=> Development_Setup.rst: Fix link

.misc/appveyor.yml
Replaces five pip commands performing custom caching
with one command which uses pip's inbuilt caching.
=> AppveyorCI: Use pip caching

docs/Developers/Writing_Good_Commits.rst
This helps to avoid errors when newcomers directly
copy commit messages on solving issues that are
not bugs.
Closes https://github.com/coala/coala/issues/3737
them. …
=> Writing_Good_Commits.rst: Fixes to Closes

docs/Developers/Git_Basics.rst
This example explains how to install git on a MacOS system using homebrew.
Closes https://github.com/coala/coala/issues/3256
them. …
=> Developers/Git_Basics.rst: Add example for MacOS

tests/bears/BearTest.py
This test shows that a file is created and
still exists after a corrupted download.
Related to https://github.com/coala/coala-bears/issues/1461
Closes https://github.com/coala/coala/issues/3820
=> BearTest: Test exception during HTTP fetch

coalib/core/Bear.py, tests/core/BearTest.py
Part 1 - from https://github.com/coala/coala/pull/3523
=> core: Add Bear v2

coalib/bears/Bear.py
Fixes https://github.com/coala/coala/issues/3811
=> Bear.download_cached_file: Set chunk_size=16Kb

coalib/settings/Section.py
Sectio.py: Removed redundant code
Removed redundant return statements from nested if Body
Fixes Issue #3822
=> Section.py: Remove redundant lines

coalib/bearlib/abstractions/Linter.py
Changed parsed to passed
Closes https://github.com/coala/coala/issues/3850
them. …
=> Linter.py: Correction of typo

docs/Developers/Testing_Bears.rst
The settings param is passed as a separate param to check_results.
It should be moved out of the list.
Closes https://github.com/coala/coala/issues/3859
them. …
=> Testing_Bears.rst: Update example 3

.misc/check_setuptools.py, .travis.yml, requirements.txt, test-requirements.txt
Fixes https://github.com/coala/coala/issues/3745 and https://github.com/coala/coala/issues/3748
=> Pin minimum pip & setuptools

coalib/misc/DictUtilities.py
defaultdict is more useful in this use-case.
we don't have to check whether it is None or not.
Also now, we can remove add_pair_to_dict method.
Closes https://github.com/coala/coala/issues/3898
them. …
=> misc/DictUtilities.py: Use defaultdict

docs/Developers/Writing_Linter_Bears.rst
Changed rcfile to pylint_rcfile.
Closes https://github.com/coala/coala/issues/3911
them. …
=> Writing_Linter_Bears.rst: Fix a typo

docs/Developers/Newcomers_Guide.rst
Mention that the only way to familiarise yourself with the codebase is to practice and take up new issues.
Fixes #3926
them. …
=> docs: update newcomer guide

coalib/bearlib/aspects/meta.py
=> aspects/meta.py: Fixed typo error

coalib/results/Diff.py, tests/results/DiffTest.py
Prevent out of range deletion in Diff.
Raise error in case of out of range deletion.
Fixes https://github.com/coala/coala/issues/3782
them.
When asked …
=> Diff: Prevent invalid deletion

docs/Developers/Git_Basics.rst
Tell people to run coala before pushing.
Closes https://github.com/coala/coala/issues/3874
them. …
=> Git_Basics.rst: Add "Run coala" section

coalib/output/ConsoleInteraction.py, tests/output/ConsoleInteractionTest.py
Bears are now displayed alphabetically case-insensitive.
Closes https://github.com/coala/coala/issues/3941
them. …
=> ConsoleInteraction.py: Change bears list order

docs/Developers/Newcomers_Guide.rst
Closes https://github.com/coala/coala/issues/3619
them.
instead.
Please …
=> Newcomers_Guide.rst: Correct grammatical errors

docs/_static/custom.css
=> custom.css: Decrease font size of toctree

coalib/bearlib/__init__.py
Add support for multiple deprecations of the
same setting.
Closes https://github.com/coala/coala/issues/3537
=> deprecate_settings: Allow multiple deprecations

.misc/deploy.pypi.sh
Added checks for script to fail
gracefully when twine throws error 500
Closes #3644
=> deloy.pypi.sh: Pypi upload fail only for error 500

tests/bears/BearTest.py
Closes https://github.com/coala/coala/issues/3823
=> BearTest.py: replace hrml with html

tests/bearlib/aspects/InstanceTest.py, tests/bearlib/aspects/SubTest.py, tests/bearlib/aspects/TasteTest.py
Move closing braces to the the same line as the end of
block/condition, as is the general codestyle of coala
Closes #3931
them. …
=> tests/aspects: Change the position of end braces

coalib/bears/Bear.py
Fixes https://github.com/coala/coala/issues/3978
them.
instead.
Please …
=> Bear.py: Add SEE_MORE attribute

docs/Developers/Writing_Native_Bears.rst
It adds SEE_MORE attribute in writing native bears tutorial.
Closes https://github.com/coala/coala/issues/4027
them. …
=> Writing_Native_Bears.rst: Add SEE_MORE attribute

coalib/bearlib/aspects/meta.py, tests/bearlib/aspects/ClassTest.py
This function helps to determine whether or not
an aspect is a subaspect of another one.
Closes https://github.com/coala/coala/issues/3977
=> Add issubaspect function

coalib/bearlib/aspects/Spelling.py
Add aspects for the aspectsYEAHBear
Closes https://github.com/coala/coala/issues/4040
them. …
=> Add aspect `aspectsYEAH`

docs/Developers/Git_Basics.rst
The note tells a newcomer to look for more commands in their favourite search engines.
Closes https://github.com/coala/coala/issues/3971
them.
When …
=> Git_Basics.rst: Add a note

docs/Developers/Git_Basics.rst, docs/Developers/Newcomers_Guide.rst
Git_Basics.rst: Reinforces to contact on gitter
Reinforcement over PR closing and contacting at gitter in case of issue.
Closes #4050
them.
When asked …
=> Newcomers_Guide.rst: Reinforces not to close PR

coalib/bearlib/languages/documentation/DocumentationComment.py
Remove parameter descriptions for language and docstyle.
Add parameter description for docstyle_definition.
Closes https://github.com/coala/coala/issues/3998
them. …
=> DocumentationComment: Correct docstring parameters

README.rst
We have lots of duplication between the readme and the website. The
website is properly maintained and *way* better but users don't visit it
and get stuck and confused in the readme (found during usability
testing). Let's primarily get them to visit coala.io!
them.
likely receive a lot of bot comments and build failures if coala …
=> Minify README

.coafile, coalib/bearlib/abstractions/ExternalBearWrap.py, coalib/bearlib/languages/__init__.py, coalib/bears/Bear.py, coalib/settings/Section.py, tests/bearlib/abstractions/external_bear_wrap_testfiles/ExternalBearWrapTest.py, tests/bearlib/aspects/ClassTest.py, tests/bearlib/aspects/InstanceTest.py, tests/bearlib/aspects/conftest.py, tests/settings/ConfigurationGatheringTest.py, tests/test_bears/TestBear.py
Adds python_import section to check non-builtin unused imports.
Adds ignore PyUnusedCodeBear to non-builtin imports as required
Removes unused import where necessary
Closes https://github.com/coala/coala/issues/2994
them.
After you …
=> .coafile: Add python_import section

README.rst
=> README: Use properly sized image

coalib/bearlib/aspects/__init__.py, coalib/bearlib/aspects/collections.py, coalib/bearlib/aspects/meta.py, tests/bearlib/aspects/ClassTest.py, tests/bearlib/aspects/CollectionsTest.py
Functions ``isaspect`` and ``assert_aspect`` to check and raise errors
for invalid instances of aspectclasses.
Closes https://github.com/coala/coala/issues/4099
them. …
=> aspects: Check and raise error for invalid aspect

coalib/bearlib/abstractions/Linter.py, coalib/results/Diff.py, docs/Developers/Writing_Linter_Bears.rst, requirements.txt, tests/bearlib/abstractions/LinterTest.py, tests/results/DiffTest.py
=> Add output format `unidiff` to Linter

requirements.txt
Closes https://github.com/coala/coala/issues/4064
=> requirements.txt: Use dependency_management 0.4

coalib/processes/Processing.py, tests/processes/section_executor_test_files/ProcessingGlobalTestBear.py, tests/processes/section_executor_test_files/ProcessingLocalTestBear.py
Related to https://github.com/coala/coala/issues/4166
=> Remove four unnecessary use of pragma: no cover

coalib/results/Diff.py, tests/results/DiffTest.py
A property Diff.has_changes is introduced.
Returns True if the modified file is different from original file.
Otherwise returns False.
Closes https://github.com/coala/coala/issues/3790
them. …
=> Diff.py: Add new property to Diff

docs/Developers/Writing_Linter_Bears.rst
Create a link for `@linter` in the first paragraph of the `Linter Bears`
page.
Closes https://github.com/coala/coala/issues/3819
them.
=> Writing_Linter_Bears.rst: Add API link for @linter

coalib/core/DependencyTracker.py, coalib/core/Graphs.py, docs-requirements.txt
=> update sphinx version in docs-requirements.txt

coalib/collecting/Collectors.py, coalib/processes/Processing.py, tests/collecting/CollectorsTest.py
The new message suggests users to remove unmatched files from their
.coafile. This feedback is more explicit and  can help to avoid user
confusion.
Closes https://github.com/coala/coala/issues/4146
them. …
=> Globs: Change Glob-not-found warning

docs/Developers/Executing_Tests.rst, docs/Developers/Writing_Tests.rst
Fixes https://github.com/coala/coala/issues/4189
them.
instead.
Please …
=> docs: Replace py.test with pytest

coalib/settings/Setting.py, tests/settings/SectionTest.py, tests/settings/SettingTest.py
Fixes https://github.com/coala/coala/issues/4202
=> Setting: Enforce constructor signature

coalib/settings/Section.py
This commit was coauthored by Maximilian Scholz.
Fixes https://github.com/coala/coala/issues/4182
them. …
=> set_default_section: Handle casing properly

coalib/results/result_actions/OpenEditorAction.py
=> Add Support Neovim Code Editor

coalib/collecting/Dependencies.py, coalib/core/CircularDependencyError.py, coalib/core/DependencyTracker.py, coalib/core/Graphs.py, tests/collecting/DependenciesTest.py, tests/core/CircularDependencyErrorTest.py
Closes https://github.com/coala/coala/issues/4191
=> Merge CicularDependencyError classes

coalib/testing/LocalBearTestHelper.py, tests/test_bears/TestBear.py, tests/testing/LocalBearTestHelperTest.py
=> Add LocalBearTestHelper.check_line_result_count()

docs/Developers/Writing_Good_Commits.rst
Closes https://github.com/coala/coala/issues/3244
=> Writing_Good_Commits: Improve why we limit length

.coafile
This commit disables E303 message since it is already
covered by pep8bear.
Closes https://github.com/coala/coala/issues/3556
them. …
=> coafile: Disable E303 for PycodeStyleBear

docs/Developers/Newcomers_Guide.rst
Introducing Gitter and cobot to the newcomer user.
I used some of the content in #4028 
Fixes #3958 
them. …
=> Newcomers_Guide.rst: Add Introduction to Gitter

coalib/coala.py, coalib/output/Logging.py, tests/coalaTest.py
Fixes https://github.com/coala/coala/issues/4185
them.
instead.
Please …
=> no_color: Fix coloring bug in --no-color option

coalib/bearlib/languages/documentation/DocumentationExtraction.py, tests/bearlib/languages/documentation/DocumentationExtractionTest.py, tests/bearlib/languages/documentation/documentation_extraction_testdata/data.py
Fix diff's cut-off bug.
Fixes https://github.com/coala/coala/issues/4187
them. …
=> DocumentationExtraction: diff cut-off fix

.travis.yml, circle.yml, tests/bears/BearTest.py
Workarounds for https://github.com/coala/coala/issues/4277, https://github.com/coala/coala/issues/4280 and https://github.com/coala/coala/issues/4282 .
One of the commits can be removed if https://github.com/Kuniwak/vint/pull/217 is merged.
Another is https://github.com/sphinx-doc/sphinx/issues/3814
=> Fix may28 breakages

.travis.yml, circle.yml
This reverts commit 638bff9cd85bedb7e2e8c6184b41f547eca4f97c.
=> Revert "CI: Workaround requests un-vendoring of chardet"

README.rst, docs/Developers/Development_Setup.rst
Picked https://github.com/coala/coala/pull/4148 , https://github.com/coala/coala/pull/4274 and https://github.com/coala/coala/pull/4268
=> Post requests cherry picks

coalib/results/Diff.py, tests/results/DiffTest.py, tests/results/ResultTest.py
=> Diff.py: Add newlines to outward representation

coalib/bearlib/aspects/Spelling.py
Please propose better names for this aspect.
Closes https://gitlab.com/coala/GSoC-2017/issues/236
=> aspects/Spelling: Add coalaCorrect

coalib/bearlib/languages/documentation/DocstyleDefinition.py, coalib/bearlib/languages/documentation/DocumentationComment.py, coalib/bearlib/languages/documentation/default.coalang, coalib/bearlib/languages/documentation/doxygen.coalang, tests/bearlib/languages/documentation/DocstyleDefinitionTest.py, tests/bearlib/languages/documentation/DocumentationCommentTest.py, tests/bearlib/languages/documentation/documentation_extraction_testdata/default.java, tests/bearlib/languages/documentation/documentation_extraction_testdata/default.py, tests/bearlib/languages/documentation/documentation_extraction_testdata/doxygen.py
Add support for :raises xyz:
Add subsequent test cases.
Closes https://github.com/coala/coala/issues/4279
them. …
=> DocumentationAPI: Support for :raises xyz:

coalib/coala_ci.py, coalib/coala_format.py, coalib/coala_json.py, tests/coalaCITest.py, tests/coalaFormatTest.py, tests/coalaJSONTest.py
=> Replace 'binary' with 'executable'

coalib/bearlib/aspects/Metadata.py, coalib/bearlib/aspects/Redundancy.py, coalib/bearlib/aspects/Smell.py, coalib/bearlib/aspects/Spelling.py, coalib/bearlib/aspects/root.py, tests/bearlib/aspects/aspectsDocsTest.py
Closes https://github.com/coala/coala/issues/4305
=> aspects/Smell: Add Smell aspect

.travis.yml, circle.yml
=> CI: Cache Sphinx build directory

docs/Developers/Newcomers_Guide.rst
Added instructions about code documentation and styling
Linked Writing_Documentation.rst and PEP8 guidelines for references
Fixes https://github.com/coala/coala/issues/4255
them.
After you submit your pull request, **DO NOT click …
=> Newcomers_Guide.rst: Link style guidelines

coalib/bearlib/aspects/__init__.py, coalib/bearlib/aspects/exceptions.py, coalib/bearlib/aspects/meta.py, tests/bearlib/aspects/ClassTest.py, tests/bearlib/aspects/CollectionsTest.py, tests/bearlib/aspects/ExceptionsTest.py, tests/bearlib/aspects/ModuleTest.py
Closes https://github.com/coala/coala/issues/4381
=> Aspects: Create exception for aspects lookup

coalib/bearlib/languages/documentation/DocumentationComment.py, tests/bearlib/languages/documentation/DocumentationCommentTest.py
missing ending colon makes parser to break.
Fixes https://github.com/coala/coala/issues/2143
them. …
=> DocumentationComment: Fix missing ending colon

docs/Developers/Git_Basics.rst
Add link to a guide that step by step describes
how to resolve Mid-Rebase conflicts.
Closes https://github.com/coala/coala/issues/4315
them.
When …
=> Git_Basics: Add link to Mid-Rebase conflict guide

docs/Developers/Writing_Native_Bears.rst
Adds the outputs of various commands used as examples in the tutorial
along with their explanation when available.
Closes https://github.com/coala/coala/issues/4406
them. …
=> Writing_Native_Bears.rst: Add explained outputs

docs/Developers/Bear_Installation_Tool.rst
clarify that cib is broken
Add a sentence explaining that cib
is broken
Closes https://github.com/coala/coala/issues/4344
them. …
=> Bear_Installation_Tool.rst: Clarify cib's presence

docs/Developers/Review.rst
Adds review queue link in the review guide
for the reviewers.
Closes https://github.com/coala/coala/issues/4435
them. …
=> Review.rst: Add review queue link

docs/Developers/Git_Basics.rst
Change Git_Basics.rst to explain why we use
different branches and also explain branch
naming conventions.
Closes https://github.com/coala/coala/issues/3253
them. …
=> Git_Basics.rst: Be more forceful about using branches

docs/Developers/Newcomers_Guide.rst
removed double quotes that enclosed -pull request and also unwanted
underline
Fixes https://github.com/coala/coala/issues/4442
them. …
=> Newcomers_Guide.rst: Remove bolding from heading

docs/Developers/Newcomers_Guide.rst
Added a note in the last step.
Closes #4387 
them.
=> Added in docs that newcomers shouldn't delete forks

docs/Developers/Newcomers_Guide.rst
Suggestion for newcomers to join the gitter community using their GitHub account has been added to Newcomers_Guide.rst
Fixes: [#4466](https://github.com/coala/coala/issues/4466) 
them. …
=> Newcomers_Guide.rst: Gitter login using GitHub

coalib/collecting/Dependencies.py, coalib/core/CircularDependencyError.py, coalib/core/Graphs.py, docs-requirements.txt, tests/collecting/DependenciesTest.py, tests/core/CircularDependencyErrorTest.py
Cherry-picks fixes for https://github.com/coala/coala/issues/4329 and  https://github.com/coala/coala/issues/4191
=> Release 0.11 fixes

coalib/coala.py, coalib/coala_modes.py, coalib/collecting/Collectors.py, coalib/parsing/DefaultArgParser.py, coalib/parsing/FilterHelper.py, coalib/parsing/InvalidFilterException.py, coalib/parsing/filters/CanDetectFilter.py, coalib/parsing/filters/CanFixFilter.py, coalib/parsing/filters/Filter.py, coalib/parsing/filters/LanguageFilter.py, coalib/parsing/filters/__init__.py, coalib/settings/ConfigurationGathering.py, tests/coalaTest.py, tests/collecting/CollectorsTest.py, tests/parsing/FilterTest.py, tests/test_bears/JavaTestBear.py, tests/test_bears/LinterBear.py
Closes https://github.com/coala/coala/issues/2509
them.
instead.
Please …
=> DefaultArgParser: Add generic filter-by option

RELEASE_NOTES.rst, coalib/collecting/Collectors.py, coalib/misc/Constants.py, docs/Developers/Development_Setup.rst, docs/Developers/Writing_Native_Bears.rst, tests/coalaTest.py
Fixes `pip` to `pip3` for better readability.
Closes https://github.com/coala/coala/issues/4413
them. …
=> Writing_Native_Bears.rst: Typo error fixed

tests/core/CoreTest.py
Simple generator statements have been replaced with alternative
ones.
Closes https://github.com/coala/coala/issues/4493
them. …
=> CoreTest.py: Replace generator statements

coalib/collecting/Collectors.py, tests/TestUtilities.py, tests/settings/ConfigurationGatheringTest.py
Fixes https://github.com/coala/coala/issues/4541
=> Collectors: Stabilise bear order

docs/Developers/Git_Basics.rst
Fixes https://github.com/coala/coala/issues/4221
=> Git_Basics.rst: Correct RST Syntax

coalib/coala.py, coalib/parsing/FilterHelper.py
It moves the logic of applying multiple filters from coala CLI to
FilterHelper
Closes https://github.com/coala/coala/issues/4498
them.
When asked for …
=> Filter: Move filtering logic in FilterHelper

coalib/coala.py, coalib/coala_modes.py, coalib/parsing/FilterHelper.py
It renames `get_filtered_bears` to `apply_filter` and
`filter_bears` to `apply_filters`.
Closes https://github.com/coala/coala/issues/4586
them.
When …
=> FilterHelper: Rename filter functions

coalib/settings/ConfigurationGathering.py
UPDATE ConfigurationGathering.py
Added the :return: statement documentation at L#152.
Closes #4534
=> Fix for issue #4534

coalib/coala_main.py, tests/coalaCITest.py
Closes https://github.com/coala/coala/issues/4598
=> gsoc: Add "Executing section <section>..."

docs/Developers/Development_Setup.rst
Remove target '.._dev-notes:' at line 1.
Closes https://github.com/coala/coala/issues/4222
=> Development_Setup.rst: Remove target "dev-notes"

coalib/processes/Processing.py
Fixes https://github.com/coala/coala/issues/4596
them.
instead.
Please …
=> Processes: reorder api doc

coalib/parsing/DefaultArgParser.py
Changes the usage string of filter-by for better understanding.
Closes https://github.com/coala/coala/issues/4597
them. …
=> DefaultArgParser.py: Improve filter-by usage

coalib/results/result_actions/ShowPatchAction.py, tests/results/result_actions/ShowPatchActionTest.py
Closes https://github.com/coala/coala/issues/4618
=> Fix --no-color in ShowPatchAction

coalib/bearlib/__init__.py, coalib/bearlib/languages/Language.py, coalib/bearlib/languages/LanguageDefinition.py, coalib/results/Diff.py, coalib/results/result_actions/IgnoreResultAction.py, setup.cfg, tests/settings/SectionTest.py
Fixes #4642 , and includes PR #4641 which fixes #3065 .
=> Language __getitem__ AttributeError

coalib/settings/ConfigurationGathering.py
Modify ``warn_config_absent()`` to check list of options that at least
1 should be present. Currently, ``aspects`` option can replace
``bears`` and either one of those must present in a section for it
to run.
Fixes https://github.com/coala/coala/issues/4563
=> warn_config_absent: Check at least 1 config present

coalib/bearlib/aspects/Redundancy.py
Relates to https://github.com/coala/coala-bears/issues/2016
=> Redundancy: Add `remove_non_standard_import` taste

coalib/coala.py, coalib/coala_delete_orig.py, coalib/coala_main.py, coalib/collecting/Collectors.py, coalib/misc/Caching.py, coalib/misc/CachingUtilities.py, coalib/misc/Exceptions.py, coalib/output/ConsoleInteraction.py, coalib/output/Interactions.py, coalib/parsing/FilterHelper.py, coalib/processes/DebugProcessing.py, coalib/processes/LogPrinterThread.py, coalib/processes/Processing.py, coalib/settings/ConfigurationGathering.py, coalib/settings/SectionFilling.py, requirements.txt, tests/collecting/CollectorsTest.py, tests/output/ConsoleInteractionTest.py, tests/processes/LogPrinterThreadTest.py, tests/processes/ProcessingTest.py
This PR deprecates LogPrinter by using built-in logging.
It doesn't remove it completely so that public API is
not affected.
Closes https://github.com/coala/coala/issues/3472
them.
After you submit your pull request, **DO NOT click …
=> LogPrinter: Deprecate LogPrinter

coalib/results/Result.py, coalib/settings/Section.py, tests/settings/SectionTest.py
Checks run:
Fixes/Closes https://github.com/coala/coala/issues/4682 https://github.com/coala/coala/issues/4680 https://github.com/coala/coala/issues/4683
=> Aspect: Bugfixes

coalib/bearlib/languages/definitions/Golang.py, coalib/bearlib/languages/definitions/JSP.py, coalib/bearlib/languages/definitions/Matlab.py, coalib/bearlib/languages/definitions/ObjectiveC.py, coalib/bearlib/languages/definitions/PLSQL.py, coalib/bearlib/languages/definitions/Ruby.py, coalib/bearlib/languages/definitions/Scala.py, coalib/bearlib/languages/definitions/Swift.py, coalib/bears/Bear.py
Fixes https://github.com/coala/coala/issues/4686
them.
instead.
Please …
=> Bear: Add `language` for non_optional params

coalib/coala.py, coalib/coala_modes.py, coalib/parsing/DefaultArgParser.py, coalib/parsing/FilterHelper.py, coalib/results/result_actions/GeneratePatchesAction.py, tests/parsing/FilterTest.py
It puts FilterHelper functions into module scope and removes
unnecessary class.
Closes https://github.com/coala/coala/issues/4497
them.
When asked for …
=> FilterHelper: Move functions into module scope

coalib/bears/Bear.py
Incorrect article in Bear class description fixed.
Fixes https://github.com/coala/coala/issues/4520
=> typo corrected

coalib/misc/CachingUtilities.py
Closes https://github.com/coala/coala/issues/4674
Using single quotes for strings in docstring
examples.
Closes https://github.com/coala/coala/issues/4674
them. …
=> CachingUtilities: Use single quotes for strings

.misc/deps.sh
Restricting the number of containers in Circle CI to 2
Closes #4137
them. …
=> dep.sh: Enforce only two containers in Circle CI

.travis.yml
Fixes https://github.com/coala/coala/issues/4708
them.
instead.
Please …
=> Travis: Fix setuptools version problem

docs/Developers/Newcomers_Guide.rst
The link in Step 7 now correctly points to description of myfork
in Step 3.
Fixes https://github.com/coala/coala/issues/4733
them. …
=> Newcomers_Guide: Fix link to myfork

coalib/parsing/DefaultArgParser.py, coalib/parsing/FilterHelper.py, tests/parsing/FilterTest.py
This ensures that the block of code being used to construct a
target-specific string representation executes as an inline code.
Closes https://github.com/coala/coala/issues/4496
them. …
=> FilterHelper: Inline get_all_filters_str()

docs/Developers/Newcomers_Guide.rst
Added another sentence to the note, so that it stresses to readers that reviewing code helps them to improve themselves.
Closes https://github.com/coala/coala/issues/3254
them. …
=> Newcomers_Guide.rst: Rephrase note

coalib/bearlib/languages/documentation/DocumentationExtraction.py
=> Add file-level docstring telling what functions do

coalib/bearlib/languages/documentation/DocumentationComment.py
Fixes https://github.com/coala/coala/issues/4644
them.
instead.
Please …
=> DocumentationComment.py: Refactor line to line number

coalib/settings/Setting.py, docs/Developers/Writing_Native_Bears.rst, tests/settings/SettingTest.py
=> Define shortcut types for typed list

docs/Developers/Newcomers_Guide.rst
Clarify push command in  [Newcomer_Guide.rst](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-4-sending-your-changes)
Closes https://github.com/coala/coala/issues/4485
them. …
=> Update Newcomer_Guide.rst : Clarify push command

docs/Developers/Git_Basics.rst
Removing ambiguity between coala or coala-bears and coala/coala-bears
in Git_Basics.rst
Closes https://github.com/coala/coala/issues/4095
them.
When …
=> Git_Basics.rst: Rename 'coala/coala-bears'

docs/Developers/Useful_Links.rst
One overview, one interactive exercises and one to the python 3 regex syntax.
them. …
=> 3 New Regex Tutorial Links in Useful-Links

docs/Developers/Testing_Bears.rst, docs/Developers/Writing_Tests.rst
This update removes Glossary from Writing_Bears.rst and adds it to Testing_Bears.rst.
Closes https://github.com/coala/coala/issues/4755
=> Testing_Bears: Add Glossary

docs/Developers/Writing_Linter_Bears.rst
=> Writing Native Bears Guide: Add regex tutorial links

docs/Developers/Newcomers_Guide.rst
Closes https://github.com/coala/coala/issues/4766
- [x ] I read the [commit guidelines](http://coala.io/commit) and I've followed
them.
- [x ] I ran coala over my code locally. (*All commits have to pass …
=> Modifying Newcomer's guide : Add a general command to label a PR as process/pending review

.travis.yml, requirements.txt
Fixes https://github.com/coala/coala/issues/4794
=> requirements: Increase minimum setuptools version

docs/Developers/Adding_CI.rst
Closes https://github.com/coala/coala/issues/4006
them.
instead.
Please …
=> Adding_CI.rst: update circleCI recommendation

coalib/parsing/DefaultArgParser.py
Replace "--filter-by-language" with "--filter-by"
on help page because "--filter-by-language" is
deprecated.
Closes https://github.com/coala/coala/issues/4652
them. …
=> DefaultArgParser.py: Update coala help

docs/Developers/Testing_Bears.rst
Changed settings={'max_number_of_lines': int=20} to settings={'max_number_of_lines': 20}
Fixes https://github.com/coala/coala/issues/3873
them.
When …
=> Testing_Bears.rst: Update settings snippet

coalib/coala.py, coalib/coala_modes.py, coalib/output/ConsoleInteraction.py, tests/coalaFormatTest.py, tests/coalaJSONTest.py
=> coala: Add filter-by option for json and format

coalib/parsing/FilterHelper.py
Replaces 'args' with 'filters' in lines 38 and 39.
Closes https://github.com/coala/coala/issues/4694
them. …
=> FilterHelper.py: Correct parameter reference

docs/Developers/Writing_Native_Bears.rst
Changed 'This' to 'There' in line 125
Closes https://github.com/coala/coala/issues/4823
them.
=> Updates: Writing_Native_Bears.rst

docs/Developers/Testing_Bears.rst
This commit fixes some formatting issues in the doc file.
Closes https://github.com/coala/coala/issues/3774
them. …
=> Testing_Bears.rst: Correct the formatting

coalib/settings/ConfigurationGathering.py
Closes https://github.com/coala/coala/issues/4828
them.
instead.
Please …
=> ConfigurationGathering.py: Add missing whitespace

.coafile, docs/conf.py
Emerged from discussion https://github.com/coala/coala/commit/e275ebbf9bdad5f256dbc00c79887a88a000292c#commitcomment-22478720
Closes https://github.com/coala/coala/issues/4844
=> .coafile: Also lint docs/conf.py

tests/collecting/ImportersTest.py
The current assertions do little to assure the results
are stable.
Related to https://github.com/coala/coala/issues/4190
=> ImportersTest: Add detailed assertions

docs/Developers/Review.rst
Clarifying guidelines for `difficulty/low` reviewing
process.
Closes https://github.com/coala/coala/issues/4857
=> Review.rst: Clarify difficulty/low review process

coalib/parsing/DefaultArgParser.py, coalib/parsing/FilterHelper.py, coalib/parsing/InvalidFilterException.py, coalib/parsing/filters/__init__.py
Added the `__init__` method inside InvalidFilterException.py.
Closes: #4495
**For short-term contributors:** we understand that getting your commits well
up your stuff for the merge!
them. …
=> InvalidFilterException.py: Add constructor

coalib/parsing/InvalidFilterException.py
Change base class from Exception to LookupError.
Closes https://github.com/coala/coala/issues/4873
them.
=> InvalidFilterException: Change base class

coalib/bearlib/languages/__init__.py, coalib/bearlib/languages/definitions/TypeScript.py
This adds a definition for the TypeScript language
so that coala can work with it.
them. …
=> TypeScript.py: Add TypeScript language definition

docs/Developers/Review.rst
This corrects corobo's name
Closes #4879
them.
=> Review.rst: Change cobot to corobo

coalib/coala.py, coalib/collecting/Collectors.py, coalib/settings/ConfigurationGathering.py, tests/output/ConsoleInteractionTest.py
It adds option to print only selected bears using `--show-bears -bears`.
Closes https://github.com/coala/coala/issues/4651
them. …
=> coala: Option to print only selected bears

.gitignore
Update .gitignore to add the meta folder of Visual Studio Code.
Closes https://github.com/coala/coala/issues/4835
them. …
=> .gitignore: Add .vscode

coalib/output/ConsoleInteraction.py, coalib/parsing/DefaultArgParser.py, tests/output/ConsoleInteractionTest.py
It adds show-settings option to display optional and
non-optional settings for the bears
Closes https://github.com/coala/coala/issues/4432
them.
When …
=> DefaultArgParser: Add show-settings option

tests/coalaCITest.py
coalaCITest.py: Add --limit-files test
Add --limit-files setting
unit tests
Closes https://github.com/coala/coala/issues/4887
them. …
=> coalaCITest.py: Add --limit-files test

docs/Developers/Writing_Good_Commits.rst
Added an example showing a
good commit message for fixing
a typo in a doc string or comment
Closes https://github.com/coala/coala/issues/4034
them. …
=> Writing_Good_Commits.rst: Add commit example

docs/index.rst
Added links to user's guide and the coala homepage in the
navigation panel of the Coala API Documentation
Closes https://github.com/coala/coala/issues/4934
them. …
=> index.rst: Add links to the API Documentation page

coalib/bearlib/abstractions/Linter.py
This ensures that it replace Double Quotes with Single Quotes in Docstrings where needed. 
Closes https://github.com/coala/coala/issues/4940
them. …
=> Linter.py : Replace Double Quotes

docs/Developers/Newcomers_Guide.rst
This fixes the typo in markup
by adding '_' after the Google promotion link.
Fixes https://github.com/coala/coala/issues/4880
them. …
=> Newcomers_Guide.rst: Fix promotion link markup

coalib/coala_modes.py
=> [MRG] Add docstring for coala_modes.py mode_normal

coalib/bearlib/aspects/Formatting.py
Adds indent_type taste, specifying the type of
indent used.
Adds indent_size taste, specifying the number
of spaces used per indent.
Closes #4982
them. …
=> Formatting.py: Add indentation aspect

docs/Developers/Development_Setup.rst
Closes https://github.com/coala/coala/issues/3902
them.
instead.
Please …
=> Development Setup: Mention GitLab

coalib/misc/Compatibility.py
Add comment explaining JSONDecodeError is available since Python 3.5.x.
Closes #4156
them. …
=> Compatibility.py: Add comment

docs/Developers/Newcomers_Guide.rst
This fixes the typo in Newcomer's Guide and changes
it from ``To see all of corobo commands, ``
to ``To see all of corobo commands: ``.
Closes https://github.com/coala/coala/issues/4840
them. …
=> Newcomers_Guide.rst: Fix typo in documentation

coalib/output/ConsoleInteraction.py
Adds docstring for `return` statement of `require_setting`.
Closes https://github.com/coala/coala/issues/4045
them. …
=> ConsoleInteraction: Enhance require_setting doc

tests/coalaCITest.py
Closes https://github.com/coala/coala/issues/4885
them.
instead.
Please …
=> coalaCITest.py: Remove unused code

docs/Developers/Git_Basics.rst
Changes git installation command from git-all to git
Issue Fixed : https://github.com/coala/coala/issues/4903
them. …
=> Update git installation command

docs/Developers/Development_Setup.rst
This changes the redirecting link to installing
from git in 'Using venv' section.
Closes https://github.com/coala/coala/issues/5001
them.
When asked …
=> Development_Setup.rst: Change link address

docs/Developers/Development_Setup.rst
This changes the redirecting link to installing from git in 'Development
Setup Notes' under 'Using virtualenv' section.
Closes https://github.com/coala/coala/issues/5002
them. …
=> Development_Setup.rst: Change redirecting link

coalib/parsing/DefaultArgParser.py, tests/processes/ProcessingTest.py, tests/settings/ConfigurationGatheringTest.py
Closes https://github.com/coala/coala/issues/5022
=> Add type=PathArg to remaining FILE args

tests/parsing/FilterTest.py
The said unused import has been removed from FiterTest.py file.
Closes https://github.com/coala/coala/issues/5026
them. …
=> FilterTest.py: unused 'InvalidFilterException'

coalib/output/ConsoleInteraction.py
=> ConsoleInteraction.py: Fix a Typo

docs/Developers/Newcomers_Guide.rst
Add reference to "How To Ask Questions The Smart Way" guide.
Closes https://github.com/coala/coala/issues/4847
them.
=> Newcomers_Guide.rst: Mention smart questions

docs/Developers/Executing_Tests.rst
This changes `testing` to `test` for better readability.
Closes https://github.com/coala/coala/issues/3956
them. …
=>  Executing_Tests.rst: Fix a grammatical mistake

coalib/parsing/DefaultArgParser.py, coalib/results/result_actions/GeneratePatchesAction.py
Change ApplyPatchAction glob from * to **.
Add a test case which ensures that ApplyPatchAction
works for ESLintBear.
Fixes https://github.com/coala/coala/issues/4957
=> Fix --apply-patches not working

docs/Developers/Git_Basics.rst
This fixes the formatting for "git status"
under pushing the commit section.
Closes https://github.com/coala/coala/issues/5061
them. …
=> Git_Basics.rst: Correct formatting for git status

.coafile
Closes https://github.com/coala/coala/issues/5013
=> .coafile: Change glob of ApplyPatchAction

coalib/settings/ConfigurationGathering.py
Short Term Contributor
As suggested by @ishanSrt at #5025, I have made the required changes.
them.
instead.
Please consider helping us by reviewing other peoples pull requests as well:
- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
of the review queue. …
=> Update ConfigurationGathering.py Fixes #5025

docs/Developers/Writing_Native_Bears.rst
This updates the example code of this tutorial
to describe how to use the default built-in logging.
Closes https://github.com/coala/coala/issues/5101
them. …
=> Writing_Native_Bears.rst: Update to new logging

docs/Developers/Review.rst
Change his --> their.
Closes #5085
them.
instead.
Please consider helping …
=> Review.rst: Replace a word

.travis.yml, coalib/misc/DeprecationUtilities.py, coalib/output/ConsoleInteraction.py, requirements.txt, tests/output/ConsoleInteractionTest.py
=> Remove redundant parameters

coalib/results/Diff.py, coalib/results/SourceRange.py, tests/results/DiffTest.py, tests/results/SourceRangeTest.py
Additional simple message
Closes https://github.com/coala/coala/issues/3847
them. …
=> from_clang: Report useful error

docs/Developers/Newcomers_Guide.rst
Added a link to guide newcomers to ask questions directly in community.
Closes #4929
them. …
=> Newcomers_Guide.rst : Add smart question link

package.json
This pull request removes extra spacing on the closing bracket for dependencies in package.json.  It ensures consistency in whitespace.
Fixes https://github.com/coala/coala/issues/4056
them. …
=> package.json: Remove extra spacing

.editorconfig
This changes fies --> files.
Closes #5108
them.
instead.
Please consider …
=> .editorconfig: Correct typo

coalib/settings/FunctionMetadata.py
Fixes a typo in the comment.
Closes https://github.com/coala/coala/issues/5132
them. …
=> FunctionMetadata.py: Typo Error

coalib/coala_main.py, tests/coalaCITest.py
Closes https://github.com/coala/coala/issues/5038
them.
instead.
Please …
=> Support for section ordering

.misc/appveyor.yml
Closes https://github.com/coala/coala/issues/5207
them.
instead.
Please …
=> appveyor.yml: Remove everything related to LLVM

docs/Developers/Writing_Linter_Bears.rst
Fix typo in Writing_Linter_Bears.rst
Closes https://github.com/coala/coala/issues/5236
them. …
=> Writing_Linter_Bears.rst: Fix typo

tests/coalaCITest.py
Add --bear-dirs setting
unit tests
Closes https://github.com/coala/coala/issues/4888
them. …
=> coalaCITest.py: Add --bear-dirs test

coalib/core/Core.py, tests/core/CoreTest.py, tests/core/DependencyBearTest.py
Closes https://github.com/coala/coala/issues/4458
=> core: Don't offer implicit dependency results

docs/Developers/Writing_Documentation.rst
Writing_Documentation.rst: Fix url 
This fixes the earlier [url](http://www.sphinx-doc.org/en/latest/rest.html) to a new [url](http://www.sphinx-doc.org/en/master/rest.html). 
Fixes https://github.com/coala/coala/issues/5263
them. …
=> Writing_Documentation.rst: Fix url

coalib/results/Result.py, tests/results/ResultTest.py
Results with different diffs are now not equal.
Fixes https://github.com/coala/coala/issues/4400
them. …
=> Result.py: Compare diffs

docs/Developers/Development_Setup.rst
Updates the documentation generation command from ``make html`` to ``python3 setup.py docs``.
Closes coala/coala#5062
them. …
=> Development_Setup.rst: Update Documentation generation instructions

docs/Developers/Writing_Good_Commits.rst
This fixes the typo and changes
it from Fixes --> Closes.
Closes https://github.com/coala/coala/issues/5195
them. …
=> Writing_Good_Commits.rst: Fix typo

PULL_REQUEST_TEMPLATE.md
Closes https://github.com/coala/coala/issues/5314
them.
instead.
Please …
=> PULL_REQUEST_TEMPLATE.md: Change cobot to corobo

docs/Developers/Development_Setup.rst
Closes https://github.com/coala/coala/issues/5276
them.
instead.
Please …
=> Development_Setup: Change cd - to cd ..

docs/Developers/Writing_Linter_Bears.rst
Removing an ambiguity in 'Using Severities' section.
Just deleted a sentence that contained confusing info
because there are enough explanations given in the
beginning of the paragraph.
Closes https://github.com/coala/coala/issues/5248
them.
pass on every …
=> Writing_Linter_Bears.rst: Clean docs

docs/Developers/Review.rst
This commit reflects the recent changes how
the developers respond to pull requests.
Closes https://github.com/coala/documentation/issues/529
them. …
=> Review.rst: Update review docs

coalib/output/ConsoleInteraction.py
This fixes error message from
enter a valid letter. -> enter a valid letter or number.
Fixes https://github.com/coala/coala/issues/5219
=> ConsoleInteraction.py : Fix error message

coalib/bearlib/languages/definitions/Matlab.py
Closes https://github.com/coala/coala/issues/5282
them.
instead.
Please …
=> Matlab.py: Add comment delimiter for Matlab & Octave

coalib/results/result_actions/ShowAppliedPatchesAction.py
The success message have been changed from,
All action applied --> Showing Applied Patches.
Fixes https://github.com/coala/coala/issues/5192
them. …
=> ShowAppliedPatchesAction.py : Success Message

docs/Developers/Writing_Good_Commits.rst
=> Fixes #3259 - Modified: Writing_Good_Commits.rst

coalib/bearlib/languages/definitions/Markdown.py
=> Add markdown language definition

setup.py
`man/man1` is removed for Windows as it does nothing.
Fixes https://github.com/coala/coala/issues/5320
them. …
=> setup.py: Remove man pages on Windows

.circleci/config.yml
This changes the cached paths to correct ones and flushes the old
cache by changing the name of the cache.
Fixes https://github.com/coala/coala/issues/5376
them. …
=> .circleci/config.yml: Change cached paths

docs/Developers/Development_Setup.rst
Adds brief description about "Installing from Git" section.
Closes https://github.com/coala/coala/issues/3903.
them. …
=> Development_Setup.rst: Rephrase instructions 

coalib/bearlib/languages/__init__.py
Closes https://github.com/coala/coala/issues/5360
them.
instead.
Please …
=> coalib/bearlib/languages: import Markdown

docs/Developers/Linter_Bears_Advanced.rst
Fixed indentation on line 123.
Closes https://github.com/coala/coala/issues/5337
=> Linter_Bears_Advanced.rst: Fixed indentation

coalib/output/ConsoleInteraction.py
Closes https://github.com/coala/coala/issues/5201
them.
instead.
Please …
=> ConsoleInteraction: Fix a typo

tests/coalaTest.py
Adds a temporary file, then immediately ignores it.
Ideally, coala should ignore the file and do nothing.
Closes https://github.com/coala/coala/issues/4886
them. …
=> tests/coalaTest.py: Add test case for ignore flag

coalib/settings/ConfigurationGathering.py
Refactoring of ``targets`` list ensures
simplified one line list comprehension
of ``targets`` list
Closes https://github.com/coala/coala/issues/3708
them. …
=> ConfigurationGathering.py: Refactor targets list

coalib/parsing/FilterHelper.py
This commit improves documentation of apply_filter function.
Closes https://github.com/coala/coala/issues/4583
them.
=> FilterHelper.apply_filter: Add docstring

docs/Developers/Newcomers_Guide.rst, docs/_static/custom.css
This adds color schemes for different types of blocks
and catgorizes them into important, caution and notes.
Closes https://github.com/coala/coala/issues/3704
=> Newcomers_Guide: Improves emphasis of material

docs/Developers/Newcomers_Guide.rst
It contains the documentation for Gitlab coala.
Closes https://github.com/coala/coala/issues/3901
them. …
=> Newcomers_Guide.rst: Add reference to GitLab repo

.circleci/config.yml, .misc/appveyor.yml, .travis.yml, coalib/output/ConsoleInteraction.py, tests/coalaJSONTest.py
The output of coala -B --json should be
similar to coala -B.
Fixes https://github.com/coala/coala/issues/5156
them. …
=> ConsoleInteraction.py: Fix coala -B --json

.coafile, RELEASE_NOTES.rst, docs/Developers/Adding_CI.rst, docs/Developers/Development_Setup.rst, docs/Developers/External_Bears.rst, docs/Developers/Newcomers_Guide.rst, docs/Developers/Writing_Linter_Bears.rst
Update .coafile with RSTcheckBear.
Closes https://github.com/coala/coala/issues/4209
them. …
=> .coafile: Use RSTcheckBear and update .coafile

.circleci/config.yml, .misc/appveyor.yml, .travis.yml
Not all bears load properly in coala CI,
and this command is returning a non-zero exit code.
Related to https://github.com/coala/coala/issues/5406
them. …
=> CI: Remove coala -B --json

docs/Developers/Review.rst
Split off from https://github.com/coala/coala/pull/3657
=> Review.rst: Add more details for reviewers

.circleci/config.yml, test-requirements.txt
Do now allow pip 10 to be installed.
It breaks pytest_reqs
Closes https://github.com/coala/coala/issues/5409
them. …
=> test-requirements.txt: Require pip 9

docs/Developers/Linter_Bears_Advanced.rst
Add details about ``process_output_unified_diff``,
``process_output_corrected`` and ``process_output_regex``.
Closes https://github.com/coala/coala/issues/4120
them. …
=> Linter_Bears_Advanced.rst: Linter tutorials brush-up

coalib/bearlib/languages/documentation/DocumentationComment.py, coalib/bears/Bear.py, coalib/results/TextPosition.py, tests/bearlib/abstractions/LinterTest.py, tests/bearlib/abstractions/linter_test_files/test_linter.py, tests/bears/BearTest.py, tests/results/TextPositionTest.py, tests/results/TextRangeTest.py
Raise an exception when a line or column offset is zero.
Closes https://github.com/coala/coala/issues/5355
them. …
=> TextPosition.py: Raise exception for zero offset

docs/Developers/NextGen_Core.rst, docs/index.rst
Closes: https://github.com/coala/coala/issues/4584
them.
instead.
Please …
=> docs: Adds NextGen-Core docs

coalib/bearlib/languages/documentation/DocumentationComment.py, tests/bearlib/languages/documentation/DocumentationCommentTest.py
Parse cross-reference from doc strings so that they can be validated afterwards. This could have help prevented the error fixed in #3842.
them.
=> DocComment: Parse references to different objects in docstring

setup.py
Related to https://gitlab.com/coala/mobans/merge_requests/3
them.
instead. …
=> setup.py: Sync moban

coalib/bearlib/languages/__init__.py, coalib/bearlib/languages/definitions/Jinja2.py, tests/results/result_actions/IgnoreResultActionTest.py
Closes https://github.com/coala/coala/issues/5107
them.
instead.
Please …
=> Jinja2.py: Add support for ignore comments

coalib/bearlib/aspects/Formatting.py
There was a typo in the formatting aspect file, inside
the LineLength class. In the docs subclass the variable
"example_langague" was changed to "example_language".
Fixes https://github.com/coala/coala/issues/5446
them.
After you …
=> Formatting.py: Fixing a typo

tests/parsing/FilterTest.py
Import `available_filters` directly from coalib.parsing.filters
Closes https://github.com/coala/coala/issues/5331
them. …
=> FilterTest.py: Import available_filters directly

docs/Developers/Executing_Tests.rst
Mention codecov.io and explain why
100% test coverage not possible
while executing tests.
Fixes https://github.com/coala/coala/issues/5444
them.
When …
=> Executing_Tests.rst: Mention codecov

docs/Developers/Writing_Linter_Bears.rst
Adds missing code and changes it from
create_arguments(config_file) --> create_arguments(self, config_file)
Fixes https://github.com/coala/coala/issues/5354
them. …
=> Writing_Linter_Bears.rst: Fix method definition

.coafile, coalib/bearlib/aspects/__init__.py, coalib/bearlib/aspects/meta.py, coalib/bearlib/languages/definitions/C.py, coalib/bearlib/languages/definitions/CPP.py, coalib/bearlib/languages/documentation/DocumentationExtraction.py, coalib/bearlib/naming_conventions/__init__.py, tests/bearlib/aspects/CollectionsTest.py, tests/coalaTest.py, tests/collecting/CollectorsTest.py, tests/parsing/LineParserTest.py
https://github.com/coala/coala
them.
instead.
Please consider helping us …
=> Fix invalid escape sequence and remove W605 from ignore list

.misc/check_moban.sh, .moban.yaml, .travis.yml
Remove cloning of upstream setupmobans.
Use stages, and allow moban to fail except
pushes to master.
Related to https://gitlab.com/coala/mobans/merge_requests/25
them. …
=> .travis.yml: Add separate moban job

docs/Developers/Testing_Bears.rst
This changes the description of ``check_validity`` in Example 2
to avoid ambiguity and helps understand its behavior by
short explanations for both usages from example.
Closes https://github.com/coala/coala/issues/5439
them.
After …
=> Testing_Bears.rst: Change check_validity docs

.misc/appveyor.yml, .misc/run_with_env.cmd, setup.py
=> setup.py: Sync moban template

coalib/bearlib/aspects/Formatting.py
This adds more description to `preferred_quotation`
taste of `Quotation` aspect to clarify it more.
Closes #5520
them. …
=> Formatting: Add description to `preferred_quotation` 

docs/Developers/Newcomers_Guide.rst
This command helps to run tests locally
after installing dependencies.
Closes https://github.com/coala/coala/issues/5404
them. …
=> Newcomers.rst: Add a command pytest to the guide

coalib/io/FileFactory.py, tests/io/FileFactoryTest.py, tests/io/FileFactoryTestFiles/test1.txt, tests/io/FileFactoryTestFiles/test2.txt
This adds the FileFactory class. Objects of this
class will be used to represent files and
replace the file contents in the file dict.
Closes https://github.com/coala/coala/issues/3530
cc @Makman2 @fneu @shreyans800755 
them.
After …
=> Add FileFactory.py

coalib/io/Directory.py, tests/io/DirectoryTest.py, tests/io/DirectoryTestDir/Dir1/test2.txt, tests/io/DirectoryTestDir/Dir2/test3.txt, tests/io/DirectoryTestDir/test1.txt
Directory class will act as an interface
to directories providing useful information
about them. The objects of this class can be
used by bears that operate only on directories
and perform analysis based on the things like
directory structure
Closes https://github.com/coala/coala/issues/4999
them.
likely receive a lot of bot …
=> Add Directory class

.ci/check_man.sh, .circleci/config.yml, .travis.yml
Adds test to Travis CI to verify that `man` can load man page
correctly.
Closes https://github.com/coala/coala/issues/5321
them. …
=> .travis.yml: Add man page test

.travis.yml
This makes Python 3.6 the sentinel job,
so it runs by itself initially and causes
all other jobs to be cancelled if it fails.
them. …
=> .travis.yml: Add sentinel job

coalib/bearlib/languages/definitions/TypeScript.py
Closes https://github.com/coala/coala/issues/5463
them.
instead.
Please …
=> TypeScript.py: Change aliases to type tuple

setup.cfg, test-requirements.txt
See https://travis-ci.org/jayvdb/coala/jobs/394414992#L814
=> Add pytest-profiling

coalib/results/result_actions/ResultAction.py
This fixes the typo and changes
it from :result --> :result:
Fixes https://github.com/coala/coala/issues/5223
them. …
=> ResultAction.py: Fix docstring typo

.gitignore, .moban.yaml, setup.cfg, setup.py, test-requirements.txt
=> Sync moban

docs/Developers/Development_Setup.rst
This fix Broken Links in venv and
virtualenv section. 
Fixes #5556 
them. …
=> Development_Setup.rst: Fix Broken Links

coalib/bearlib/languages/definitions/Tcl.py
This creates a basic language file for tcl in
coala language definitions.
Closes https://github.com/coala/coala/issues/5570
them. …
=> Tcl: Create basic language file for tcl

coalib/bearlib/languages/definitions/m4.py
This creates a basic language file for m4 in
coala language definitions.
Closes https://github.com/coala/coala/issues/5569
them. …
=> m4: Create language file for m4

coalib/bears/Bear.py, coalib/bears/GlobalBear.py, coalib/parsing/DefaultArgParser.py, coalib/processes/Processing.py, tests/bears/BearTest.py, tests/bears/DebugBearsTest.py, tests/processes/ProcessingTest.py
Moved from https://github.com/RaiVaibhav/coala/pull/5
Related to https://github.com/coala/coala/issues/1101
=> Add: Debugging Interface

coalib/bearlib/languages/definitions/PowerShell.py
This creates a basic language file for PowerShell in
coala language definitions.
Closes https://github.com/coala/coala/issues/5582
them.
When asked …
=> PowerShell: Create language file for PowerShell

docs/Developers/Newcomers_Guide.rst
This add mention of GitLab newcomers group.
Closes https://github.com/coala/coala/issues/5546
them. …
=> Newcomers_Guide.rst: Add GitLab newcomers group

docs/Developers/Debug_Bears.rst, docs/index.rst
Related to https://github.com/coala/coala/issues/1101
=> Debug_Bears.rst: Add Debug bears docs

coalib/io/FileFactory.py, coalib/io/memoized_property.py, tests/io/FileFactoryTest.py
=> Add memoization to FileFactory

docs/Developers/Useful_Links.rst
The new link points to working reST documentation page.
Closes https://github.com/coala/coala/issues/5604
them. …
=> Useful_Links.rst: Change Basic rST link

coalib/bearlib/languages/definitions/VisualBasic.py
This creates a basic language file for visual basic in
coala language definitions.
Closes https://github.com/coala/coala/issues/5578
them.
When asked …
=> VisualBasic: Create language file for Visual Basic

.travis.yml
Related to https://github.com/coala/meta/issues/123
Also removes the GitCommitBear hack around
https://github.com/coala/coala-bears/issues/1037
=> .travis.yml: Use bears master

.moban.yaml
This was omitted from 54622c2.
Related to https://github.com/coala/coala/pull/5618
them. …
=> .moban.yaml: Add cached_property

.moban.dt/core-test-requirements.txt.jj2, .moban.yaml, requirements.txt, test-requirements.txt
testfixtures is moved to test-requirement.txt
so that coala does not depend on specific versions
of testing libraries which may conflict with versions
coala users need installed for their own project.
Fixes https://github.com/coala/coala/issues/5335
them.
pass …
=> requirements.txt: Remove testfixtures

.misc/appveyor.yml, setup.py
Closes https://github.com/coala/coala/issues/5640
them.
instead.
Please …
=> appveyor.yml: Sync moban

.moban.yaml, requirements.txt
=> requirements.txt: Use coala-utils master

docs/Developers/Writing_Tests.rst
This remove unwanted back-quotes in the documentation.
There is attempt to make the code bold & inline literal together.
Fixes https://github.com/coala/coala/issues/3855
them. …
=> Update Writing_Tests.rst: Remove unwanted quotes

coalib/bearlib/aspects/Smell.py
This fixes typo and changes Customer... to Customer {
Fixes https://github.com/coala/coala/issues/5364
them. …
=> Smell.py: Fix docstring typo

test-requirements.txt
Sync with mobans template.
them.
instead.
Please consider helping us by …
=> test-requirements.txt: Moban Sync

tests/TestUtilities.py, tests/coalaJSONTest.py, tests/collecting/CollectorsTest.py, tests/settings/ConfigurationGatheringTest.py
Update tests to use it.
them.
instead.
Please consider helping us by …
=> TestUtilities: Add sorted test bear list

coalib/collecting/Collectors.py, coalib/settings/ConfigurationGathering.py, tests/settings/ConfigurationGatheringTest.py
Fixes https://github.com/coala/coala/issues/5654
them.
instead.
Please …
=> Document unsorted bear lists

coalib/collecting/Collectors.py, coalib/parsing/DefaultArgParser.py, tests/coalaJSONTest.py, tests/coalaTest.py, tests/parsing/DefaultArgParserTest.py
Related to https://github.com/coala/coala/issues/4166
them.
instead. …
=> DefaultArgParser: Remove pragma nocover

tests/coalaJSONTest.py, tests/coalaTest.py
Fixes https://github.com/coala/coala/issues/5671
them.
instead.
Please …
=> coalaJSONTest: Remove unnecessary second patch

coalib/misc/CachingUtilities.py, coalib/misc/Constants.py
=> Constants: Move USER_DATA_DIR to CachingUtilities

docs/Developers/Debug_Bears.rst
Related to https://github.com/coala/coala/issues/1101
=> Debug_bears.rst: Add Debugger Settings docs

coalib/bearlib/languages/definitions/VisualBasic.py, coalib/bearlib/languages/definitions/__init__.py
Some langauges have language specific line length restriction.
This adds `max_line_length` restriction for VB.
them. …
=> VisualBasic: Add `max_line_length`

.circleci/config.yml, .moban.yaml, requirements.txt, setup.py
=> setup.py: Require dev release of depman

.moban.dt/core-setup.cfg.jj2, .moban.yaml, setup.cfg, tests/conftest.py
Also use template for tests/conftest.py
them.
instead.
Please consider …
=> setup.cfg: Use template

docs/Developers/Meta-review.rst, docs/index.rst
Closes https://github.com/coala/coala/issues/5513
them.
instead.
Please …
=> Meta-review.rst: Add meta-review docs

coalib/misc/CachingUtilities.py
Closes https://github.com/coala/coala/issues/5642
them.
instead.
Please …
=> CachingUtilities.py: Remove unused local variable

.coafile
Related to #5375.
them.
instead.
Please consider helping us by reviewing …
=> .coafile: Modify circleci config file location

coalib/testing/LocalBearTestHelper.py, tests/testing/LocalBearTestHelperTest.py
This modifies `LocalBearTestHelper` to make it compatible
for testing `aspects` in coala-bears.
Closes https://github.com/coala/coala/issues/5637
them. …
=> LocalBearTestHelper: Modify for `aspects` testing

coalib/bears/Bear.py, coalib/parsing/DefaultArgParser.py, tests/bears/BearTest.py
Add Profiler Interface.
Related to https://github.com/coala/coala/issues/565
=> Add: Profiling Interface

docs/Developers/Profile_Bears.rst, docs/index.rst
Related to https://github.com/coala/coala/issues/565
=> Profile_Bears: Add Profiling Interface doc

coalib/coala_main.py
Changed the Variable name from STR_ENTER_NUMBER to STR_ENTER_LETTER
Changed the value of Variable from 'Enter number (Ctrl-D to exit)' to 'Enter letter (Ctrl-D to exit)'
Fixes https://github.com/coala/coala/issues/5685
them.
After …
=> coala_main.py: Change variable name and value

coalib/bearlib/languages/__init__.py, coalib/bearlib/languages/definitions/XML.py, tests/TestUtilities.py
Closes https://github.com/coala/coala/issues/5692
them.
instead.
Please …
=> XML.py: Add language definition for XML

.misc/appveyor.yml, setup.cfg, test-requirements.txt
=> Sync templates

coalib/coala.py, coalib/coala_ci.py, coalib/coala_delete_orig.py, coalib/coala_format.py, coalib/coala_json.py, setup.cfg
Related to https://github.com/coala/coala/issues/4166
Split off from https://github.com/coala/coala/pull/4169
them. …
=>  setup.cfg: Allow non-coverage of sys.exit(main())

coalib/bearlib/aspects/Formatting.py
This adds `min_file_length` and `include_blank_lines`
as tastes to `FileLength` aspect.
them. …
=> Formatting: Add tastes to `FileLength` aspect

coalib/coala_main.py, coalib/io/FileProxy.py, coalib/misc/Caching.py, coalib/processes/Processing.py, tests/io/FileProxyTest.py, tests/misc/CachingTest.py, tests/processes/ProcessingTest.py
Adds support for FileProxies and analysis of in-memory files.
Known Shortcomings:
- Cannot yet work with apply-patch actions.
- File Proxies cannot yet work with caching disabled.
=> Add Support for FileProxies

coalib/io/FileFactory.py, coalib/processes/Processing.py, tests/io/FileFactoryTest.py, tests/processes/ProcessingTest.py, tests/processes/file_factory_test_files/a_bear_test.txt, tests/processes/file_factory_test_files/b_bear_test.txt, tests/processes/file_factory_test_files/c_bear_test.txt, tests/processes/file_factory_test_files/d_bear_test.txt, tests/processes/file_factory_test_files/e_bear_test.txt, tests/processes/file_factory_test_files/factory_test.txt, tests/processes/file_factory_test_files/n_bear_test.txt, tests/processes/file_factory_test_files/n_bear_test2.txt, tests/processes/file_factory_test_files/x_bear_test.txt
=> Integrate FileFactory with the core

.misc/appveyor.yml, .misc/run_with_env.cmd
=> appveyor.yml: Install test requirements first

coalib/bearlib/languages/__init__.py, coalib/bearlib/languages/definitions/JSON.py, tests/TestUtilities.py
Closes https://github.com/coala/coala/issues/5730
=> JSON.py: Add language definition for JSON

coalib/bearlib/languages/definitions/JavaScript.py
Closes https://github.com/coala/coala/issues/5603
them.
instead.
Please …
=> JavaScript.py: Add alias 'node' to language JavaScript

coalib/coala.py, coalib/parsing/FilterHelper.py, coalib/results/result_actions/GeneratePatchesAction.py, tests/parsing/FilterHelperTest.py
Change the filters input from list to dict
Fixes https://github.com/coala/coala/issues/5398
them. …
=> FilterHelper.py: Rewrite filters

coalib/core/__init__.py
Closes https://github.com/coala/coala/issues/5537
cc @jayvdb @Makman2 
them. …
=> core/__init__.py: Add module docstrings

docs/Developers/Newcomers_Guide.rst
Mentioned Adding CI info in Step 4 of Newcomers' Guide.
Closes https://github.com/coala/coala/issues/3755.
them. …
=> Newcomers_Guide.rst: Mention "Adding CI"

.coafile
According to coala's warnings.
=> .coafile: Remove trailing globstars

.misc/appveyor.yml, .moban.yaml
=> .ci/appveyor.yml: Add Python 3.6 jobs

.travis.yml
Unsupported versions do not need requirements
pre-installed.  This also prevents version
constraints in dependencies from breaking the job.
Closes https://github.com/coala/coala/issues/5636
them. …
=> .travis.yml: Disable install on unsupported

coalib/bearlib/languages/__init__.py, coalib/bearlib/languages/definitions/Bash.py, coalib/bearlib/languages/definitions/KornShell.py, coalib/bearlib/languages/definitions/ZShell.py, tests/TestUtilities.py
=> Definition

setup.cfg
Closes https://github.com/coala/coala/issues/5756
them.
instead.
Please …
=> setup.cfg: Raise Appveyor timeout limit

coalib/bearlib/languages/definitions/SCSS.py, tests/TestUtilities.py
Add a new python file in coalib/bearlib/languages/definitions/SCSS.py
Closes https://github.com/coala/coala/issues/5739
=> SCSS.py: Add SCSS.py file

docs/Developers/Writing_Good_Commits.rst
Closes https://github.com/coala/coala/issues/5738
them.
instead.
Please …
=> Writing_Good_Commits.rst: Fix Mistake

coalib/bearlib/languages/definitions/CPP.py
This removes unnecessary blank line
between aliases and extensions.
Closes https://github.com/coala/coala/issues/5762
them. …
=> CPP.py: Remove blank line

docs/Developers/Writing_Documentation.rst
This modifies make html-->python3 setup.py docs.
Documentation can be tested locally
by running python3 setup.py docs in the
root directory, not by make html.
Closes https://github.com/coala/coala/issues/5432
them. …
=> Writing_Documentation.rst: Modify a command

coalib/bearlib/languages/definitions/Haskell.py, tests/TestUtilities.py
Add a new python file in coalib/bearlib/languages/definitions/Haskell.py
Closes https://github.com/coala/coala/issues/5330
=> Haskell.py: Add Haskell.py file

tests/bearlib/languages/documentation/DocumentationCommentTest.py, tests/bearlib/languages/documentation/documentation_extraction_testdata/default.py
Removes docstrings and fixes tests to
ensure PEP257 adherence.
Fixes https://github.com/coala/coala/issues/4566
them. …
=> default.py: Remove erroneous mention of docstrings

docs/.gitignore, docs/index.rst, docs/release_notes.rst
Release Notes are now published at api docs.
I was not familiar with reStructuredText.
I was initially trying to add ```Release Notes``` in 
```rst
.. toctree::
:caption: Home
:hidden:
Welcome <self>
Homepage <http://coala.io/#/home>
Release Notes <release_notes>
Code of Conduct <http://coala.io/coc>
```
but it was giving out every title in this toctree, which is not suitable so I shifted ```Release Notes``` to it's own ```toctree```.
Also to commit ```release_notes.rst``` i have to exclude it from ```.gitignore```.
Closes: #5724 
for you to learn this. Just drop us a …
=> Release notes now published at api docs

docs/Developers/Newcomers_Guide.rst
The update modifies the note into a note block.
Fixes https://github.com/coala/coala/issues/5605
them. …
=> docs: Update Newcomers_Guide.rst

tests/parsing/ConfParserTest.py
This fixes multiple occurences of typos in the comments
omment --> comment
inexistent --> non-existent
Fixes https://github.com/coala/coala/issues/5785
them. …
=> ConfParserTest.py: Fix typos in comments

.gitignore, setup.cfg, test-requirements.txt
Sync with mobans template
them.
instead.
Please consider helping us by …
=> moban: Moban Sync

coalib/misc/CachingUtilities.py
Fix description for pickle_dump and pickle_load 
functions.
Fixes https://github.com/coala/coala/issues/5442
them. …
=> CachingUtilities.py: Fix description

coalib/results/result_actions/OpenEditorAction.py
Issue in focus: #5150 
Added VSCode to the list of known GUI Editors.
Clarifications:
- VSCode is has it's path linked to variable `code`, hence the name code. This is true for Windows, MacOS and Linux(Arch Linux, Ubuntu and Linux Mint are tested upon) and is evident from their documentation on [Windows](https://code.visualstudio.com/docs/editor/command-line) and [macOS](https://code.visualstudio.com/docs/setup/mac)
There is an internal command too, to set the path variable specifiaclly to `code` as can be seen from this gif:
Guidance Required:
- There exists a way to open a file to a particular line and position in VSCode but doesn't follow the scheme like the rest of the editors. In order to open a file to a particular location, the command goes: 
`$code <file_name>:{line}:{column} -g`. …
=> Addition of Visual Studio Code to the list of known editors

coalib/settings/ConfigurationGathering.py, tests/settings/ConfigurationGatheringTest.py
This changes COAFILE_OUTPUT to refer to .coafile
Closes https://github.com/coala/coala/issues/5417
them. …
=> ConfigurationGathering.py: Change COAFILE_OUTPUT to refer to .coafile

coalib/bearlib/languages/__init__.py, coalib/bearlib/languages/definitions/antlr.py, tests/TestUtilities.py
This adds the language definitions
for g4 files in coala.
Closes https://github.com/coala/coala/issues/5822
them. …
=> antlr.py: Add g4 file

coalib/bearlib/languages/__init__.py, coalib/bearlib/languages/definitions/D.py, tests/TestUtilities.py
=> Add language definition file for D

docs/Developers/Newcomers_Guide.rst
(This is a bit raw and rough and aggressive.  Need help to tone it down a bit, while still being effective at being a challenge to newcomers, and adequately warning them that we dont care about their "one line change" -- it is going to be rejected if they dont comply with the guidelines.)
=> Newcomers_Guide.rst: Explain newcomer issues

coalib/output/ConsoleInteraction.py
This removes the unnecessary words in the docstring
Closes #5843
them. …
=> coalib/output/ConsoleInteraction.py: Modifies the docstring

coalib/results/Result.py
=> Result.py: Add docstring regarding the case that line or column is None

docs/Developers/Newcomers_Guide.rst
In step 5, there are 2 new paragraphs outlining why it is
of the utmost importance that all the commits required
for solving an issue should be included in only one
Pull Request.
Closes https://github.com/coala/coala/issues/4770
them.
pass on every single …
=>    Newcomers_Guide.rst: Include 2 new paragraphs

coalib/bearlib/languages/__init__.py, coalib/bearlib/languages/definitions/TinyBasic.py, tests/TestUtilities.py
This adds a new language definition
of TinyBasic, written in Python.
Closes https://github.com/coala/coala/issues/5824
them. …
=> TinyBasic.py: Add language definition of TinyBasic

docs/Developers/Review.rst
Closes https://github.com/coala/coala/issues/3247
them.
instead.
Please …
=> Review.rst: Add review confirmation policy to doc

.editorconfig, .gitignore, .moban.yaml, setup.py, test-requirements.txt
=> Add .editorconfig to moban sync & moban sync

tests/coalaTest.py
Currently the test_coala_with_color and _without_color
tests fail with little indication of what is happening,
especially as the first warnings messages are related to
the .coafile 'Default' section.  The reported error is
trimmed, preventing the real cause of the error from
being seen in the logs.  It can be hiding a backtrace.
This introduces a new test which explicitly checks for
the two types of warnings which are currently happening,
being the 'Default' section and missing bears warnings.
These are happening because the repository .coafile is
being loaded instead of only using CLI arguments.
Then any additional warnings are considered to be an
error, and the entire output is show, so the reader
can see what is causing the problem.
Related to https://github.com/coala/coala/issues/5390 …
=> coalaTest: Add test preventing unknown warnings

docs/Developers/Newcomers_Guide.rst
=> Newcomers_Guide.rst: Commands to Send Changes

coalib/bearlib/languages/__init__.py, coalib/bearlib/languages/definitions/Verilog.py, tests/TestUtilities.py
=> Add language definition for Verilog

coalib/bearlib/abstractions/Linter.py, tests/bearlib/abstractions/LinterTest.py
=> Linter stream info

.moban.yaml, test-requirements.txt
=> Moban repo support

coalib/bearlib/languages/__init__.py, coalib/bearlib/languages/definitions/Text.py, tests/TestUtilities.py
A plain text language without delimiters
Closes https://github.com/coala/coala/issues/5904
them. …
=> languages: Add a Text language

.coafile, coalib/bearlib/languages/Language.py, coalib/bearlib/languages/documentation/DocumentationComment.py, coalib/bearlib/languages/documentation/DocumentationExtraction.py, coalib/coala_main.py, coalib/misc/BuildManPage.py, coalib/processes/Processing.py, coalib/results/Result.py, coalib/settings/Annotations.py, coalib/testing/LocalBearTestHelper.py, tests/bearlib/aspects/SubTest.py, tests/bearlib/aspects/TasteTest.py, tests/bearlib/languages/documentation/DocBaseClassTest.py, tests/bears/BearTest.py, tests/coalaCITest.py, tests/coalaDebugFlagTest.py, tests/coalaDebugTest.py, tests/coalaDeleteOrigTest.py, tests/coalaFormatTest.py, tests/coalaJSONTest.py, tests/coalaTest.py, tests/core/BearTest.py, tests/misc/CachingTest.py, tests/output/ConsoleInteractionTest.py, tests/results/result_actions/ShowAppliedPatchesActionTest.py, tests/settings/ConfigurationGatheringTest.py, tests/test_bears/internal_folder/DependentBear.py
Removed backslash line continuation and modified the `.coafile`.
Closes https://github.com/coala/coala/issues/558
Edit: I added ignore comments in areas that uses backslash line continuation in 
strings
them.
After you submit your …
=> Remove backslash line continuation

setup.cfg
Closes https://github.com/coala/coala/issues/5756
them.
instead.
Please …
=> setup.cfg: Raise AppVeyor timeout

coalib/bearlib/aspects/Formatting.py
This fixes the typo and changes it from 'the of rules' --> 'the rules'.
Closes https://github.com/coala/coala/issues/5922
them. …
=> Formatting.py: Fix typo

coalib/settings/Setting.py
This fixes the typo and changes
it from of --> off.
Closes #5933 
them. …
=> Setting.py: Fix docstring typo

docs/Developers/Writing_Good_Commits.rst
This fixes a grammatical error by changing the line
"At coala we are looking heavily at the maintainability of the code".
to
"At coala, we are looking heavily at the maintainability of the code."
Closes  coala#5927
them.
After you …
=> Writing_Good_Commits.rst: Fix grammar 

docs/Developers/Review.rst
=> Review.rst: Add a note to the reviewers

docs/Developers/Newcomers_Guide.rst
This fixes the comma typo from 
"When you say "Hello World" in chat ``corobo`` (our gitter bot) will invite you"
to
"When you say "Hello World" in chat, ``corobo`` (our gitter bot) will invite you"
Fixes https://github.com/coala/coala/issues/5924
them.
pass on …
=> Newcomers_Guide.rst: Fix docstring typo

coalib/parsing/Globbing.py
This fixes the typo and changes it from obtaines --> obtained.
Closes https://github.com/coala/coala/issues/5920
them. …
=> Globbing.py: Fix docstring typo

.gitignore, .moban.yaml, setup.cfg, test-requirements.txt
=> Sync coala-moban

.misc/Fudge.ps1, .misc/FudgeCI.ps1, .misc/FudgeGenerateFake.ps1, .misc/FudgePostInstall.ps1, .misc/Modules/FudgeTools.psm1, .misc/PrepareAVVM.ps1, .misc/appveyor.yml, .misc/check_unsupported.sh, .misc/constants.ps1, .misc/deps.python-packages.ps1, .misc/store_env_in_registry.py, .moban.yaml, Fudgefile, docs/Developers/Writing_Native_Bears.rst, setup.cfg, test-requirements.txt
Includes workaround for https://github.com/coala/coala/issues/5985
Note commit `.moban.yaml: Use local mobans` needs to be removed before merging.
=> Use Fudge for Windows development and CI

coalib/output/ConsoleInteraction.py, coalib/processes/Processing.py, coalib/results/Result.py, coalib/results/result_actions/ResultAction.py, tests/output/ConsoleInteractionTest.py, tests/processes/ProcessingTest.py, tests/results/result_actions/ResultActionTest.py
This adds a new attribute `actions` to the Result class. It is a list of action objects which are specific to the origin to that Result.
This also makes changes in `ConsoleInteraction` module and `Processing` module to incorporate these additions and support bears to define their own actions.
=> Result.py: Add actions attribute

.circleci/config.yml, .misc/appveyor.yml, .misc/check_unsupported.sh, .moban.yaml, .travis.yml, coalib/__init__.py, docs/Developers/Development_Setup.rst, docs/Developers/Writing_Tests.rst, setup.py, tests/core/ProjectBearTest.py
Fixes https://github.com/coala/coala/issues/6110
=> .travis.yml: Use existing Java SDK version

.gitignore, .misc/check_setuptools.py, .moban.yaml, .travis.yml
An attempt to fix the build errors.
=> .travis.yml: Fix build errors

.moban.yaml, .travis.yml
Fixing the unsupported job (wasn't reported in previous PR).
=> .travis.yml: Fix unsupported job

docs/Developers/Writing_bear_actions.rst, docs/index.rst
This adds a tutorial in the docs which describes how to write
actions specific to bears.
=> Tutorial for writing bear actions

docs/Developers/Adding_CI.rst
All occurances of the URL was updated
travis-ci.org -> travis-ci.com
Closes https://github.com/coala/coala/issues/6138
them. …
=> Adding_CI.rst: Update travis.org to .com

coalib/bearlib/languages/__init__.py, coalib/bearlib/languages/definitions/SASS.py, tests/TestUtilities.py
Cherry-picked a previous commit and updated the correct versions for SASS. Thanks, @Utkarsh1308!
Closes #5740
=> SASS.py: Add language definition for SASS

coalib/bearlib/aspects/decorators.py, coalib/results/Result.py, coalib/settings/ConfigurationGathering.py, docs/Developers/Writing_Native_Bears.rst, tests/settings/ConfigurationGatheringTest.py
Removed the occurrences of Aspect and Aspects
in all doc strings and comments.
Closes https://github.com/coala/coala/issues/4039
them.
When asked for …
=> Remove occurrences of Aspect(s) in docs and comments

coalib/output/printers/LogPrinter.py
=> Fix simple typo: reponsibility -> responsibility

tests/output/ConsoleInteractionTest.py
A previous PR was mergeable but needed rebasing. Thanks, @Dilshaad21! :)
Also, made a minor change so LineLengthBear no longer shows an error.
Closes #6056
=> ConsoleInteractionTest.py: Updated to reduce redundancy

docs/Developers/Development_Setup.rst
=> Development_Setup.rst: Fix dead link
